// Copyright (C) 2025 The Android Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import {
  LRLanguage,
  LanguageSupport,
  delimitedIndent,
  foldInside,
  foldNodeProp,
  indentNodeProp,
  syntaxTree,
} from '@codemirror/language';
import {
  type CompletionContext,
  type CompletionResult,
} from '@codemirror/autocomplete';
import {linter, type Diagnostic} from '@codemirror/lint';
import {styleTags, tags as t} from '@lezer/highlight';
import {parser} from './perfetto_sql.grammar'; // Generated by Lezer

// All keyword node names from the structured grammar.
const KEYWORD_NODES = [
  'SELECT', 'FROM', 'WHERE', 'AS', 'ON', 'AND', 'OR', 'NOT', 'IN', 'IS',
  'NULL', 'JOIN', 'LEFT', 'RIGHT', 'INNER', 'OUTER', 'CROSS', 'NATURAL',
  'GROUP', 'BY', 'ORDER', 'HAVING', 'LIMIT', 'OFFSET', 'UNION', 'ALL',
  'INTERSECT', 'EXCEPT', 'DISTINCT', 'ASC', 'DESC', 'WITH', 'RECURSIVE',
  'MATERIALIZED', 'CREATE', 'PERFETTO', 'TABLE', 'VIEW', 'FUNCTION',
  'MACRO', 'INDEX', 'VIRTUAL', 'USING', 'INCLUDE', 'MODULE', 'RETURNS',
  'DELEGATES', 'TO', 'CASE', 'WHEN', 'THEN', 'ELSE', 'END', 'CAST',
  'EXISTS', 'OVER', 'PARTITION', 'LIKE', 'GLOB', 'BETWEEN',
].join(' ');

export const language = LRLanguage.define({
  parser: parser.configure({
    props: [
      indentNodeProp.add({
        SelectBody: delimitedIndent({closing: ')', align: false}),
      }),
      foldNodeProp.add({
        SelectBody: foldInside,
        WithClause: foldInside,
      }),
      styleTags({
        [KEYWORD_NODES]: t.keyword,
        'Boolean': t.bool,
        'String': t.string,
        'Number': t.number,
        'LineComment': t.lineComment,
        'MacroVariable': t.variableName,
        'MacroInvocation': t.macroName,
        'FunctionCall': t.function(t.variableName),
        'ParenL ParenR': t.paren,
      }),
    ],
  }),
  languageData: {
    commentTokens: {line: '--'},
  },
});

const perfettoSqlLinter = linter((view) => {
  const diagnostics: Diagnostic[] = [];
  const tree = syntaxTree(view.state);
  tree.cursor().iterate((node) => {
    if (node.type.isError) {
      // For zero-width error nodes, highlight one char after the error position
      // so the squiggly is visible.
      const from = node.from;
      const to = node.to > node.from ? node.to : Math.min(node.from + 1, view.state.doc.length);
      diagnostics.push({
        from,
        to,
        severity: 'error',
        message: 'Syntax error',
      });
    }
  });
  return diagnostics;
});

// Node names that indicate the cursor is in a table-name position.
const TABLE_CONTEXT_NODES = new Set([
  'FromClause', 'JoinClause', 'TableRef', 'TableSource',
]);

const SQL_KEYWORDS = [
  'SELECT', 'FROM', 'WHERE', 'JOIN', 'LEFT', 'RIGHT', 'INNER', 'CROSS',
  'ON', 'USING', 'GROUP BY', 'ORDER BY', 'HAVING', 'LIMIT', 'OFFSET',
  'AS', 'AND', 'OR', 'NOT', 'IN', 'IS', 'NULL', 'BETWEEN', 'LIKE',
  'DISTINCT', 'UNION ALL', 'UNION', 'INTERSECT', 'EXCEPT',
  'CASE', 'WHEN', 'THEN', 'ELSE', 'END', 'CAST', 'EXISTS', 'OVER',
  'PARTITION BY', 'ASC', 'DESC', 'WITH',
  'CREATE PERFETTO TABLE', 'CREATE PERFETTO VIEW',
  'CREATE PERFETTO FUNCTION', 'CREATE PERFETTO MACRO',
  'CREATE PERFETTO INDEX', 'CREATE VIRTUAL TABLE',
  'INCLUDE PERFETTO MODULE', 'RETURNS', 'DELEGATES TO',
];

function isInTableContext(context: CompletionContext): boolean {
  const tree = syntaxTree(context.state);
  let node = tree.resolveInner(context.pos, -1);
  // Walk up ancestors looking for a table context node.
  while (node) {
    if (TABLE_CONTEXT_NODES.has(node.name)) return true;
    if (!node.parent) break;
    node = node.parent;
  }
  return false;
}

function makeCompletionSource(tables: readonly string[]) {
  const tableCompletions = tables.map((t) => ({
    label: t,
    type: 'class' as const,
  }));
  const keywordCompletions = SQL_KEYWORDS.map((kw) => ({
    label: kw,
    type: 'keyword' as const,
  }));

  return (context: CompletionContext): CompletionResult | null => {
    const word = context.matchBefore(/[\w.]*/);
    if (!word || (word.from === word.to && !context.explicit)) return null;

    if (isInTableContext(context)) {
      return {from: word.from, options: tableCompletions};
    }
    return {from: word.from, options: [...keywordCompletions, ...tableCompletions]};
  };
}

const DEFAULT_TABLES = [
  'sched', 'slice', 'thread_state', 'thread', 'process',
  'counter', 'counter_track', 'track', 'cpu_counter_track',
  'thread_counter_track', 'process_counter_track',
  'ftrace_event', 'raw', 'args', 'metadata',
];

export function perfettoSql(tables?: readonly string[]) {
  const completionSource = makeCompletionSource(tables ?? DEFAULT_TABLES);
  return new LanguageSupport(language, [
    perfettoSqlLinter,
    language.data.of({autocomplete: completionSource}),
  ]);
}
