// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  LineComment = 1,
  Program = 2,
  String = 3,
  Number = 4,
  Boolean = 5,
  Identifier = 6,
  Keyword = 7,
  Function = 8,
  MacroVariable = 9
