// Copyright (C) 2024 The Android Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-20.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import {time} from '../base/time';

/**
 * Provides information about the currently loaded trace.
 */
export interface TraceInfo {
  /**
   * The title of the trace, typically the file name and size.
   */
  readonly traceTitle: string;
  /**
   * The URL from which the trace was loaded, if applicable.
   */
  readonly traceUrl: string;

  /**
   * The start timestamp of the trace.
   */
  readonly start: time;
  /**
   * The end timestamp of the trace.
   */
  readonly end: time;

  /**
   * The timestamp value at the time of the Unix epoch.
   *
   * Normally some large negative value, because the Unix epoch is typically in
   * the past compared to `ts=0`.
   */
  readonly unixOffset: time;

  /**
   * The reported timezone offset in minutes from UTC.
   */
  readonly tzOffMin: number;

  /**
   * The number of import/analysis errors present in the `stats` table.
   */
  readonly importErrors: number;

  /**
   * The trace type inferred by TraceProcessor (e.g., 'proto', 'json', ...).
   *
   * See `TraceTypeToString()` in `src/trace_processor/util/trace_type.cc` for
   * all available types.
   */
  readonly traceType?: string;

  /**
   * `true` if the trace contains any ftrace data (sched or other ftrace events).
   */
  readonly hasFtrace: boolean;

  /**
   * The UUID of the trace. This is generated by TraceProcessor by either
   * looking at the `TraceUuid` packet emitted by `traced` or, as a fallback, by
   * hashing the first KB of the trace. This can be an empty string in rare
   * cases (e.g., opening an empty trace).
   */
  readonly uuid: string;

  /**
   * Whether the current trace has been successfully stored into cache storage.
   */
  readonly cached: boolean;

  /**
   * Returns `true` if the current trace can be downloaded via `getTraceFile()`.
   *
   * The trace isn't downloadable in the following cases:
   * - It comes from a source (e.g., HTTP+RPC) that doesn't support re-download
   *   due to technical limitations.
   * - Download is disabled because the trace was pushed via `postMessage` and
   *   the caller has asked to disable downloads.
   */
  readonly downloadable: boolean;
}
