# Sequence 1 defaults to track for "t1".
packet {
  trusted_packet_sequence_id: 1
  timestamp: 0
  incremental_state_cleared: true
  track_descriptor {
    uuid: 1
    thread {
      pid: 5
      tid: 1
      thread_name: "t1"
    }
  }
  trace_packet_defaults {
    track_event_defaults {
      track_uuid: 1
    }
  }
}
# Sequence 2 defaults to track for "t2".
packet {
  trusted_packet_sequence_id: 2
  timestamp: 0
  incremental_state_cleared: true
  track_descriptor {
    uuid: 2
    thread {
      pid: 5
      tid: 2
      thread_name: "t2"
    }
  }
  trace_packet_defaults {
    track_event_defaults {
      track_uuid: 2
    }
  }
}
# Should appear on default track "t1".
packet {
  trusted_packet_sequence_id: 1
  timestamp: 1000
  track_event {
    categories: "cat"
    name: "name1"
    type: 3
  }
}
# Should appear on default track "t2".
packet {
  trusted_packet_sequence_id: 2
  timestamp: 2000
  track_event {
    categories: "cat"
    name: "name2"
    type: 3
  }
}
# Should appear on overridden track "t2".
packet {
  trusted_packet_sequence_id: 1
  timestamp: 3000
  track_event {
    track_uuid: 2
    categories: "cat"
    name: "name3"
    type: 3
  }
}
