CREATE TABLE TEST(id INTEGER, val INTEGER);

INSERT INTO TEST
VALUES (1, 1), (2, NULL), (3, 3), (4, 4), (5, NULL), (6, NULL), (7, NULL);

SELECT
  id,
  LAST_NON_NULL(val)
  OVER (ORDER BY id ASC ROWS BETWEEN CURRENT ROW AND 2 FOLLOWING) AS val
FROM TEST
ORDER BY id ASC;
