packet {
  ftrace_events {
    cpu: 2
    event {
      timestamp: 751796307210
      pid: 2857
      mali_mali_KCPU_CQS_WAIT_START {
        info_val1: 1
        info_val2: 0
        kctx_tgid: 2201
        kctx_id: 10
        id: 0
      }
    }
    event {
      timestamp: 751800621175
      pid: 2857
      mali_mali_KCPU_CQS_WAIT_END {
        info_val1: 412313493488
        info_val2: 0
        kctx_tgid: 2201
        kctx_id: 10
        id: 0
      }
    }
    event {
      timestamp: 751800638997
      pid: 2857
      mali_mali_KCPU_CQS_SET {
        info_val1: 412313493480
        info_val2: 0
        kctx_tgid: 2201
        kctx_id: 10
        id: 0
      }
    }
  }
}
