# Copyright (C) 2019 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@perfetto_cfg//:perfetto_cfg.bzl", "PERFETTO_CONFIG")

cc_library(
    name = "open_csd",
    srcs = [
        "decoder/source/c_api/ocsd_c_api.cpp",
        "decoder/source/c_api/ocsd_c_api_custom_obj.cpp",
        "decoder/source/c_api/ocsd_c_api_custom_obj.h",
        "decoder/source/c_api/ocsd_c_api_obj.h",
        "decoder/source/ete/trc_cmp_cfg_ete.cpp",
        "decoder/source/etmv3/trc_cmp_cfg_etmv3.cpp",
        "decoder/source/etmv3/trc_pkt_decode_etmv3.cpp",
        "decoder/source/etmv3/trc_pkt_elem_etmv3.cpp",
        "decoder/source/etmv3/trc_pkt_proc_etmv3.cpp",
        "decoder/source/etmv3/trc_pkt_proc_etmv3_impl.cpp",
        "decoder/source/etmv3/trc_pkt_proc_etmv3_impl.h",
        "decoder/source/etmv4/trc_cmp_cfg_etmv4.cpp",
        "decoder/source/etmv4/trc_etmv4_stack_elem.cpp",
        "decoder/source/etmv4/trc_pkt_decode_etmv4i.cpp",
        "decoder/source/etmv4/trc_pkt_elem_etmv4i.cpp",
        "decoder/source/etmv4/trc_pkt_proc_etmv4i.cpp",
        "decoder/source/i_dec/trc_i_decode.cpp",
        "decoder/source/i_dec/trc_idec_arminst.cpp",
        "decoder/source/mem_acc/trc_mem_acc_base.cpp",
        "decoder/source/mem_acc/trc_mem_acc_bufptr.cpp",
        "decoder/source/mem_acc/trc_mem_acc_cache.cpp",
        "decoder/source/mem_acc/trc_mem_acc_cb.cpp",
        "decoder/source/mem_acc/trc_mem_acc_file.cpp",
        "decoder/source/mem_acc/trc_mem_acc_mapper.cpp",
        "decoder/source/ocsd_code_follower.cpp",
        "decoder/source/ocsd_dcd_tree.cpp",
        "decoder/source/ocsd_error.cpp",
        "decoder/source/ocsd_error_logger.cpp",
        "decoder/source/ocsd_gen_elem_list.cpp",
        "decoder/source/ocsd_gen_elem_stack.cpp",
        "decoder/source/ocsd_lib_dcd_register.cpp",
        "decoder/source/ocsd_msg_logger.cpp",
        "decoder/source/ocsd_version.cpp",
        "decoder/source/pkt_printers/gen_elem_printer.cpp",
        "decoder/source/pkt_printers/raw_frame_printer.cpp",
        "decoder/source/pkt_printers/trc_print_fact.cpp",
        "decoder/source/ptm/trc_cmp_cfg_ptm.cpp",
        "decoder/source/ptm/trc_pkt_decode_ptm.cpp",
        "decoder/source/ptm/trc_pkt_elem_ptm.cpp",
        "decoder/source/ptm/trc_pkt_proc_ptm.cpp",
        "decoder/source/stm/trc_pkt_decode_stm.cpp",
        "decoder/source/stm/trc_pkt_elem_stm.cpp",
        "decoder/source/stm/trc_pkt_proc_stm.cpp",
        "decoder/source/trc_component.cpp",
        "decoder/source/trc_core_arch_map.cpp",
        "decoder/source/trc_frame_deformatter.cpp",
        "decoder/source/trc_frame_deformatter_impl.h",
        "decoder/source/trc_gen_elem.cpp",
        "decoder/source/trc_printable_elem.cpp",
        "decoder/source/trc_ret_stack.cpp",
    ],
    hdrs = [
        "decoder/include/common/comp_attach_notifier_i.h",
        "decoder/include/common/comp_attach_pt_t.h",
        "decoder/include/common/ocsd_code_follower.h",
        "decoder/include/common/ocsd_dcd_mngr.h",
        "decoder/include/common/ocsd_dcd_mngr_i.h",
        "decoder/include/common/ocsd_dcd_tree.h",
        "decoder/include/common/ocsd_dcd_tree_elem.h",
        "decoder/include/common/ocsd_error.h",
        "decoder/include/common/ocsd_error_logger.h",
        "decoder/include/common/ocsd_gen_elem_list.h",
        "decoder/include/common/ocsd_gen_elem_stack.h",
        "decoder/include/common/ocsd_lib_dcd_register.h",
        "decoder/include/common/ocsd_msg_logger.h",
        "decoder/include/common/ocsd_pe_context.h",
        "decoder/include/common/ocsd_version.h",
        "decoder/include/common/trc_component.h",
        "decoder/include/common/trc_core_arch_map.h",
        "decoder/include/common/trc_cs_config.h",
        "decoder/include/common/trc_frame_deformatter.h",
        "decoder/include/common/trc_gen_elem.h",
        "decoder/include/common/trc_pkt_decode_base.h",
        "decoder/include/common/trc_pkt_elem_base.h",
        "decoder/include/common/trc_pkt_proc_base.h",
        "decoder/include/common/trc_printable_elem.h",
        "decoder/include/common/trc_raw_buffer.h",
        "decoder/include/common/trc_ret_stack.h",
        "decoder/include/i_dec/trc_i_decode.h",
        "decoder/include/i_dec/trc_idec_arminst.h",
        "decoder/include/interfaces/trc_abs_typed_base_i.h",
        "decoder/include/interfaces/trc_data_raw_in_i.h",
        "decoder/include/interfaces/trc_data_rawframe_in_i.h",
        "decoder/include/interfaces/trc_error_log_i.h",
        "decoder/include/interfaces/trc_gen_elem_in_i.h",
        "decoder/include/interfaces/trc_indexer_pkt_i.h",
        "decoder/include/interfaces/trc_indexer_src_i.h",
        "decoder/include/interfaces/trc_instr_decode_i.h",
        "decoder/include/interfaces/trc_pkt_in_i.h",
        "decoder/include/interfaces/trc_pkt_raw_in_i.h",
        "decoder/include/interfaces/trc_tgt_mem_access_i.h",
        "decoder/include/mem_acc/trc_mem_acc.h",
        "decoder/include/mem_acc/trc_mem_acc_base.h",
        "decoder/include/mem_acc/trc_mem_acc_bufptr.h",
        "decoder/include/mem_acc/trc_mem_acc_cache.h",
        "decoder/include/mem_acc/trc_mem_acc_cb.h",
        "decoder/include/mem_acc/trc_mem_acc_cb_if.h",
        "decoder/include/mem_acc/trc_mem_acc_file.h",
        "decoder/include/mem_acc/trc_mem_acc_mapper.h",
        "decoder/include/opencsd.h",
        "decoder/include/opencsd/c_api/ocsd_c_api_cust_fact.h",
        "decoder/include/opencsd/c_api/ocsd_c_api_cust_impl.h",
        "decoder/include/opencsd/c_api/ocsd_c_api_custom.h",
        "decoder/include/opencsd/c_api/ocsd_c_api_types.h",
        "decoder/include/opencsd/c_api/opencsd_c_api.h",
        "decoder/include/opencsd/ete/ete_decoder.h",
        "decoder/include/opencsd/ete/trc_cmp_cfg_ete.h",
        "decoder/include/opencsd/ete/trc_dcd_mngr_ete.h",
        "decoder/include/opencsd/ete/trc_pkt_types_ete.h",
        "decoder/include/opencsd/etmv3/etmv3_decoder.h",
        "decoder/include/opencsd/etmv3/trc_cmp_cfg_etmv3.h",
        "decoder/include/opencsd/etmv3/trc_dcd_mngr_etmv3.h",
        "decoder/include/opencsd/etmv3/trc_pkt_decode_etmv3.h",
        "decoder/include/opencsd/etmv3/trc_pkt_elem_etmv3.h",
        "decoder/include/opencsd/etmv3/trc_pkt_proc_etmv3.h",
        "decoder/include/opencsd/etmv3/trc_pkt_types_etmv3.h",
        "decoder/include/opencsd/etmv4/etmv4_decoder.h",
        "decoder/include/opencsd/etmv4/trc_cmp_cfg_etmv4.h",
        "decoder/include/opencsd/etmv4/trc_dcd_mngr_etmv4i.h",
        "decoder/include/opencsd/etmv4/trc_etmv4_stack_elem.h",
        "decoder/include/opencsd/etmv4/trc_pkt_decode_etmv4i.h",
        "decoder/include/opencsd/etmv4/trc_pkt_elem_etmv4i.h",
        "decoder/include/opencsd/etmv4/trc_pkt_proc_etmv4.h",
        "decoder/include/opencsd/etmv4/trc_pkt_proc_etmv4i.h",
        "decoder/include/opencsd/etmv4/trc_pkt_types_etmv4.h",
        "decoder/include/opencsd/ocsd_if_types.h",
        "decoder/include/opencsd/ocsd_if_version.h",
        "decoder/include/opencsd/ptm/ptm_decoder.h",
        "decoder/include/opencsd/ptm/trc_cmp_cfg_ptm.h",
        "decoder/include/opencsd/ptm/trc_dcd_mngr_ptm.h",
        "decoder/include/opencsd/ptm/trc_pkt_decode_ptm.h",
        "decoder/include/opencsd/ptm/trc_pkt_elem_ptm.h",
        "decoder/include/opencsd/ptm/trc_pkt_proc_ptm.h",
        "decoder/include/opencsd/ptm/trc_pkt_types_ptm.h",
        "decoder/include/opencsd/stm/stm_decoder.h",
        "decoder/include/opencsd/stm/trc_cmp_cfg_stm.h",
        "decoder/include/opencsd/stm/trc_dcd_mngr_stm.h",
        "decoder/include/opencsd/stm/trc_pkt_decode_stm.h",
        "decoder/include/opencsd/stm/trc_pkt_elem_stm.h",
        "decoder/include/opencsd/stm/trc_pkt_proc_stm.h",
        "decoder/include/opencsd/stm/trc_pkt_types_stm.h",
        "decoder/include/opencsd/trc_gen_elem_types.h",
        "decoder/include/opencsd/trc_pkt_types.h",
        "decoder/include/pkt_printers/gen_elem_printer.h",
        "decoder/include/pkt_printers/item_printer.h",
        "decoder/include/pkt_printers/pkt_printer_t.h",
        "decoder/include/pkt_printers/raw_frame_printer.h",
        "decoder/include/pkt_printers/trc_pkt_printers.h",
        "decoder/include/pkt_printers/trc_print_fact.h",
    ],
    copts = ['-fexceptions'] + PERFETTO_CONFIG.deps_copts.open_csd,
    defines = [
        "ENABLE_LARGE_TRACE_SOURCES",
    ],
    includes = [
        "decoder/include",
    ],
    visibility = ["//visibility:public"],
)
