packet {
  ftrace_events {
    cpu: 0
    event {
      timestamp: 99999900
      pid: 200
      napi_gro_receive_entry {
        name: "rmnet0"
        len: 512
      }
    }
    event {
      timestamp: 99999920
      pid: 300
      napi_gro_receive_exit {
        ret: 1
      }
    }
    event {
      timestamp: 99999930
      pid: 200
      napi_gro_receive_entry {
        name: "rmnet0"
        len: 512
      }
    }
    event {
      timestamp: 99999940
      pid: 300
      napi_gro_receive_exit {
        ret: 2
      }
    }
    event {
      timestamp: 99999945
      pid: 200
      kfree_skb {
        protocol: 2048
      }
    }
    event {
     timestamp: 100000000
     pid: 200
     cpu_frequency {
       cpu_id: 0
       state: 2000000
     }
    }
    event {
     timestamp: 100000000
     pid: 200
     softirq_entry {
       vec: 3
     }
    }
    event {
      timestamp: 100000000
      pid: 200
      netif_receive_skb {
        name: "rmnet0"
        len: 1024
      }
    }
    event {
      timestamp: 100090000
      pid: 234
      tcp_retransmit_skb {
        daddr: 19216801
        saddr: 127001
        dport: 5001
        sport: 56789
        state: 1
        skaddr: 77889900
      }
    }
    event {
      timestamp: 100100000
      pid: 200
      net_dev_xmit {
        name: "rmnet0"
        len: 1024
      }
    }
    event {
      timestamp: 100500000
      pid: 200
      softirq_exit {
        vec: 3
      }
    }
    event {
      timestamp: 100505000
      pid: 200
      irq_handler_entry {
        irq: 1
        name: "IPI"
      }
    }
    event {
      timestamp: 100515000
      pid: 200
      irq_handler_exit {
        irq: 1
        ret: 1
      }
    }
    event {
      timestamp: 100520000
      pid: 200
      softirq_entry {
        vec: 2
      }
    }
    event {
      timestamp: 100540000
      pid: 200
      softirq_exit {
        vec: 2
      }
    }
  }
}

packet {
  ftrace_events {
    cpu: 1
    event {
      timestamp: 1119999800
      pid: 200
      kfree_skb {
        protocol: 600
      }
    }
    event {
      timestamp: 119999900
      pid: 200
      napi_gro_receive_entry {
        name: "rmnet0"
        len: 512
      }
    }
    event {
      timestamp: 119999920
      pid: 300
      napi_gro_receive_exit {
        ret: 1
      }
    }
    event {
      timestamp: 119999930
      pid: 200
      napi_gro_receive_entry {
        name: "rmnet0"
        len: 512
      }
    }
    event {
      timestamp: 119999940
      pid: 300
      napi_gro_receive_exit {
        ret: 2
      }
    }
    event {
     timestamp: 120000000
     pid: 200
     cpu_frequency {
       cpu_id: 1
       state: 2000000
     }
    }
    event {
     timestamp: 120000000
     pid: 300
     softirq_entry {
       vec: 3
     }
    }
    event {
      timestamp: 120000000
      pid: 300
      netif_receive_skb {
        name: "rmnet0"
        len: 1024
      }
    }
    event {
      timestamp: 120100000
      pid: 300
      net_dev_xmit {
        name: "rmnet0"
        len: 1024
      }
    }
    event {
      timestamp: 120500000
      pid: 300
      softirq_exit {
        vec: 3
      }
    }
    event {
      timestamp: 120505000
      pid: 200
      irq_handler_entry {
        irq: 1
        name: "IPI"
      }
    }
    event {
      timestamp: 120515000
      pid: 200
      irq_handler_exit {
        irq: 1
        ret: 1
      }
    }
    event {
      timestamp: 120520000
      pid: 200
      softirq_entry {
        vec: 2
      }
    }
    event {
      timestamp: 120540000
      pid: 200
      softirq_exit {
        vec: 2
      }
    }
  }
}

packet {
  ftrace_events {
    cpu: 0
    event {
      timestamp: 139999900
      pid: 200
      napi_gro_receive_entry {
        name: "rmnet0"
        len: 512
      }
    }
    event {
      timestamp: 139999920
      pid: 300
      napi_gro_receive_exit {
        ret: 1
      }
    }
    event {
      timestamp: 139999930
      pid: 200
      napi_gro_receive_entry {
        name: "rmnet0"
        len: 512
      }
    }
    event {
      timestamp: 139999940
      pid: 300
      napi_gro_receive_exit {
        ret: 2
      }
    }
    event {
     timestamp: 140000000
     pid: 200
     cpu_frequency {
       cpu_id: 0
       state: 1000000
     }
    }
    event {
     timestamp: 140000000
     pid: 400
     softirq_entry {
       vec: 3
     }
    }
    event {
      timestamp: 140000000
      pid: 400
      netif_receive_skb {
        name: "rmnet0"
        len: 1024
      }
    }
    event {
      timestamp: 140100000
      pid: 400
      net_dev_xmit {
        name: "rmnet0"
        len: 1024
      }
    }
    event {
      timestamp: 140500000
      pid: 400
      softirq_exit {
        vec: 3
      }
    }
  }
}

packet {
  ftrace_events {
    cpu: 1
    event {
      timestamp: 139999900
      pid: 200
      napi_gro_receive_entry {
        name: "rmnet0"
        len: 1024
      }
    }
    event {
      timestamp: 139999920
      pid: 300
      napi_gro_receive_exit {
        ret: 3
      }
    }
    event {
      timestamp: 140000000
      pid: 200
      cpu_frequency {
        cpu_id: 1
        state: 1000000
      }
    }
    event {
      timestamp: 140000000
      pid: 500
      softirq_entry {
        vec: 3
      }
    }
    event {
      timestamp: 140000000
      pid: 500
      netif_receive_skb {
        name: "rmnet0"
        len: 1024
      }
    }
    event {
      timestamp: 140100000
      pid: 500
      net_dev_xmit {
        name: "rmnet0"
        len: 1024
      }
    }
    event {
      timestamp: 140500000
      pid: 500
      softirq_exit {
        vec: 3
      }
    }
  }
}

packet {
  ftrace_events {
    cpu: 4
    event {
     timestamp: 100000000
     pid: 200
     cpu_frequency {
       cpu_id: 4
       state: 2000000
     }
    }
    event {
      timestamp: 100000000
      pid: 600
      netif_receive_skb {
        name: "wlan0"
        len: 512
      }
    }
    event {
      timestamp: 101000000
      pid: 600
      net_dev_xmit {
        name: "wlan0"
        len: 512
      }
    }
  }
}
