packet {
  ftrace_events {
    cpu: 0
    event {
      timestamp: 20000
      pid: 0
      suspend_resume {
        action: "syscore_suspend"
        val: 0
        start: 1
      }
    }
  }
}
packet {
  ftrace_events {
    cpu: 0
    event {
      timestamp: 29999
      pid: 0
      suspend_resume {
        action: "syscore_suspend"
        val: 0
        start: 0
      }
    }
  }
}
packet {
  ftrace_events {
    cpu: 0
    event {
      timestamp: 30000
      pid: 0
      suspend_resume {
        action: "syscore_resume"
        val: 0
        start: 1
      }
    }
  }
}
packet {
  ftrace_events {
    cpu: 0
    event {
      timestamp: 40000
      pid: 0
      suspend_resume {
        action: "syscore_resume"
        val: 0
        start: 0
      }
    }
  }
}
packet {
  ftrace_events {
    cpu: 4
    event {
      timestamp: 50000
      pid: 0
      suspend_resume {
        action: "timekeeping_freeze"
        val: 4
        start: 1
      }
    }
  }
}
packet {
  ftrace_events {
    cpu: 1
    event {
      timestamp: 60000
      pid: 0
      suspend_resume {
        action: "timekeeping_freeze"
        val: 1
        start: 0
      }
    }
  }
}
