packet {
  clock_snapshot {
    clocks {
      clock_id: 6
      timestamp: 101000002
    }
  }
  trusted_packet_sequence_id: 1
  timestamp: 101000002
}
packet {
  trusted_packet_sequence_id: 1
  timestamp: 101000002
  chrome_metadata {
    background_tracing_metadata {
      triggered_rule {}
    }
    chrome_version_code: 101
    enabled_categories: "cat1,cat2,cat3"
  }
}
