packet {
  ftrace_events {
    cpu: 0
    event {
      timestamp: 1626347346
      pid: 9087
      f2fs_iostat_latency {
        dev: 0xfe2e
        d_rd_peak: 4
        d_rd_avg: 0
        d_rd_cnt: 84
        n_rd_peak: 0
        n_rd_avg: 0
        n_rd_cnt: 0
        m_rd_peak: 4
        m_rd_avg: 2
        m_rd_cnt: 4
        d_wr_s_peak: 24
        d_wr_s_avg: 2
        d_wr_s_cnt: 2398
        n_wr_s_peak: 24
        n_wr_s_avg: 1
        n_wr_s_cnt: 428
        m_wr_s_peak: 20
        m_wr_s_avg: 1
        m_wr_s_cnt: 1325
        d_wr_as_peak: 16
        d_wr_as_avg: 3
        d_wr_as_cnt: 800
        n_wr_as_peak: 0
        n_wr_as_avg: 0
        n_wr_as_cnt: 0
        m_wr_as_peak: 0
        m_wr_as_avg: 0
        m_wr_as_cnt: 0
      }
    }
  }
}
packet {
  ftrace_events {
    cpu: 4
    event {
      timestamp: 1629349027
      pid: 9662
      f2fs_iostat_latency {
        dev: 0xfe20
        d_rd_peak: 4
        d_rd_avg: 0
        d_rd_cnt: 143
        n_rd_peak: 3
        n_rd_avg: 1
        n_rd_cnt: 121
        m_rd_peak: 4
        m_rd_avg: 2
        m_rd_cnt: 4
        d_wr_s_peak: 20
        d_wr_s_avg: 2
        d_wr_s_cnt: 2705
        n_wr_s_peak: 20
        n_wr_s_avg: 0
        n_wr_s_cnt: 411
        m_wr_s_peak: 20
        m_wr_s_avg: 1
        m_wr_s_cnt: 1471
        d_wr_as_peak: 16
        d_wr_as_avg: 2
        d_wr_as_cnt: 929
        n_wr_as_peak: 5
        n_wr_as_avg: 1
        n_wr_as_cnt: 23
        m_wr_as_peak: 0
        m_wr_as_avg: 0
        m_wr_as_cnt: 0
      }
    }
  }
}
packet {
  ftrace_events {
    cpu: 3
    event {
      timestamp: 1632350255
      pid: 2718
      f2fs_iostat_latency {
        dev: 0xfe2e
        d_rd_peak: 4
        d_rd_avg: 0
        d_rd_cnt: 108
        n_rd_peak: 0
        n_rd_avg: 0
        n_rd_cnt: 0
        m_rd_peak: 4
        m_rd_avg: 0
        m_rd_cnt: 5
        d_wr_s_peak: 36
        d_wr_s_avg: 2
        d_wr_s_cnt: 3034
        n_wr_s_peak: 32
        n_wr_s_avg: 1
        n_wr_s_cnt: 390
        m_wr_s_peak: 20
        m_wr_s_avg: 0
        m_wr_s_cnt: 1602
        d_wr_as_peak: 12
        d_wr_as_avg: 2
        d_wr_as_cnt: 531
        n_wr_as_peak: 0
        n_wr_as_avg: 0
        n_wr_as_cnt: 0
        m_wr_as_peak: 5
        m_wr_as_avg: 1
        m_wr_as_cnt: 34
      }
    }
  }
}
packet {
  ftrace_events {
    cpu: 2
    event {
      timestamp: 1635348134
      pid: 9634
      f2fs_iostat_latency {
        dev: 0xfe2e
        d_rd_peak: 4
        d_rd_avg: 0
        d_rd_cnt: 127
        n_rd_peak: 0
        n_rd_avg: 0
        n_rd_cnt: 0
        m_rd_peak: 4
        m_rd_avg: 2
        m_rd_cnt: 4
        d_wr_s_peak: 28
        d_wr_s_avg: 1
        d_wr_s_cnt: 3019
        n_wr_s_peak: 16
        n_wr_s_avg: 0
        n_wr_s_cnt: 407
        m_wr_s_peak: 8
        m_wr_s_avg: 1
        m_wr_s_cnt: 1739
        d_wr_as_peak: 36
        d_wr_as_avg: 2
        d_wr_as_cnt: 790
        n_wr_as_peak: 0
        n_wr_as_avg: 0
        n_wr_as_cnt: 0
        m_wr_as_peak: 0
        m_wr_as_avg: 0
        m_wr_as_cnt: 0
      }
    }
  }
}
packet {
  ftrace_events {
    cpu: 2
    event {
      timestamp: 1638349595
      pid: 9657
      f2fs_iostat_latency {
        dev: 0xfe20
        d_rd_peak: 4
        d_rd_avg: 0
        d_rd_cnt: 135
        n_rd_peak: 0
        n_rd_avg: 0
        n_rd_cnt: 0
        m_rd_peak: 4
        m_rd_avg: 1
        m_rd_cnt: 5
        d_wr_s_peak: 12
        d_wr_s_avg: 2
        d_wr_s_cnt: 3092
        n_wr_s_peak: 36
        n_wr_s_avg: 1
        n_wr_s_cnt: 392
        m_wr_s_peak: 40
        m_wr_s_avg: 1
        m_wr_s_cnt: 1856
        d_wr_as_peak: 12
        d_wr_as_avg: 3
        d_wr_as_cnt: 631
        n_wr_as_peak: 0
        n_wr_as_avg: 0
        n_wr_as_cnt: 0
        m_wr_as_peak: 0
        m_wr_as_avg: 0
        m_wr_as_cnt: 0
      }
    }
  }
}
