// Autogenerated by:
// ../../tools/ftrace_proto_gen/ftrace_descriptor_gen.cc
// Do not edit.

#include "src/trace_processor/ftrace_descriptors.h"

namespace perfetto {
namespace trace_processor {
namespace {

std::array<MessageDescriptor, 331> descriptors{{
    {},
    {},
    {},
    {
        "print",
        {
            {},
            {"ip", ProtoSchemaType::kUint64},
            {"buf", ProtoSchemaType::kString},
        },
    },
    {
        "sched_switch",
        {
            {},
            {"prev_comm", ProtoSchemaType::kString},
            {"prev_pid", ProtoSchemaType::kInt32},
            {"prev_prio", ProtoSchemaType::kInt32},
            {"prev_state", ProtoSchemaType::kInt64},
            {"next_comm", ProtoSchemaType::kString},
            {"next_pid", ProtoSchemaType::kInt32},
            {"next_prio", ProtoSchemaType::kInt32},
        },
    },
    {},
    {},
    {},
    {},
    {},
    {},
    {
        "cpu_frequency",
        {
            {},
            {"state", ProtoSchemaType::kUint32},
            {"cpu_id", ProtoSchemaType::kUint32},
        },
    },
    {
        "cpu_frequency_limits",
        {
            {},
            {"min_freq", ProtoSchemaType::kUint32},
            {"max_freq", ProtoSchemaType::kUint32},
            {"cpu_id", ProtoSchemaType::kUint32},
        },
    },
    {
        "cpu_idle",
        {
            {},
            {"state", ProtoSchemaType::kUint32},
            {"cpu_id", ProtoSchemaType::kUint32},
        },
    },
    {
        "clock_enable",
        {
            {},
            {"name", ProtoSchemaType::kString},
            {"state", ProtoSchemaType::kUint64},
            {"cpu_id", ProtoSchemaType::kUint64},
        },
    },
    {
        "clock_disable",
        {
            {},
            {"name", ProtoSchemaType::kString},
            {"state", ProtoSchemaType::kUint64},
            {"cpu_id", ProtoSchemaType::kUint64},
        },
    },
    {
        "clock_set_rate",
        {
            {},
            {"name", ProtoSchemaType::kString},
            {"state", ProtoSchemaType::kUint64},
            {"cpu_id", ProtoSchemaType::kUint64},
        },
    },
    {
        "sched_wakeup",
        {
            {},
            {"comm", ProtoSchemaType::kString},
            {"pid", ProtoSchemaType::kInt32},
            {"prio", ProtoSchemaType::kInt32},
            {"success", ProtoSchemaType::kInt32},
            {"target_cpu", ProtoSchemaType::kInt32},
        },
    },
    {
        "sched_blocked_reason",
        {
            {},
            {"pid", ProtoSchemaType::kInt32},
            {"caller", ProtoSchemaType::kUint64},
            {"io_wait", ProtoSchemaType::kUint32},
        },
    },
    {
        "sched_cpu_hotplug",
        {
            {},
            {"affected_cpu", ProtoSchemaType::kInt32},
            {"error", ProtoSchemaType::kInt32},
            {"status", ProtoSchemaType::kInt32},
        },
    },
    {
        "sched_waking",
        {
            {},
            {"comm", ProtoSchemaType::kString},
            {"pid", ProtoSchemaType::kInt32},
            {"prio", ProtoSchemaType::kInt32},
            {"success", ProtoSchemaType::kInt32},
            {"target_cpu", ProtoSchemaType::kInt32},
        },
    },
    {
        "ipi_entry",
        {
            {},
            {"reason", ProtoSchemaType::kString},
        },
    },
    {
        "ipi_exit",
        {
            {},
            {"reason", ProtoSchemaType::kString},
        },
    },
    {
        "ipi_raise",
        {
            {},
            {"target_cpus", ProtoSchemaType::kUint32},
            {"reason", ProtoSchemaType::kString},
        },
    },
    {
        "softirq_entry",
        {
            {},
            {"vec", ProtoSchemaType::kUint32},
        },
    },
    {
        "softirq_exit",
        {
            {},
            {"vec", ProtoSchemaType::kUint32},
        },
    },
    {
        "softirq_raise",
        {
            {},
            {"vec", ProtoSchemaType::kUint32},
        },
    },
    {
        "i2c_read",
        {
            {},
            {"adapter_nr", ProtoSchemaType::kInt32},
            {"msg_nr", ProtoSchemaType::kUint32},
            {"addr", ProtoSchemaType::kUint32},
            {"flags", ProtoSchemaType::kUint32},
            {"len", ProtoSchemaType::kUint32},
        },
    },
    {
        "i2c_write",
        {
            {},
            {"adapter_nr", ProtoSchemaType::kInt32},
            {"msg_nr", ProtoSchemaType::kUint32},
            {"addr", ProtoSchemaType::kUint32},
            {"flags", ProtoSchemaType::kUint32},
            {"len", ProtoSchemaType::kUint32},
            {"buf", ProtoSchemaType::kUint32},
        },
    },
    {
        "i2c_result",
        {
            {},
            {"adapter_nr", ProtoSchemaType::kInt32},
            {"nr_msgs", ProtoSchemaType::kUint32},
            {"ret", ProtoSchemaType::kInt32},
        },
    },
    {
        "i2c_reply",
        {
            {},
            {"adapter_nr", ProtoSchemaType::kInt32},
            {"msg_nr", ProtoSchemaType::kUint32},
            {"addr", ProtoSchemaType::kUint32},
            {"flags", ProtoSchemaType::kUint32},
            {"len", ProtoSchemaType::kUint32},
            {"buf", ProtoSchemaType::kUint32},
        },
    },
    {
        "smbus_read",
        {
            {},
            {"adapter_nr", ProtoSchemaType::kInt32},
            {"flags", ProtoSchemaType::kUint32},
            {"addr", ProtoSchemaType::kUint32},
            {"command", ProtoSchemaType::kUint32},
            {"protocol", ProtoSchemaType::kUint32},
        },
    },
    {
        "smbus_write",
        {
            {},
            {"adapter_nr", ProtoSchemaType::kInt32},
            {"addr", ProtoSchemaType::kUint32},
            {"flags", ProtoSchemaType::kUint32},
            {"command", ProtoSchemaType::kUint32},
            {"len", ProtoSchemaType::kUint32},
            {"protocol", ProtoSchemaType::kUint32},
        },
    },
    {
        "smbus_result",
        {
            {},
            {"adapter_nr", ProtoSchemaType::kInt32},
            {"addr", ProtoSchemaType::kUint32},
            {"flags", ProtoSchemaType::kUint32},
            {"read_write", ProtoSchemaType::kUint32},
            {"command", ProtoSchemaType::kUint32},
            {"res", ProtoSchemaType::kInt32},
            {"protocol", ProtoSchemaType::kUint32},
        },
    },
    {
        "smbus_reply",
        {
            {},
            {"adapter_nr", ProtoSchemaType::kInt32},
            {"addr", ProtoSchemaType::kUint32},
            {"flags", ProtoSchemaType::kUint32},
            {"command", ProtoSchemaType::kUint32},
            {"len", ProtoSchemaType::kUint32},
            {"protocol", ProtoSchemaType::kUint32},
        },
    },
    {
        "lowmemory_kill",
        {
            {},
            {"comm", ProtoSchemaType::kString},
            {"pid", ProtoSchemaType::kInt32},
            {"pagecache_size", ProtoSchemaType::kInt64},
            {"pagecache_limit", ProtoSchemaType::kInt64},
            {"free", ProtoSchemaType::kInt64},
        },
    },
    {
        "irq_handler_entry",
        {
            {},
            {"irq", ProtoSchemaType::kInt32},
            {"name", ProtoSchemaType::kString},
            {"handler", ProtoSchemaType::kUint32},
        },
    },
    {
        "irq_handler_exit",
        {
            {},
            {"irq", ProtoSchemaType::kInt32},
            {"ret", ProtoSchemaType::kInt32},
        },
    },
    {
        "sync_pt",
        {
            {},
            {"timeline", ProtoSchemaType::kString},
            {"value", ProtoSchemaType::kString},
        },
    },
    {
        "sync_timeline",
        {
            {},
            {"name", ProtoSchemaType::kString},
            {"value", ProtoSchemaType::kString},
        },
    },
    {
        "sync_wait",
        {
            {},
            {"name", ProtoSchemaType::kString},
            {"status", ProtoSchemaType::kInt32},
            {"begin", ProtoSchemaType::kUint32},
        },
    },
    {
        "ext4_da_write_begin",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"pos", ProtoSchemaType::kInt64},
            {"len", ProtoSchemaType::kUint32},
            {"flags", ProtoSchemaType::kUint32},
        },
    },
    {
        "ext4_da_write_end",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"pos", ProtoSchemaType::kInt64},
            {"len", ProtoSchemaType::kUint32},
            {"copied", ProtoSchemaType::kUint32},
        },
    },
    {
        "ext4_sync_file_enter",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"parent", ProtoSchemaType::kUint64},
            {"datasync", ProtoSchemaType::kInt32},
        },
    },
    {
        "ext4_sync_file_exit",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"ret", ProtoSchemaType::kInt32},
        },
    },
    {
        "block_rq_issue",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"sector", ProtoSchemaType::kUint64},
            {"nr_sector", ProtoSchemaType::kUint32},
            {"bytes", ProtoSchemaType::kUint32},
            {"rwbs", ProtoSchemaType::kString},
            {"comm", ProtoSchemaType::kString},
            {"cmd", ProtoSchemaType::kString},
        },
    },
    {
        "mm_vmscan_direct_reclaim_begin",
        {
            {},
            {"order", ProtoSchemaType::kInt32},
            {"may_writepage", ProtoSchemaType::kInt32},
            {"gfp_flags", ProtoSchemaType::kUint32},
        },
    },
    {
        "mm_vmscan_direct_reclaim_end",
        {
            {},
            {"nr_reclaimed", ProtoSchemaType::kUint64},
        },
    },
    {
        "mm_vmscan_kswapd_wake",
        {
            {},
            {"nid", ProtoSchemaType::kInt32},
            {"order", ProtoSchemaType::kInt32},
        },
    },
    {
        "mm_vmscan_kswapd_sleep",
        {
            {},
            {"nid", ProtoSchemaType::kInt32},
        },
    },
    {
        "binder_transaction",
        {
            {},
            {"debug_id", ProtoSchemaType::kInt32},
            {"target_node", ProtoSchemaType::kInt32},
            {"to_proc", ProtoSchemaType::kInt32},
            {"to_thread", ProtoSchemaType::kInt32},
            {"reply", ProtoSchemaType::kInt32},
            {"code", ProtoSchemaType::kUint32},
            {"flags", ProtoSchemaType::kUint32},
        },
    },
    {
        "binder_transaction_received",
        {
            {},
            {"debug_id", ProtoSchemaType::kInt32},
        },
    },
    {
        "binder_set_priority",
        {
            {},
            {"proc", ProtoSchemaType::kInt32},
            {"thread", ProtoSchemaType::kInt32},
            {"old_prio", ProtoSchemaType::kUint32},
            {"new_prio", ProtoSchemaType::kUint32},
            {"desired_prio", ProtoSchemaType::kUint32},
        },
    },
    {
        "binder_lock",
        {
            {},
            {"tag", ProtoSchemaType::kString},
        },
    },
    {
        "binder_locked",
        {
            {},
            {"tag", ProtoSchemaType::kString},
        },
    },
    {
        "binder_unlock",
        {
            {},
            {"tag", ProtoSchemaType::kString},
        },
    },
    {
        "workqueue_activate_work",
        {
            {},
            {"work", ProtoSchemaType::kUint64},
        },
    },
    {
        "workqueue_execute_end",
        {
            {},
            {"work", ProtoSchemaType::kUint64},
        },
    },
    {
        "workqueue_execute_start",
        {
            {},
            {"work", ProtoSchemaType::kUint64},
            {"function", ProtoSchemaType::kUint64},
        },
    },
    {
        "workqueue_queue_work",
        {
            {},
            {"work", ProtoSchemaType::kUint64},
            {"function", ProtoSchemaType::kUint64},
            {"workqueue", ProtoSchemaType::kUint64},
            {"req_cpu", ProtoSchemaType::kUint32},
            {"cpu", ProtoSchemaType::kUint32},
        },
    },
    {
        "regulator_disable",
        {
            {},
            {"name", ProtoSchemaType::kString},
        },
    },
    {
        "regulator_disable_complete",
        {
            {},
            {"name", ProtoSchemaType::kString},
        },
    },
    {
        "regulator_enable",
        {
            {},
            {"name", ProtoSchemaType::kString},
        },
    },
    {
        "regulator_enable_complete",
        {
            {},
            {"name", ProtoSchemaType::kString},
        },
    },
    {
        "regulator_enable_delay",
        {
            {},
            {"name", ProtoSchemaType::kString},
        },
    },
    {
        "regulator_set_voltage",
        {
            {},
            {"name", ProtoSchemaType::kString},
            {"min", ProtoSchemaType::kInt32},
            {"max", ProtoSchemaType::kInt32},
        },
    },
    {
        "regulator_set_voltage_complete",
        {
            {},
            {"name", ProtoSchemaType::kString},
            {"val", ProtoSchemaType::kUint32},
        },
    },
    {
        "cgroup_attach_task",
        {
            {},
            {"dst_root", ProtoSchemaType::kInt32},
            {"dst_id", ProtoSchemaType::kInt32},
            {"pid", ProtoSchemaType::kInt32},
            {"comm", ProtoSchemaType::kString},
            {"cname", ProtoSchemaType::kString},
        },
    },
    {
        "cgroup_mkdir",
        {
            {},
            {"root", ProtoSchemaType::kInt32},
            {"id", ProtoSchemaType::kInt32},
            {"cname", ProtoSchemaType::kString},
        },
    },
    {
        "cgroup_remount",
        {
            {},
            {"root", ProtoSchemaType::kInt32},
            {"ss_mask", ProtoSchemaType::kUint32},
            {"name", ProtoSchemaType::kString},
        },
    },
    {
        "cgroup_rmdir",
        {
            {},
            {"root", ProtoSchemaType::kInt32},
            {"id", ProtoSchemaType::kInt32},
            {"cname", ProtoSchemaType::kString},
        },
    },
    {
        "cgroup_transfer_tasks",
        {
            {},
            {"dst_root", ProtoSchemaType::kInt32},
            {"dst_id", ProtoSchemaType::kInt32},
            {"pid", ProtoSchemaType::kInt32},
            {"comm", ProtoSchemaType::kString},
            {"cname", ProtoSchemaType::kString},
        },
    },
    {
        "cgroup_destroy_root",
        {
            {},
            {"root", ProtoSchemaType::kInt32},
            {"ss_mask", ProtoSchemaType::kUint32},
            {"name", ProtoSchemaType::kString},
        },
    },
    {
        "cgroup_release",
        {
            {},
            {"root", ProtoSchemaType::kInt32},
            {"id", ProtoSchemaType::kInt32},
            {"cname", ProtoSchemaType::kString},
        },
    },
    {
        "cgroup_rename",
        {
            {},
            {"root", ProtoSchemaType::kInt32},
            {"id", ProtoSchemaType::kInt32},
            {"cname", ProtoSchemaType::kString},
        },
    },
    {
        "cgroup_setup_root",
        {
            {},
            {"root", ProtoSchemaType::kInt32},
            {"ss_mask", ProtoSchemaType::kUint32},
            {"name", ProtoSchemaType::kString},
        },
    },
    {
        "mdp_cmd_kickoff",
        {
            {},
            {"ctl_num", ProtoSchemaType::kUint32},
            {"kickoff_cnt", ProtoSchemaType::kInt32},
        },
    },
    {
        "mdp_commit",
        {
            {},
            {"num", ProtoSchemaType::kUint32},
            {"play_cnt", ProtoSchemaType::kUint32},
            {"clk_rate", ProtoSchemaType::kUint32},
            {"bandwidth", ProtoSchemaType::kUint64},
        },
    },
    {
        "mdp_perf_set_ot",
        {
            {},
            {"pnum", ProtoSchemaType::kUint32},
            {"xin_id", ProtoSchemaType::kUint32},
            {"rd_lim", ProtoSchemaType::kUint32},
            {"is_vbif_rt", ProtoSchemaType::kUint32},
        },
    },
    {
        "mdp_sspp_change",
        {
            {},
            {"num", ProtoSchemaType::kUint32},
            {"play_cnt", ProtoSchemaType::kUint32},
            {"mixer", ProtoSchemaType::kUint32},
            {"stage", ProtoSchemaType::kUint32},
            {"flags", ProtoSchemaType::kUint32},
            {"format", ProtoSchemaType::kUint32},
            {"img_w", ProtoSchemaType::kUint32},
            {"img_h", ProtoSchemaType::kUint32},
            {"src_x", ProtoSchemaType::kUint32},
            {"src_y", ProtoSchemaType::kUint32},
            {"src_w", ProtoSchemaType::kUint32},
            {"src_h", ProtoSchemaType::kUint32},
            {"dst_x", ProtoSchemaType::kUint32},
            {"dst_y", ProtoSchemaType::kUint32},
            {"dst_w", ProtoSchemaType::kUint32},
            {"dst_h", ProtoSchemaType::kUint32},
        },
    },
    {
        "tracing_mark_write",
        {
            {},
            {"pid", ProtoSchemaType::kInt32},
            {"trace_name", ProtoSchemaType::kString},
            {"trace_begin", ProtoSchemaType::kUint32},
        },
    },
    {
        "mdp_cmd_pingpong_done",
        {
            {},
            {"ctl_num", ProtoSchemaType::kUint32},
            {"intf_num", ProtoSchemaType::kUint32},
            {"pp_num", ProtoSchemaType::kUint32},
            {"koff_cnt", ProtoSchemaType::kInt32},
        },
    },
    {
        "mdp_compare_bw",
        {
            {},
            {"new_ab", ProtoSchemaType::kUint64},
            {"new_ib", ProtoSchemaType::kUint64},
            {"new_wb", ProtoSchemaType::kUint64},
            {"old_ab", ProtoSchemaType::kUint64},
            {"old_ib", ProtoSchemaType::kUint64},
            {"old_wb", ProtoSchemaType::kUint64},
            {"params_changed", ProtoSchemaType::kUint32},
            {"update_bw", ProtoSchemaType::kUint32},
        },
    },
    {
        "mdp_perf_set_panic_luts",
        {
            {},
            {"pnum", ProtoSchemaType::kUint32},
            {"fmt", ProtoSchemaType::kUint32},
            {"mode", ProtoSchemaType::kUint32},
            {"panic_lut", ProtoSchemaType::kUint32},
            {"robust_lut", ProtoSchemaType::kUint32},
        },
    },
    {
        "mdp_sspp_set",
        {
            {},
            {"num", ProtoSchemaType::kUint32},
            {"play_cnt", ProtoSchemaType::kUint32},
            {"mixer", ProtoSchemaType::kUint32},
            {"stage", ProtoSchemaType::kUint32},
            {"flags", ProtoSchemaType::kUint32},
            {"format", ProtoSchemaType::kUint32},
            {"img_w", ProtoSchemaType::kUint32},
            {"img_h", ProtoSchemaType::kUint32},
            {"src_x", ProtoSchemaType::kUint32},
            {"src_y", ProtoSchemaType::kUint32},
            {"src_w", ProtoSchemaType::kUint32},
            {"src_h", ProtoSchemaType::kUint32},
            {"dst_x", ProtoSchemaType::kUint32},
            {"dst_y", ProtoSchemaType::kUint32},
            {"dst_w", ProtoSchemaType::kUint32},
            {"dst_h", ProtoSchemaType::kUint32},
        },
    },
    {
        "mdp_cmd_readptr_done",
        {
            {},
            {"ctl_num", ProtoSchemaType::kUint32},
            {"koff_cnt", ProtoSchemaType::kInt32},
        },
    },
    {
        "mdp_misr_crc",
        {
            {},
            {"block_id", ProtoSchemaType::kUint32},
            {"vsync_cnt", ProtoSchemaType::kUint32},
            {"crc", ProtoSchemaType::kUint32},
        },
    },
    {
        "mdp_perf_set_qos_luts",
        {
            {},
            {"pnum", ProtoSchemaType::kUint32},
            {"fmt", ProtoSchemaType::kUint32},
            {"intf", ProtoSchemaType::kUint32},
            {"rot", ProtoSchemaType::kUint32},
            {"fl", ProtoSchemaType::kUint32},
            {"lut", ProtoSchemaType::kUint32},
            {"linear", ProtoSchemaType::kUint32},
        },
    },
    {
        "mdp_trace_counter",
        {
            {},
            {"pid", ProtoSchemaType::kInt32},
            {"counter_name", ProtoSchemaType::kString},
            {"value", ProtoSchemaType::kInt32},
        },
    },
    {
        "mdp_cmd_release_bw",
        {
            {},
            {"ctl_num", ProtoSchemaType::kUint32},
        },
    },
    {
        "mdp_mixer_update",
        {
            {},
            {"mixer_num", ProtoSchemaType::kUint32},
        },
    },
    {
        "mdp_perf_set_wm_levels",
        {
            {},
            {"pnum", ProtoSchemaType::kUint32},
            {"use_space", ProtoSchemaType::kUint32},
            {"priority_bytes", ProtoSchemaType::kUint32},
            {"wm0", ProtoSchemaType::kUint32},
            {"wm1", ProtoSchemaType::kUint32},
            {"wm2", ProtoSchemaType::kUint32},
            {"mb_cnt", ProtoSchemaType::kUint32},
            {"mb_size", ProtoSchemaType::kUint32},
        },
    },
    {
        "mdp_video_underrun_done",
        {
            {},
            {"ctl_num", ProtoSchemaType::kUint32},
            {"underrun_cnt", ProtoSchemaType::kUint32},
        },
    },
    {
        "mdp_cmd_wait_pingpong",
        {
            {},
            {"ctl_num", ProtoSchemaType::kUint32},
            {"kickoff_cnt", ProtoSchemaType::kInt32},
        },
    },
    {
        "mdp_perf_prefill_calc",
        {
            {},
            {"pnum", ProtoSchemaType::kUint32},
            {"latency_buf", ProtoSchemaType::kUint32},
            {"ot", ProtoSchemaType::kUint32},
            {"y_buf", ProtoSchemaType::kUint32},
            {"y_scaler", ProtoSchemaType::kUint32},
            {"pp_lines", ProtoSchemaType::kUint32},
            {"pp_bytes", ProtoSchemaType::kUint32},
            {"post_sc", ProtoSchemaType::kUint32},
            {"fbc_bytes", ProtoSchemaType::kUint32},
            {"prefill_bytes", ProtoSchemaType::kUint32},
        },
    },
    {
        "mdp_perf_update_bus",
        {
            {},
            {"client", ProtoSchemaType::kInt32},
            {"ab_quota", ProtoSchemaType::kUint64},
            {"ib_quota", ProtoSchemaType::kUint64},
        },
    },
    {
        "rotator_bw_ao_as_context",
        {
            {},
            {"state", ProtoSchemaType::kUint32},
        },
    },
    {
        "mm_filemap_add_to_page_cache",
        {
            {},
            {"pfn", ProtoSchemaType::kUint64},
            {"i_ino", ProtoSchemaType::kUint64},
            {"index", ProtoSchemaType::kUint64},
            {"s_dev", ProtoSchemaType::kUint64},
            {"page", ProtoSchemaType::kUint64},
        },
    },
    {
        "mm_filemap_delete_from_page_cache",
        {
            {},
            {"pfn", ProtoSchemaType::kUint64},
            {"i_ino", ProtoSchemaType::kUint64},
            {"index", ProtoSchemaType::kUint64},
            {"s_dev", ProtoSchemaType::kUint64},
            {"page", ProtoSchemaType::kUint64},
        },
    },
    {
        "mm_compaction_begin",
        {
            {},
            {"zone_start", ProtoSchemaType::kUint64},
            {"migrate_pfn", ProtoSchemaType::kUint64},
            {"free_pfn", ProtoSchemaType::kUint64},
            {"zone_end", ProtoSchemaType::kUint64},
            {"sync", ProtoSchemaType::kUint32},
        },
    },
    {
        "mm_compaction_defer_compaction",
        {
            {},
            {"nid", ProtoSchemaType::kInt32},
            {"idx", ProtoSchemaType::kUint32},
            {"order", ProtoSchemaType::kInt32},
            {"considered", ProtoSchemaType::kUint32},
            {"defer_shift", ProtoSchemaType::kUint32},
            {"order_failed", ProtoSchemaType::kInt32},
        },
    },
    {
        "mm_compaction_deferred",
        {
            {},
            {"nid", ProtoSchemaType::kInt32},
            {"idx", ProtoSchemaType::kUint32},
            {"order", ProtoSchemaType::kInt32},
            {"considered", ProtoSchemaType::kUint32},
            {"defer_shift", ProtoSchemaType::kUint32},
            {"order_failed", ProtoSchemaType::kInt32},
        },
    },
    {
        "mm_compaction_defer_reset",
        {
            {},
            {"nid", ProtoSchemaType::kInt32},
            {"idx", ProtoSchemaType::kUint32},
            {"order", ProtoSchemaType::kInt32},
            {"considered", ProtoSchemaType::kUint32},
            {"defer_shift", ProtoSchemaType::kUint32},
            {"order_failed", ProtoSchemaType::kInt32},
        },
    },
    {
        "mm_compaction_end",
        {
            {},
            {"zone_start", ProtoSchemaType::kUint64},
            {"migrate_pfn", ProtoSchemaType::kUint64},
            {"free_pfn", ProtoSchemaType::kUint64},
            {"zone_end", ProtoSchemaType::kUint64},
            {"sync", ProtoSchemaType::kUint32},
            {"status", ProtoSchemaType::kInt32},
        },
    },
    {
        "mm_compaction_finished",
        {
            {},
            {"nid", ProtoSchemaType::kInt32},
            {"idx", ProtoSchemaType::kUint32},
            {"order", ProtoSchemaType::kInt32},
            {"ret", ProtoSchemaType::kInt32},
        },
    },
    {
        "mm_compaction_isolate_freepages",
        {
            {},
            {"start_pfn", ProtoSchemaType::kUint64},
            {"end_pfn", ProtoSchemaType::kUint64},
            {"nr_scanned", ProtoSchemaType::kUint64},
            {"nr_taken", ProtoSchemaType::kUint64},
        },
    },
    {
        "mm_compaction_isolate_migratepages",
        {
            {},
            {"start_pfn", ProtoSchemaType::kUint64},
            {"end_pfn", ProtoSchemaType::kUint64},
            {"nr_scanned", ProtoSchemaType::kUint64},
            {"nr_taken", ProtoSchemaType::kUint64},
        },
    },
    {
        "mm_compaction_kcompactd_sleep",
        {
            {},
            {"nid", ProtoSchemaType::kInt32},
        },
    },
    {
        "mm_compaction_kcompactd_wake",
        {
            {},
            {"nid", ProtoSchemaType::kInt32},
            {"order", ProtoSchemaType::kInt32},
            {"classzone_idx", ProtoSchemaType::kUint32},
        },
    },
    {
        "mm_compaction_migratepages",
        {
            {},
            {"nr_migrated", ProtoSchemaType::kUint64},
            {"nr_failed", ProtoSchemaType::kUint64},
        },
    },
    {
        "mm_compaction_suitable",
        {
            {},
            {"nid", ProtoSchemaType::kInt32},
            {"idx", ProtoSchemaType::kUint32},
            {"order", ProtoSchemaType::kInt32},
            {"ret", ProtoSchemaType::kInt32},
        },
    },
    {
        "mm_compaction_try_to_compact_pages",
        {
            {},
            {"order", ProtoSchemaType::kInt32},
            {"gfp_mask", ProtoSchemaType::kUint32},
            {"mode", ProtoSchemaType::kUint32},
        },
    },
    {
        "mm_compaction_wakeup_kcompactd",
        {
            {},
            {"nid", ProtoSchemaType::kInt32},
            {"order", ProtoSchemaType::kInt32},
            {"classzone_idx", ProtoSchemaType::kUint32},
        },
    },
    {
        "suspend_resume",
        {
            {},
            {"action", ProtoSchemaType::kString},
            {"val", ProtoSchemaType::kInt32},
            {"start", ProtoSchemaType::kUint32},
        },
    },
    {
        "sched_wakeup_new",
        {
            {},
            {"comm", ProtoSchemaType::kString},
            {"pid", ProtoSchemaType::kInt32},
            {"prio", ProtoSchemaType::kInt32},
            {"success", ProtoSchemaType::kInt32},
            {"target_cpu", ProtoSchemaType::kInt32},
        },
    },
    {
        "block_bio_backmerge",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"sector", ProtoSchemaType::kUint64},
            {"nr_sector", ProtoSchemaType::kUint32},
            {"rwbs", ProtoSchemaType::kString},
            {"comm", ProtoSchemaType::kString},
        },
    },
    {
        "block_bio_bounce",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"sector", ProtoSchemaType::kUint64},
            {"nr_sector", ProtoSchemaType::kUint32},
            {"rwbs", ProtoSchemaType::kString},
            {"comm", ProtoSchemaType::kString},
        },
    },
    {
        "block_bio_complete",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"sector", ProtoSchemaType::kUint64},
            {"nr_sector", ProtoSchemaType::kUint32},
            {"error", ProtoSchemaType::kInt32},
            {"rwbs", ProtoSchemaType::kString},
        },
    },
    {
        "block_bio_frontmerge",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"sector", ProtoSchemaType::kUint64},
            {"nr_sector", ProtoSchemaType::kUint32},
            {"rwbs", ProtoSchemaType::kString},
            {"comm", ProtoSchemaType::kString},
        },
    },
    {
        "block_bio_queue",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"sector", ProtoSchemaType::kUint64},
            {"nr_sector", ProtoSchemaType::kUint32},
            {"rwbs", ProtoSchemaType::kString},
            {"comm", ProtoSchemaType::kString},
        },
    },
    {
        "block_bio_remap",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"sector", ProtoSchemaType::kUint64},
            {"nr_sector", ProtoSchemaType::kUint32},
            {"old_dev", ProtoSchemaType::kUint64},
            {"old_sector", ProtoSchemaType::kUint64},
            {"rwbs", ProtoSchemaType::kString},
        },
    },
    {
        "block_dirty_buffer",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"sector", ProtoSchemaType::kUint64},
            {"size", ProtoSchemaType::kUint64},
        },
    },
    {
        "block_getrq",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"sector", ProtoSchemaType::kUint64},
            {"nr_sector", ProtoSchemaType::kUint32},
            {"rwbs", ProtoSchemaType::kString},
            {"comm", ProtoSchemaType::kString},
        },
    },
    {
        "block_plug",
        {
            {},
            {"comm", ProtoSchemaType::kString},
        },
    },
    {
        "block_rq_abort",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"sector", ProtoSchemaType::kUint64},
            {"nr_sector", ProtoSchemaType::kUint32},
            {"errors", ProtoSchemaType::kInt32},
            {"rwbs", ProtoSchemaType::kString},
            {"cmd", ProtoSchemaType::kString},
        },
    },
    {
        "block_rq_complete",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"sector", ProtoSchemaType::kUint64},
            {"nr_sector", ProtoSchemaType::kUint32},
            {"errors", ProtoSchemaType::kInt32},
            {"rwbs", ProtoSchemaType::kString},
            {"cmd", ProtoSchemaType::kString},
        },
    },
    {
        "block_rq_insert",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"sector", ProtoSchemaType::kUint64},
            {"nr_sector", ProtoSchemaType::kUint32},
            {"bytes", ProtoSchemaType::kUint32},
            {"rwbs", ProtoSchemaType::kString},
            {"comm", ProtoSchemaType::kString},
            {"cmd", ProtoSchemaType::kString},
        },
    },
    {},
    {
        "block_rq_remap",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"sector", ProtoSchemaType::kUint64},
            {"nr_sector", ProtoSchemaType::kUint32},
            {"old_dev", ProtoSchemaType::kUint64},
            {"old_sector", ProtoSchemaType::kUint64},
            {"nr_bios", ProtoSchemaType::kUint32},
            {"rwbs", ProtoSchemaType::kString},
        },
    },
    {
        "block_rq_requeue",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"sector", ProtoSchemaType::kUint64},
            {"nr_sector", ProtoSchemaType::kUint32},
            {"errors", ProtoSchemaType::kInt32},
            {"rwbs", ProtoSchemaType::kString},
            {"cmd", ProtoSchemaType::kString},
        },
    },
    {
        "block_sleeprq",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"sector", ProtoSchemaType::kUint64},
            {"nr_sector", ProtoSchemaType::kUint32},
            {"rwbs", ProtoSchemaType::kString},
            {"comm", ProtoSchemaType::kString},
        },
    },
    {
        "block_split",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"sector", ProtoSchemaType::kUint64},
            {"new_sector", ProtoSchemaType::kUint64},
            {"rwbs", ProtoSchemaType::kString},
            {"comm", ProtoSchemaType::kString},
        },
    },
    {
        "block_touch_buffer",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"sector", ProtoSchemaType::kUint64},
            {"size", ProtoSchemaType::kUint64},
        },
    },
    {
        "block_unplug",
        {
            {},
            {"nr_rq", ProtoSchemaType::kInt32},
            {"comm", ProtoSchemaType::kString},
        },
    },
    {
        "ext4_alloc_da_blocks",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"data_blocks", ProtoSchemaType::kUint32},
            {"meta_blocks", ProtoSchemaType::kUint32},
        },
    },
    {
        "ext4_allocate_blocks",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"block", ProtoSchemaType::kUint64},
            {"len", ProtoSchemaType::kUint32},
            {"logical", ProtoSchemaType::kUint32},
            {"lleft", ProtoSchemaType::kUint32},
            {"lright", ProtoSchemaType::kUint32},
            {"goal", ProtoSchemaType::kUint64},
            {"pleft", ProtoSchemaType::kUint64},
            {"pright", ProtoSchemaType::kUint64},
            {"flags", ProtoSchemaType::kUint32},
        },
    },
    {
        "ext4_allocate_inode",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"dir", ProtoSchemaType::kUint64},
            {"mode", ProtoSchemaType::kUint32},
        },
    },
    {
        "ext4_begin_ordered_truncate",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"new_size", ProtoSchemaType::kInt64},
        },
    },
    {
        "ext4_collapse_range",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"offset", ProtoSchemaType::kInt64},
            {"len", ProtoSchemaType::kInt64},
        },
    },
    {
        "ext4_da_release_space",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"i_blocks", ProtoSchemaType::kUint64},
            {"freed_blocks", ProtoSchemaType::kInt32},
            {"reserved_data_blocks", ProtoSchemaType::kInt32},
            {"reserved_meta_blocks", ProtoSchemaType::kInt32},
            {"allocated_meta_blocks", ProtoSchemaType::kInt32},
            {"mode", ProtoSchemaType::kUint32},
        },
    },
    {
        "ext4_da_reserve_space",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"i_blocks", ProtoSchemaType::kUint64},
            {"reserved_data_blocks", ProtoSchemaType::kInt32},
            {"reserved_meta_blocks", ProtoSchemaType::kInt32},
            {"mode", ProtoSchemaType::kUint32},
            {"md_needed", ProtoSchemaType::kInt32},
        },
    },
    {
        "ext4_da_update_reserve_space",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"i_blocks", ProtoSchemaType::kUint64},
            {"used_blocks", ProtoSchemaType::kInt32},
            {"reserved_data_blocks", ProtoSchemaType::kInt32},
            {"reserved_meta_blocks", ProtoSchemaType::kInt32},
            {"allocated_meta_blocks", ProtoSchemaType::kInt32},
            {"quota_claim", ProtoSchemaType::kInt32},
            {"mode", ProtoSchemaType::kUint32},
        },
    },
    {
        "ext4_da_write_pages",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"first_page", ProtoSchemaType::kUint64},
            {"nr_to_write", ProtoSchemaType::kInt64},
            {"sync_mode", ProtoSchemaType::kInt32},
            {"b_blocknr", ProtoSchemaType::kUint64},
            {"b_size", ProtoSchemaType::kUint32},
            {"b_state", ProtoSchemaType::kUint32},
            {"io_done", ProtoSchemaType::kInt32},
            {"pages_written", ProtoSchemaType::kInt32},
        },
    },
    {
        "ext4_da_write_pages_extent",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"lblk", ProtoSchemaType::kUint64},
            {"len", ProtoSchemaType::kUint32},
            {"flags", ProtoSchemaType::kUint32},
        },
    },
    {
        "ext4_direct_IO_enter",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"pos", ProtoSchemaType::kInt64},
            {"len", ProtoSchemaType::kUint64},
            {"rw", ProtoSchemaType::kInt32},
        },
    },
    {
        "ext4_direct_IO_exit",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"pos", ProtoSchemaType::kInt64},
            {"len", ProtoSchemaType::kUint64},
            {"rw", ProtoSchemaType::kInt32},
            {"ret", ProtoSchemaType::kInt32},
        },
    },
    {
        "ext4_discard_blocks",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"blk", ProtoSchemaType::kUint64},
            {"count", ProtoSchemaType::kUint64},
        },
    },
    {
        "ext4_discard_preallocations",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
        },
    },
    {
        "ext4_drop_inode",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"drop", ProtoSchemaType::kInt32},
        },
    },
    {
        "ext4_es_cache_extent",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"lblk", ProtoSchemaType::kUint32},
            {"len", ProtoSchemaType::kUint32},
            {"pblk", ProtoSchemaType::kUint64},
            {"status", ProtoSchemaType::kUint32},
        },
    },
    {
        "ext4_es_find_delayed_extent_range_enter",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"lblk", ProtoSchemaType::kUint32},
        },
    },
    {
        "ext4_es_find_delayed_extent_range_exit",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"lblk", ProtoSchemaType::kUint32},
            {"len", ProtoSchemaType::kUint32},
            {"pblk", ProtoSchemaType::kUint64},
            {"status", ProtoSchemaType::kUint64},
        },
    },
    {
        "ext4_es_insert_extent",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"lblk", ProtoSchemaType::kUint32},
            {"len", ProtoSchemaType::kUint32},
            {"pblk", ProtoSchemaType::kUint64},
            {"status", ProtoSchemaType::kUint64},
        },
    },
    {
        "ext4_es_lookup_extent_enter",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"lblk", ProtoSchemaType::kUint32},
        },
    },
    {
        "ext4_es_lookup_extent_exit",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"lblk", ProtoSchemaType::kUint32},
            {"len", ProtoSchemaType::kUint32},
            {"pblk", ProtoSchemaType::kUint64},
            {"status", ProtoSchemaType::kUint64},
            {"found", ProtoSchemaType::kInt32},
        },
    },
    {
        "ext4_es_remove_extent",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"lblk", ProtoSchemaType::kInt64},
            {"len", ProtoSchemaType::kInt64},
        },
    },
    {
        "ext4_es_shrink",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"nr_shrunk", ProtoSchemaType::kInt32},
            {"scan_time", ProtoSchemaType::kUint64},
            {"nr_skipped", ProtoSchemaType::kInt32},
            {"retried", ProtoSchemaType::kInt32},
        },
    },
    {
        "ext4_es_shrink_count",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"nr_to_scan", ProtoSchemaType::kInt32},
            {"cache_cnt", ProtoSchemaType::kInt32},
        },
    },
    {
        "ext4_es_shrink_scan_enter",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"nr_to_scan", ProtoSchemaType::kInt32},
            {"cache_cnt", ProtoSchemaType::kInt32},
        },
    },
    {
        "ext4_es_shrink_scan_exit",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"nr_shrunk", ProtoSchemaType::kInt32},
            {"cache_cnt", ProtoSchemaType::kInt32},
        },
    },
    {
        "ext4_evict_inode",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"nlink", ProtoSchemaType::kInt32},
        },
    },
    {
        "ext4_ext_convert_to_initialized_enter",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"m_lblk", ProtoSchemaType::kUint32},
            {"m_len", ProtoSchemaType::kUint32},
            {"u_lblk", ProtoSchemaType::kUint32},
            {"u_len", ProtoSchemaType::kUint32},
            {"u_pblk", ProtoSchemaType::kUint64},
        },
    },
    {
        "ext4_ext_convert_to_initialized_fastpath",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"m_lblk", ProtoSchemaType::kUint32},
            {"m_len", ProtoSchemaType::kUint32},
            {"u_lblk", ProtoSchemaType::kUint32},
            {"u_len", ProtoSchemaType::kUint32},
            {"u_pblk", ProtoSchemaType::kUint64},
            {"i_lblk", ProtoSchemaType::kUint32},
            {"i_len", ProtoSchemaType::kUint32},
            {"i_pblk", ProtoSchemaType::kUint64},
        },
    },
    {
        "ext4_ext_handle_unwritten_extents",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"flags", ProtoSchemaType::kInt32},
            {"lblk", ProtoSchemaType::kUint32},
            {"pblk", ProtoSchemaType::kUint64},
            {"len", ProtoSchemaType::kUint32},
            {"allocated", ProtoSchemaType::kUint32},
            {"newblk", ProtoSchemaType::kUint64},
        },
    },
    {
        "ext4_ext_in_cache",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"lblk", ProtoSchemaType::kUint32},
            {"ret", ProtoSchemaType::kInt32},
        },
    },
    {
        "ext4_ext_load_extent",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"pblk", ProtoSchemaType::kUint64},
            {"lblk", ProtoSchemaType::kUint32},
        },
    },
    {
        "ext4_ext_map_blocks_enter",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"lblk", ProtoSchemaType::kUint32},
            {"len", ProtoSchemaType::kUint32},
            {"flags", ProtoSchemaType::kUint32},
        },
    },
    {
        "ext4_ext_map_blocks_exit",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"flags", ProtoSchemaType::kUint32},
            {"pblk", ProtoSchemaType::kUint64},
            {"lblk", ProtoSchemaType::kUint32},
            {"len", ProtoSchemaType::kUint32},
            {"mflags", ProtoSchemaType::kUint32},
            {"ret", ProtoSchemaType::kInt32},
        },
    },
    {
        "ext4_ext_put_in_cache",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"lblk", ProtoSchemaType::kUint32},
            {"len", ProtoSchemaType::kUint32},
            {"start", ProtoSchemaType::kUint64},
        },
    },
    {
        "ext4_ext_remove_space",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"start", ProtoSchemaType::kUint32},
            {"end", ProtoSchemaType::kUint32},
            {"depth", ProtoSchemaType::kInt32},
        },
    },
    {
        "ext4_ext_remove_space_done",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"start", ProtoSchemaType::kUint32},
            {"end", ProtoSchemaType::kUint32},
            {"depth", ProtoSchemaType::kInt32},
            {"partial", ProtoSchemaType::kInt64},
            {"eh_entries", ProtoSchemaType::kUint32},
        },
    },
    {
        "ext4_ext_rm_idx",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"pblk", ProtoSchemaType::kUint64},
        },
    },
    {
        "ext4_ext_rm_leaf",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"partial", ProtoSchemaType::kInt64},
            {"start", ProtoSchemaType::kUint32},
            {"ee_lblk", ProtoSchemaType::kUint32},
            {"ee_pblk", ProtoSchemaType::kUint64},
            {"ee_len", ProtoSchemaType::kInt32},
        },
    },
    {
        "ext4_ext_show_extent",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"pblk", ProtoSchemaType::kUint64},
            {"lblk", ProtoSchemaType::kUint32},
            {"len", ProtoSchemaType::kUint32},
        },
    },
    {
        "ext4_fallocate_enter",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"offset", ProtoSchemaType::kInt64},
            {"len", ProtoSchemaType::kInt64},
            {"mode", ProtoSchemaType::kInt32},
            {"pos", ProtoSchemaType::kInt64},
        },
    },
    {
        "ext4_fallocate_exit",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"pos", ProtoSchemaType::kInt64},
            {"blocks", ProtoSchemaType::kUint32},
            {"ret", ProtoSchemaType::kInt32},
        },
    },
    {
        "ext4_find_delalloc_range",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"from", ProtoSchemaType::kUint32},
            {"to", ProtoSchemaType::kUint32},
            {"reverse", ProtoSchemaType::kInt32},
            {"found", ProtoSchemaType::kInt32},
            {"found_blk", ProtoSchemaType::kUint32},
        },
    },
    {
        "ext4_forget",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"block", ProtoSchemaType::kUint64},
            {"is_metadata", ProtoSchemaType::kInt32},
            {"mode", ProtoSchemaType::kUint32},
        },
    },
    {
        "ext4_free_blocks",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"block", ProtoSchemaType::kUint64},
            {"count", ProtoSchemaType::kUint64},
            {"flags", ProtoSchemaType::kInt32},
            {"mode", ProtoSchemaType::kUint32},
        },
    },
    {
        "ext4_free_inode",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"uid", ProtoSchemaType::kUint32},
            {"gid", ProtoSchemaType::kUint32},
            {"blocks", ProtoSchemaType::kUint64},
            {"mode", ProtoSchemaType::kUint32},
        },
    },
    {
        "ext4_get_implied_cluster_alloc_exit",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"flags", ProtoSchemaType::kUint32},
            {"lblk", ProtoSchemaType::kUint32},
            {"pblk", ProtoSchemaType::kUint64},
            {"len", ProtoSchemaType::kUint32},
            {"ret", ProtoSchemaType::kInt32},
        },
    },
    {
        "ext4_get_reserved_cluster_alloc",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"lblk", ProtoSchemaType::kUint32},
            {"len", ProtoSchemaType::kUint32},
        },
    },
    {
        "ext4_ind_map_blocks_enter",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"lblk", ProtoSchemaType::kUint32},
            {"len", ProtoSchemaType::kUint32},
            {"flags", ProtoSchemaType::kUint32},
        },
    },
    {
        "ext4_ind_map_blocks_exit",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"flags", ProtoSchemaType::kUint32},
            {"pblk", ProtoSchemaType::kUint64},
            {"lblk", ProtoSchemaType::kUint32},
            {"len", ProtoSchemaType::kUint32},
            {"mflags", ProtoSchemaType::kUint32},
            {"ret", ProtoSchemaType::kInt32},
        },
    },
    {
        "ext4_insert_range",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"offset", ProtoSchemaType::kInt64},
            {"len", ProtoSchemaType::kInt64},
        },
    },
    {
        "ext4_invalidatepage",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"index", ProtoSchemaType::kUint64},
            {"offset", ProtoSchemaType::kUint64},
            {"length", ProtoSchemaType::kUint32},
        },
    },
    {
        "ext4_journal_start",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ip", ProtoSchemaType::kUint64},
            {"blocks", ProtoSchemaType::kInt32},
            {"rsv_blocks", ProtoSchemaType::kInt32},
            {"nblocks", ProtoSchemaType::kInt32},
        },
    },
    {
        "ext4_journal_start_reserved",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ip", ProtoSchemaType::kUint64},
            {"blocks", ProtoSchemaType::kInt32},
        },
    },
    {
        "ext4_journalled_invalidatepage",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"index", ProtoSchemaType::kUint64},
            {"offset", ProtoSchemaType::kUint64},
            {"length", ProtoSchemaType::kUint32},
        },
    },
    {
        "ext4_journalled_write_end",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"pos", ProtoSchemaType::kInt64},
            {"len", ProtoSchemaType::kUint32},
            {"copied", ProtoSchemaType::kUint32},
        },
    },
    {
        "ext4_load_inode",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
        },
    },
    {
        "ext4_load_inode_bitmap",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"group", ProtoSchemaType::kUint32},
        },
    },
    {
        "ext4_mark_inode_dirty",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"ip", ProtoSchemaType::kUint64},
        },
    },
    {
        "ext4_mb_bitmap_load",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"group", ProtoSchemaType::kUint32},
        },
    },
    {
        "ext4_mb_buddy_bitmap_load",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"group", ProtoSchemaType::kUint32},
        },
    },
    {
        "ext4_mb_discard_preallocations",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"needed", ProtoSchemaType::kInt32},
        },
    },
    {
        "ext4_mb_new_group_pa",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"pa_pstart", ProtoSchemaType::kUint64},
            {"pa_lstart", ProtoSchemaType::kUint64},
            {"pa_len", ProtoSchemaType::kUint32},
        },
    },
    {
        "ext4_mb_new_inode_pa",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"pa_pstart", ProtoSchemaType::kUint64},
            {"pa_lstart", ProtoSchemaType::kUint64},
            {"pa_len", ProtoSchemaType::kUint32},
        },
    },
    {
        "ext4_mb_release_group_pa",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"pa_pstart", ProtoSchemaType::kUint64},
            {"pa_len", ProtoSchemaType::kUint32},
        },
    },
    {
        "ext4_mb_release_inode_pa",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"block", ProtoSchemaType::kUint64},
            {"count", ProtoSchemaType::kUint32},
        },
    },
    {
        "ext4_mballoc_alloc",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"orig_logical", ProtoSchemaType::kUint32},
            {"orig_start", ProtoSchemaType::kInt32},
            {"orig_group", ProtoSchemaType::kUint32},
            {"orig_len", ProtoSchemaType::kInt32},
            {"goal_logical", ProtoSchemaType::kUint32},
            {"goal_start", ProtoSchemaType::kInt32},
            {"goal_group", ProtoSchemaType::kUint32},
            {"goal_len", ProtoSchemaType::kInt32},
            {"result_logical", ProtoSchemaType::kUint32},
            {"result_start", ProtoSchemaType::kInt32},
            {"result_group", ProtoSchemaType::kUint32},
            {"result_len", ProtoSchemaType::kInt32},
            {"found", ProtoSchemaType::kUint32},
            {"groups", ProtoSchemaType::kUint32},
            {"buddy", ProtoSchemaType::kUint32},
            {"flags", ProtoSchemaType::kUint32},
            {"tail", ProtoSchemaType::kUint32},
            {"cr", ProtoSchemaType::kUint32},
        },
    },
    {
        "ext4_mballoc_discard",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"result_start", ProtoSchemaType::kInt32},
            {"result_group", ProtoSchemaType::kUint32},
            {"result_len", ProtoSchemaType::kInt32},
        },
    },
    {
        "ext4_mballoc_free",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"result_start", ProtoSchemaType::kInt32},
            {"result_group", ProtoSchemaType::kUint32},
            {"result_len", ProtoSchemaType::kInt32},
        },
    },
    {
        "ext4_mballoc_prealloc",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"orig_logical", ProtoSchemaType::kUint32},
            {"orig_start", ProtoSchemaType::kInt32},
            {"orig_group", ProtoSchemaType::kUint32},
            {"orig_len", ProtoSchemaType::kInt32},
            {"result_logical", ProtoSchemaType::kUint32},
            {"result_start", ProtoSchemaType::kInt32},
            {"result_group", ProtoSchemaType::kUint32},
            {"result_len", ProtoSchemaType::kInt32},
        },
    },
    {
        "ext4_other_inode_update_time",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"orig_ino", ProtoSchemaType::kUint64},
            {"uid", ProtoSchemaType::kUint32},
            {"gid", ProtoSchemaType::kUint32},
            {"mode", ProtoSchemaType::kUint32},
        },
    },
    {
        "ext4_punch_hole",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"offset", ProtoSchemaType::kInt64},
            {"len", ProtoSchemaType::kInt64},
            {"mode", ProtoSchemaType::kInt32},
        },
    },
    {
        "ext4_read_block_bitmap_load",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"group", ProtoSchemaType::kUint32},
        },
    },
    {
        "ext4_readpage",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"index", ProtoSchemaType::kUint64},
        },
    },
    {
        "ext4_releasepage",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"index", ProtoSchemaType::kUint64},
        },
    },
    {
        "ext4_remove_blocks",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"from", ProtoSchemaType::kUint32},
            {"to", ProtoSchemaType::kUint32},
            {"partial", ProtoSchemaType::kInt64},
            {"ee_pblk", ProtoSchemaType::kUint64},
            {"ee_lblk", ProtoSchemaType::kUint32},
            {"ee_len", ProtoSchemaType::kUint32},
        },
    },
    {
        "ext4_request_blocks",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"len", ProtoSchemaType::kUint32},
            {"logical", ProtoSchemaType::kUint32},
            {"lleft", ProtoSchemaType::kUint32},
            {"lright", ProtoSchemaType::kUint32},
            {"goal", ProtoSchemaType::kUint64},
            {"pleft", ProtoSchemaType::kUint64},
            {"pright", ProtoSchemaType::kUint64},
            {"flags", ProtoSchemaType::kUint32},
        },
    },
    {
        "ext4_request_inode",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"dir", ProtoSchemaType::kUint64},
            {"mode", ProtoSchemaType::kUint32},
        },
    },
    {
        "ext4_sync_fs",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"wait", ProtoSchemaType::kInt32},
        },
    },
    {
        "ext4_trim_all_free",
        {
            {},
            {"dev_major", ProtoSchemaType::kInt32},
            {"dev_minor", ProtoSchemaType::kInt32},
            {"group", ProtoSchemaType::kUint32},
            {"start", ProtoSchemaType::kInt32},
            {"len", ProtoSchemaType::kInt32},
        },
    },
    {
        "ext4_trim_extent",
        {
            {},
            {"dev_major", ProtoSchemaType::kInt32},
            {"dev_minor", ProtoSchemaType::kInt32},
            {"group", ProtoSchemaType::kUint32},
            {"start", ProtoSchemaType::kInt32},
            {"len", ProtoSchemaType::kInt32},
        },
    },
    {
        "ext4_truncate_enter",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"blocks", ProtoSchemaType::kUint64},
        },
    },
    {
        "ext4_truncate_exit",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"blocks", ProtoSchemaType::kUint64},
        },
    },
    {
        "ext4_unlink_enter",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"parent", ProtoSchemaType::kUint64},
            {"size", ProtoSchemaType::kInt64},
        },
    },
    {
        "ext4_unlink_exit",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"ret", ProtoSchemaType::kInt32},
        },
    },
    {
        "ext4_write_begin",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"pos", ProtoSchemaType::kInt64},
            {"len", ProtoSchemaType::kUint32},
            {"flags", ProtoSchemaType::kUint32},
        },
    },
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {
        "ext4_write_end",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"pos", ProtoSchemaType::kInt64},
            {"len", ProtoSchemaType::kUint32},
            {"copied", ProtoSchemaType::kUint32},
        },
    },
    {
        "ext4_writepage",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"index", ProtoSchemaType::kUint64},
        },
    },
    {
        "ext4_writepages",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"nr_to_write", ProtoSchemaType::kInt64},
            {"pages_skipped", ProtoSchemaType::kInt64},
            {"range_start", ProtoSchemaType::kInt64},
            {"range_end", ProtoSchemaType::kInt64},
            {"writeback_index", ProtoSchemaType::kUint64},
            {"sync_mode", ProtoSchemaType::kInt32},
            {"for_kupdate", ProtoSchemaType::kUint32},
            {"range_cyclic", ProtoSchemaType::kUint32},
        },
    },
    {
        "ext4_writepages_result",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"ret", ProtoSchemaType::kInt32},
            {"pages_written", ProtoSchemaType::kInt32},
            {"pages_skipped", ProtoSchemaType::kInt64},
            {"writeback_index", ProtoSchemaType::kUint64},
            {"sync_mode", ProtoSchemaType::kInt32},
        },
    },
    {
        "ext4_zero_range",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"offset", ProtoSchemaType::kInt64},
            {"len", ProtoSchemaType::kInt64},
            {"mode", ProtoSchemaType::kInt32},
        },
    },
    {
        "task_newtask",
        {
            {},
            {"pid", ProtoSchemaType::kInt32},
            {"comm", ProtoSchemaType::kString},
            {"clone_flags", ProtoSchemaType::kUint64},
            {"oom_score_adj", ProtoSchemaType::kInt32},
        },
    },
    {
        "task_rename",
        {
            {},
            {"pid", ProtoSchemaType::kInt32},
            {"oldcomm", ProtoSchemaType::kString},
            {"newcomm", ProtoSchemaType::kString},
            {"oom_score_adj", ProtoSchemaType::kInt32},
        },
    },
    {
        "sched_process_exec",
        {
            {},
            {"filename", ProtoSchemaType::kString},
            {"pid", ProtoSchemaType::kInt32},
            {"old_pid", ProtoSchemaType::kInt32},
        },
    },
    {
        "sched_process_exit",
        {
            {},
            {"comm", ProtoSchemaType::kString},
            {"pid", ProtoSchemaType::kInt32},
            {"tgid", ProtoSchemaType::kInt32},
            {"prio", ProtoSchemaType::kInt32},
        },
    },
    {
        "sched_process_fork",
        {
            {},
            {"parent_comm", ProtoSchemaType::kString},
            {"parent_pid", ProtoSchemaType::kInt32},
            {"child_comm", ProtoSchemaType::kString},
            {"child_pid", ProtoSchemaType::kInt32},
        },
    },
    {
        "sched_process_free",
        {
            {},
            {"comm", ProtoSchemaType::kString},
            {"pid", ProtoSchemaType::kInt32},
            {"prio", ProtoSchemaType::kInt32},
        },
    },
    {
        "sched_process_hang",
        {
            {},
            {"comm", ProtoSchemaType::kString},
            {"pid", ProtoSchemaType::kInt32},
        },
    },
    {
        "sched_process_wait",
        {
            {},
            {"comm", ProtoSchemaType::kString},
            {"pid", ProtoSchemaType::kInt32},
            {"prio", ProtoSchemaType::kInt32},
        },
    },
    {
        "f2fs_do_submit_bio",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"btype", ProtoSchemaType::kInt32},
            {"sync", ProtoSchemaType::kUint32},
            {"sector", ProtoSchemaType::kUint64},
            {"size", ProtoSchemaType::kUint32},
        },
    },
    {
        "f2fs_evict_inode",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"pino", ProtoSchemaType::kUint64},
            {"mode", ProtoSchemaType::kUint32},
            {"size", ProtoSchemaType::kInt64},
            {"nlink", ProtoSchemaType::kUint32},
            {"blocks", ProtoSchemaType::kUint64},
            {"advise", ProtoSchemaType::kUint32},
        },
    },
    {
        "f2fs_fallocate",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"mode", ProtoSchemaType::kInt32},
            {"offset", ProtoSchemaType::kInt64},
            {"len", ProtoSchemaType::kInt64},
            {"size", ProtoSchemaType::kInt64},
            {"blocks", ProtoSchemaType::kUint64},
            {"ret", ProtoSchemaType::kInt32},
        },
    },
    {
        "f2fs_get_data_block",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"iblock", ProtoSchemaType::kUint64},
            {"bh_start", ProtoSchemaType::kUint64},
            {"bh_size", ProtoSchemaType::kUint64},
            {"ret", ProtoSchemaType::kInt32},
        },
    },
    {
        "f2fs_get_victim",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"type", ProtoSchemaType::kInt32},
            {"gc_type", ProtoSchemaType::kInt32},
            {"alloc_mode", ProtoSchemaType::kInt32},
            {"gc_mode", ProtoSchemaType::kInt32},
            {"victim", ProtoSchemaType::kUint32},
            {"ofs_unit", ProtoSchemaType::kUint32},
            {"pre_victim", ProtoSchemaType::kUint32},
            {"prefree", ProtoSchemaType::kUint32},
            {"free", ProtoSchemaType::kUint32},
        },
    },
    {
        "f2fs_iget",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"pino", ProtoSchemaType::kUint64},
            {"mode", ProtoSchemaType::kUint32},
            {"size", ProtoSchemaType::kInt64},
            {"nlink", ProtoSchemaType::kUint32},
            {"blocks", ProtoSchemaType::kUint64},
            {"advise", ProtoSchemaType::kUint32},
        },
    },
    {
        "f2fs_iget_exit",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"ret", ProtoSchemaType::kInt32},
        },
    },
    {
        "f2fs_new_inode",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"ret", ProtoSchemaType::kInt32},
        },
    },
    {
        "f2fs_readpage",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"index", ProtoSchemaType::kUint64},
            {"blkaddr", ProtoSchemaType::kUint64},
            {"type", ProtoSchemaType::kInt32},
        },
    },
    {
        "f2fs_reserve_new_block",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"nid", ProtoSchemaType::kUint32},
            {"ofs_in_node", ProtoSchemaType::kUint32},
        },
    },
    {
        "f2fs_set_page_dirty",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"type", ProtoSchemaType::kInt32},
            {"dir", ProtoSchemaType::kInt32},
            {"index", ProtoSchemaType::kUint64},
            {"dirty", ProtoSchemaType::kInt32},
        },
    },
    {
        "f2fs_submit_write_page",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"type", ProtoSchemaType::kInt32},
            {"index", ProtoSchemaType::kUint64},
            {"block", ProtoSchemaType::kUint32},
        },
    },
    {
        "f2fs_sync_file_enter",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"pino", ProtoSchemaType::kUint64},
            {"mode", ProtoSchemaType::kUint32},
            {"size", ProtoSchemaType::kInt64},
            {"nlink", ProtoSchemaType::kUint32},
            {"blocks", ProtoSchemaType::kUint64},
            {"advise", ProtoSchemaType::kUint32},
        },
    },
    {
        "f2fs_sync_file_exit",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"need_cp", ProtoSchemaType::kUint32},
            {"datasync", ProtoSchemaType::kInt32},
            {"ret", ProtoSchemaType::kInt32},
        },
    },
    {
        "f2fs_sync_fs",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"dirty", ProtoSchemaType::kInt32},
            {"wait", ProtoSchemaType::kInt32},
        },
    },
    {
        "f2fs_truncate",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"pino", ProtoSchemaType::kUint64},
            {"mode", ProtoSchemaType::kUint32},
            {"size", ProtoSchemaType::kInt64},
            {"nlink", ProtoSchemaType::kUint32},
            {"blocks", ProtoSchemaType::kUint64},
            {"advise", ProtoSchemaType::kUint32},
        },
    },
    {
        "f2fs_truncate_blocks_enter",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"size", ProtoSchemaType::kInt64},
            {"blocks", ProtoSchemaType::kUint64},
            {"from", ProtoSchemaType::kUint64},
        },
    },
    {
        "f2fs_truncate_blocks_exit",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"ret", ProtoSchemaType::kInt32},
        },
    },
    {
        "f2fs_truncate_data_blocks_range",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"nid", ProtoSchemaType::kUint32},
            {"ofs", ProtoSchemaType::kUint32},
            {"free", ProtoSchemaType::kInt32},
        },
    },
    {
        "f2fs_truncate_inode_blocks_enter",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"size", ProtoSchemaType::kInt64},
            {"blocks", ProtoSchemaType::kUint64},
            {"from", ProtoSchemaType::kUint64},
        },
    },
    {
        "f2fs_truncate_inode_blocks_exit",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"ret", ProtoSchemaType::kInt32},
        },
    },
    {
        "f2fs_truncate_node",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"nid", ProtoSchemaType::kUint32},
            {"blk_addr", ProtoSchemaType::kUint32},
        },
    },
    {
        "f2fs_truncate_nodes_enter",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"nid", ProtoSchemaType::kUint32},
            {"blk_addr", ProtoSchemaType::kUint32},
        },
    },
    {
        "f2fs_truncate_nodes_exit",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"ret", ProtoSchemaType::kInt32},
        },
    },
    {
        "f2fs_truncate_partial_nodes",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"nid", ProtoSchemaType::kUint32},
            {"depth", ProtoSchemaType::kInt32},
            {"err", ProtoSchemaType::kInt32},
        },
    },
    {
        "f2fs_unlink_enter",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"size", ProtoSchemaType::kInt64},
            {"blocks", ProtoSchemaType::kUint64},
            {"name", ProtoSchemaType::kString},
        },
    },
    {
        "f2fs_unlink_exit",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"ret", ProtoSchemaType::kInt32},
        },
    },
    {
        "f2fs_vm_page_mkwrite",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"type", ProtoSchemaType::kInt32},
            {"dir", ProtoSchemaType::kInt32},
            {"index", ProtoSchemaType::kUint64},
            {"dirty", ProtoSchemaType::kInt32},
        },
    },
    {
        "f2fs_write_begin",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"pos", ProtoSchemaType::kInt64},
            {"len", ProtoSchemaType::kUint32},
            {"flags", ProtoSchemaType::kUint32},
        },
    },
    {
        "f2fs_write_checkpoint",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"is_umount", ProtoSchemaType::kUint32},
            {"msg", ProtoSchemaType::kString},
        },
    },
    {
        "f2fs_write_end",
        {
            {},
            {"dev", ProtoSchemaType::kUint64},
            {"ino", ProtoSchemaType::kUint64},
            {"pos", ProtoSchemaType::kInt64},
            {"len", ProtoSchemaType::kUint32},
            {"copied", ProtoSchemaType::kUint32},
        },
    },
    {
        "alloc_pages_iommu_end",
        {
            {},
            {"gfp_flags", ProtoSchemaType::kUint32},
            {"order", ProtoSchemaType::kUint32},
        },
    },
    {
        "alloc_pages_iommu_fail",
        {
            {},
            {"gfp_flags", ProtoSchemaType::kUint32},
            {"order", ProtoSchemaType::kUint32},
        },
    },
    {
        "alloc_pages_iommu_start",
        {
            {},
            {"gfp_flags", ProtoSchemaType::kUint32},
            {"order", ProtoSchemaType::kUint32},
        },
    },
    {
        "alloc_pages_sys_end",
        {
            {},
            {"gfp_flags", ProtoSchemaType::kUint32},
            {"order", ProtoSchemaType::kUint32},
        },
    },
    {
        "alloc_pages_sys_fail",
        {
            {},
            {"gfp_flags", ProtoSchemaType::kUint32},
            {"order", ProtoSchemaType::kUint32},
        },
    },
    {
        "alloc_pages_sys_start",
        {
            {},
            {"gfp_flags", ProtoSchemaType::kUint32},
            {"order", ProtoSchemaType::kUint32},
        },
    },
    {
        "dma_alloc_contiguous_retry",
        {
            {},
            {"tries", ProtoSchemaType::kInt32},
        },
    },
    {
        "iommu_map_range",
        {
            {},
            {"chunk_size", ProtoSchemaType::kUint64},
            {"len", ProtoSchemaType::kUint64},
            {"pa", ProtoSchemaType::kUint64},
            {"va", ProtoSchemaType::kUint64},
        },
    },
    {
        "iommu_sec_ptbl_map_range_end",
        {
            {},
            {"len", ProtoSchemaType::kUint64},
            {"num", ProtoSchemaType::kInt32},
            {"pa", ProtoSchemaType::kUint32},
            {"sec_id", ProtoSchemaType::kInt32},
            {"va", ProtoSchemaType::kUint64},
        },
    },
    {
        "iommu_sec_ptbl_map_range_start",
        {
            {},
            {"len", ProtoSchemaType::kUint64},
            {"num", ProtoSchemaType::kInt32},
            {"pa", ProtoSchemaType::kUint32},
            {"sec_id", ProtoSchemaType::kInt32},
            {"va", ProtoSchemaType::kUint64},
        },
    },
    {
        "ion_alloc_buffer_end",
        {
            {},
            {"client_name", ProtoSchemaType::kString},
            {"flags", ProtoSchemaType::kUint32},
            {"heap_name", ProtoSchemaType::kString},
            {"len", ProtoSchemaType::kUint64},
            {"mask", ProtoSchemaType::kUint32},
        },
    },
    {
        "ion_alloc_buffer_fail",
        {
            {},
            {"client_name", ProtoSchemaType::kString},
            {"error", ProtoSchemaType::kInt64},
            {"flags", ProtoSchemaType::kUint32},
            {"heap_name", ProtoSchemaType::kString},
            {"len", ProtoSchemaType::kUint64},
            {"mask", ProtoSchemaType::kUint32},
        },
    },
    {
        "ion_alloc_buffer_fallback",
        {
            {},
            {"client_name", ProtoSchemaType::kString},
            {"error", ProtoSchemaType::kInt64},
            {"flags", ProtoSchemaType::kUint32},
            {"heap_name", ProtoSchemaType::kString},
            {"len", ProtoSchemaType::kUint64},
            {"mask", ProtoSchemaType::kUint32},
        },
    },
    {
        "ion_alloc_buffer_start",
        {
            {},
            {"client_name", ProtoSchemaType::kString},
            {"flags", ProtoSchemaType::kUint32},
            {"heap_name", ProtoSchemaType::kString},
            {"len", ProtoSchemaType::kUint64},
            {"mask", ProtoSchemaType::kUint32},
        },
    },
    {
        "ion_cp_alloc_retry",
        {
            {},
            {"tries", ProtoSchemaType::kInt32},
        },
    },
    {
        "ion_cp_secure_buffer_end",
        {
            {},
            {"align", ProtoSchemaType::kUint64},
            {"flags", ProtoSchemaType::kUint64},
            {"heap_name", ProtoSchemaType::kString},
            {"len", ProtoSchemaType::kUint64},
        },
    },
    {
        "ion_cp_secure_buffer_start",
        {
            {},
            {"align", ProtoSchemaType::kUint64},
            {"flags", ProtoSchemaType::kUint64},
            {"heap_name", ProtoSchemaType::kString},
            {"len", ProtoSchemaType::kUint64},
        },
    },
    {
        "ion_prefetching",
        {
            {},
            {"len", ProtoSchemaType::kUint64},
        },
    },
    {
        "ion_secure_cma_add_to_pool_end",
        {
            {},
            {"is_prefetch", ProtoSchemaType::kUint32},
            {"len", ProtoSchemaType::kUint64},
            {"pool_total", ProtoSchemaType::kInt32},
        },
    },
    {
        "ion_secure_cma_add_to_pool_start",
        {
            {},
            {"is_prefetch", ProtoSchemaType::kUint32},
            {"len", ProtoSchemaType::kUint64},
            {"pool_total", ProtoSchemaType::kInt32},
        },
    },
    {
        "ion_secure_cma_allocate_end",
        {
            {},
            {"align", ProtoSchemaType::kUint64},
            {"flags", ProtoSchemaType::kUint64},
            {"heap_name", ProtoSchemaType::kString},
            {"len", ProtoSchemaType::kUint64},
        },
    },
    {
        "ion_secure_cma_allocate_start",
        {
            {},
            {"align", ProtoSchemaType::kUint64},
            {"flags", ProtoSchemaType::kUint64},
            {"heap_name", ProtoSchemaType::kString},
            {"len", ProtoSchemaType::kUint64},
        },
    },
    {
        "ion_secure_cma_shrink_pool_end",
        {
            {},
            {"drained_size", ProtoSchemaType::kUint64},
            {"skipped_size", ProtoSchemaType::kUint64},
        },
    },
    {
        "ion_secure_cma_shrink_pool_start",
        {
            {},
            {"drained_size", ProtoSchemaType::kUint64},
            {"skipped_size", ProtoSchemaType::kUint64},
        },
    },
    {
        "kfree",
        {
            {},
            {"call_site", ProtoSchemaType::kUint64},
            {"ptr", ProtoSchemaType::kUint64},
        },
    },
    {
        "kmalloc",
        {
            {},
            {"bytes_alloc", ProtoSchemaType::kUint64},
            {"bytes_req", ProtoSchemaType::kUint64},
            {"call_site", ProtoSchemaType::kUint64},
            {"gfp_flags", ProtoSchemaType::kUint32},
            {"ptr", ProtoSchemaType::kUint64},
        },
    },
    {
        "kmalloc_node",
        {
            {},
            {"bytes_alloc", ProtoSchemaType::kUint64},
            {"bytes_req", ProtoSchemaType::kUint64},
            {"call_site", ProtoSchemaType::kUint64},
            {"gfp_flags", ProtoSchemaType::kUint32},
            {"node", ProtoSchemaType::kInt32},
            {"ptr", ProtoSchemaType::kUint64},
        },
    },
    {
        "kmem_cache_alloc",
        {
            {},
            {"bytes_alloc", ProtoSchemaType::kUint64},
            {"bytes_req", ProtoSchemaType::kUint64},
            {"call_site", ProtoSchemaType::kUint64},
            {"gfp_flags", ProtoSchemaType::kUint32},
            {"ptr", ProtoSchemaType::kUint64},
        },
    },
    {
        "kmem_cache_alloc_node",
        {
            {},
            {"bytes_alloc", ProtoSchemaType::kUint64},
            {"bytes_req", ProtoSchemaType::kUint64},
            {"call_site", ProtoSchemaType::kUint64},
            {"gfp_flags", ProtoSchemaType::kUint32},
            {"node", ProtoSchemaType::kInt32},
            {"ptr", ProtoSchemaType::kUint64},
        },
    },
    {
        "kmem_cache_free",
        {
            {},
            {"call_site", ProtoSchemaType::kUint64},
            {"ptr", ProtoSchemaType::kUint64},
        },
    },
    {
        "migrate_pages_end",
        {
            {},
            {"mode", ProtoSchemaType::kInt32},
        },
    },
    {
        "migrate_pages_start",
        {
            {},
            {"mode", ProtoSchemaType::kInt32},
        },
    },
    {
        "migrate_retry",
        {
            {},
            {"tries", ProtoSchemaType::kInt32},
        },
    },
    {
        "mm_page_alloc",
        {
            {},
            {"gfp_flags", ProtoSchemaType::kUint32},
            {"migratetype", ProtoSchemaType::kInt32},
            {"order", ProtoSchemaType::kUint32},
            {"page", ProtoSchemaType::kUint64},
            {"pfn", ProtoSchemaType::kUint64},
        },
    },
    {
        "mm_page_alloc_extfrag",
        {
            {},
            {"alloc_migratetype", ProtoSchemaType::kInt32},
            {"alloc_order", ProtoSchemaType::kInt32},
            {"fallback_migratetype", ProtoSchemaType::kInt32},
            {"fallback_order", ProtoSchemaType::kInt32},
            {"page", ProtoSchemaType::kUint64},
            {"change_ownership", ProtoSchemaType::kInt32},
            {"pfn", ProtoSchemaType::kUint64},
        },
    },
    {
        "mm_page_alloc_zone_locked",
        {
            {},
            {"migratetype", ProtoSchemaType::kInt32},
            {"order", ProtoSchemaType::kUint32},
            {"page", ProtoSchemaType::kUint64},
            {"pfn", ProtoSchemaType::kUint64},
        },
    },
    {
        "mm_page_free",
        {
            {},
            {"order", ProtoSchemaType::kUint32},
            {"page", ProtoSchemaType::kUint64},
            {"pfn", ProtoSchemaType::kUint64},
        },
    },
    {
        "mm_page_free_batched",
        {
            {},
            {"cold", ProtoSchemaType::kInt32},
            {"page", ProtoSchemaType::kUint64},
            {"pfn", ProtoSchemaType::kUint64},
        },
    },
    {
        "mm_page_pcpu_drain",
        {
            {},
            {"migratetype", ProtoSchemaType::kInt32},
            {"order", ProtoSchemaType::kUint32},
            {"page", ProtoSchemaType::kUint64},
            {"pfn", ProtoSchemaType::kUint64},
        },
    },
    {
        "rss_stat",
        {
            {},
            {"member", ProtoSchemaType::kInt32},
            {"size", ProtoSchemaType::kInt64},
        },
    },
    {
        "ion_heap_shrink",
        {
            {},
            {"heap_name", ProtoSchemaType::kString},
            {"len", ProtoSchemaType::kUint64},
            {"total_allocated", ProtoSchemaType::kInt64},
        },
    },
    {
        "ion_heap_grow",
        {
            {},
            {"heap_name", ProtoSchemaType::kString},
            {"len", ProtoSchemaType::kUint64},
            {"total_allocated", ProtoSchemaType::kInt64},
        },
    },
    {
        "fence_init",
        {
            {},
            {"context", ProtoSchemaType::kUint32},
            {"driver", ProtoSchemaType::kString},
            {"seqno", ProtoSchemaType::kUint32},
            {"timeline", ProtoSchemaType::kString},
        },
    },
    {
        "fence_destroy",
        {
            {},
            {"context", ProtoSchemaType::kUint32},
            {"driver", ProtoSchemaType::kString},
            {"seqno", ProtoSchemaType::kUint32},
            {"timeline", ProtoSchemaType::kString},
        },
    },
    {
        "fence_enable_signal",
        {
            {},
            {"context", ProtoSchemaType::kUint32},
            {"driver", ProtoSchemaType::kString},
            {"seqno", ProtoSchemaType::kUint32},
            {"timeline", ProtoSchemaType::kString},
        },
    },
    {
        "fence_signaled",
        {
            {},
            {"context", ProtoSchemaType::kUint32},
            {"driver", ProtoSchemaType::kString},
            {"seqno", ProtoSchemaType::kUint32},
            {"timeline", ProtoSchemaType::kString},
        },
    },
    {
        "clk_enable",
        {
            {},
            {"name", ProtoSchemaType::kString},
        },
    },
    {
        "clk_disable",
        {
            {},
            {"name", ProtoSchemaType::kString},
        },
    },
    {
        "clk_set_rate",
        {
            {},
            {"name", ProtoSchemaType::kString},
            {"rate", ProtoSchemaType::kUint64},
        },
    },
    {
        "binder_transaction_alloc_buf",
        {
            {},
            {"data_size", ProtoSchemaType::kUint64},
            {"debug_id", ProtoSchemaType::kInt32},
            {"offsets_size", ProtoSchemaType::kUint64},
        },
    },
    {
        "signal_deliver",
        {
            {},
            {"code", ProtoSchemaType::kInt32},
            {"sa_flags", ProtoSchemaType::kUint64},
            {"sig", ProtoSchemaType::kInt32},
        },
    },
    {
        "signal_generate",
        {
            {},
            {"code", ProtoSchemaType::kInt32},
            {"comm", ProtoSchemaType::kString},
            {"group", ProtoSchemaType::kInt32},
            {"pid", ProtoSchemaType::kInt32},
            {"result", ProtoSchemaType::kInt32},
            {"sig", ProtoSchemaType::kInt32},
        },
    },
    {
        "oom_score_adj_update",
        {
            {},
            {"comm", ProtoSchemaType::kString},
            {"oom_score_adj", ProtoSchemaType::kInt32},
            {"pid", ProtoSchemaType::kInt32},
        },
    },
    {
        "generic",
        {
            {},
            {"event_name", ProtoSchemaType::kString},
            {},
        },
    },
    {
        "mm_event_record",
        {
            {},
            {"avg_lat", ProtoSchemaType::kUint32},
            {"count", ProtoSchemaType::kUint32},
            {"max_lat", ProtoSchemaType::kUint32},
            {"type", ProtoSchemaType::kUint32},
        },
    },
    {
        "sys_enter",
        {
            {},
            {"id", ProtoSchemaType::kInt64},
        },
    },
    {
        "sys_exit",
        {
            {},
            {"id", ProtoSchemaType::kInt64},
            {"ret", ProtoSchemaType::kInt64},
        },
    },
}};

}  // namespace

MessageDescriptor* GetMessageDescriptorForId(size_t id) {
  PERFETTO_CHECK(id < descriptors.size());
  return &descriptors[id];
}

size_t GetDescriptorsSize() {
  return descriptors.size();
}
}  // namespace trace_processor
}  // namespace perfetto
