// Copyright (C) 2025 Rivos Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Autogenerated by the ProtoZero Rust compiler plugin.
// Invoked by contrib/rust-sdk/tools/gen_rust_protos
// DO NOT EDIT.

use crate::pb_msg;

pb_msg!(CgroupSetupRootFtraceEvent {
    root: i32, primitive, 1,
    ss_mask: u32, primitive, 2,
    name: String, primitive, 3,
});

pb_msg!(CgroupRenameFtraceEvent {
    root: i32, primitive, 1,
    id: i32, primitive, 2,
    cname: String, primitive, 3,
    level: i32, primitive, 4,
    path: String, primitive, 5,
});

pb_msg!(CgroupReleaseFtraceEvent {
    root: i32, primitive, 1,
    id: i32, primitive, 2,
    cname: String, primitive, 3,
    level: i32, primitive, 4,
    path: String, primitive, 5,
});

pb_msg!(CgroupDestroyRootFtraceEvent {
    root: i32, primitive, 1,
    ss_mask: u32, primitive, 2,
    name: String, primitive, 3,
});

pb_msg!(CgroupTransferTasksFtraceEvent {
    dst_root: i32, primitive, 1,
    dst_id: i32, primitive, 2,
    pid: i32, primitive, 3,
    comm: String, primitive, 4,
    cname: String, primitive, 5,
    dst_level: i32, primitive, 6,
    dst_path: String, primitive, 7,
});

pb_msg!(CgroupRmdirFtraceEvent {
    root: i32, primitive, 1,
    id: i32, primitive, 2,
    cname: String, primitive, 3,
    level: i32, primitive, 4,
    path: String, primitive, 5,
});

pb_msg!(CgroupRemountFtraceEvent {
    root: i32, primitive, 1,
    ss_mask: u32, primitive, 2,
    name: String, primitive, 3,
});

pb_msg!(CgroupMkdirFtraceEvent {
    root: i32, primitive, 1,
    id: i32, primitive, 2,
    cname: String, primitive, 3,
    level: i32, primitive, 4,
    path: String, primitive, 5,
});

pb_msg!(CgroupAttachTaskFtraceEvent {
    dst_root: i32, primitive, 1,
    dst_id: i32, primitive, 2,
    pid: i32, primitive, 3,
    comm: String, primitive, 4,
    cname: String, primitive, 5,
    dst_level: i32, primitive, 6,
    dst_path: String, primitive, 7,
});
