// Copyright (C) 2025 Rivos Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Autogenerated by the ProtoZero Rust compiler plugin.
// Invoked by contrib/rust-sdk/tools/gen_rust_protos
// DO NOT EDIT.

use crate::pb_msg;

pb_msg!(FastrpcDmaMapFtraceEvent {
    cid: i32, primitive, 1,
    fd: i32, primitive, 2,
    phys: u64, primitive, 3,
    size: u64, primitive, 4,
    len: u64, primitive, 5,
    attr: u32, primitive, 6,
    mflags: i32, primitive, 7,
});

pb_msg!(FastrpcDmaUnmapFtraceEvent {
    cid: i32, primitive, 1,
    phys: u64, primitive, 2,
    size: u64, primitive, 3,
});

pb_msg!(FastrpcDmaAllocFtraceEvent {
    cid: i32, primitive, 1,
    phys: u64, primitive, 2,
    size: u64, primitive, 3,
    attr: u64, primitive, 4,
    mflags: i32, primitive, 5,
});

pb_msg!(FastrpcDmaFreeFtraceEvent {
    cid: i32, primitive, 1,
    phys: u64, primitive, 2,
    size: u64, primitive, 3,
});

pb_msg!(FastrpcDmaStatFtraceEvent {
    cid: i32, primitive, 1,
    len: i64, primitive, 2,
    total_allocated: u64, primitive, 3,
});
