// Copyright (C) 2025 Rivos Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Autogenerated by the ProtoZero Rust compiler plugin.
// Invoked by contrib/rust-sdk/tools/gen_rust_protos
// DO NOT EDIT.

use crate::pb_msg;

pb_msg!(PsciMemProtectFtraceEvent {
    count: u64, primitive, 1,
    was: u64, primitive, 2,
});

pb_msg!(IommuIdmapFtraceEvent {
    from: u64, primitive, 1,
    to: u64, primitive, 2,
    prot: i32, primitive, 3,
});

pb_msg!(HostFfaCallFtraceEvent {
    func_id: u64, primitive, 1,
    res_a1: u64, primitive, 2,
    res_a2: u64, primitive, 3,
    res_a3: u64, primitive, 4,
    res_a4: u64, primitive, 5,
    handled: i32, primitive, 6,
    err: i32, primitive, 7,
});

pb_msg!(HostMemAbortFtraceEvent {
    esr: u64, primitive, 1,
    addr: u64, primitive, 2,
});

pb_msg!(HostSmcFtraceEvent {
    id: u64, primitive, 1,
    forwarded: u32, primitive, 2,
});

pb_msg!(HostHcallFtraceEvent {
    id: u32, primitive, 1,
    invalid: u32, primitive, 2,
});

pb_msg!(HypExitFtraceEvent {});

pb_msg!(HypEnterFtraceEvent {});
