// Copyright (C) 2025 Rivos Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Autogenerated by the ProtoZero Rust compiler plugin.
// Invoked by contrib/rust-sdk/tools/gen_rust_protos
// DO NOT EDIT.

use crate::pb_msg;

pb_msg!(HypervisorVcpuIllegalTrapFtraceEvent {
    esr: u64, primitive, 1,
});

pb_msg!(HypervisorIommuIdmapCompleteFtraceEvent {
    map: u32, primitive, 1,
});

pb_msg!(HypervisorHypEnterFtraceEvent {});

pb_msg!(HypervisorHostMemAbortFtraceEvent {
    esr: u64, primitive, 1,
    addr: u64, primitive, 2,
});

pb_msg!(HypervisorPsciMemProtectFtraceEvent {
    count: u64, primitive, 1,
    was: u64, primitive, 2,
});

pb_msg!(HypervisorIommuIdmapFtraceEvent {
    from: u64, primitive, 1,
    to: u64, primitive, 2,
    prot: i32, primitive, 3,
});

pb_msg!(HypervisorHypExitFtraceEvent {});

pb_msg!(HypervisorHostSmcFtraceEvent {
    id: u64, primitive, 1,
    forwarded: u32, primitive, 2,
});

pb_msg!(HypervisorHostHcallFtraceEvent {
    id: u32, primitive, 1,
    invalid: u32, primitive, 2,
});
