// Copyright (C) 2025 Rivos Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Autogenerated by the ProtoZero Rust compiler plugin.
// Invoked by contrib/rust-sdk/tools/gen_rust_protos
// DO NOT EDIT.

use crate::pb_msg;

pb_msg!(RotatorBwAoAsContextFtraceEvent {
    state: u32, primitive, 1,
});

pb_msg!(MdpPerfUpdateBusFtraceEvent {
    client: i32, primitive, 1,
    ab_quota: u64, primitive, 2,
    ib_quota: u64, primitive, 3,
});

pb_msg!(MdpPerfPrefillCalcFtraceEvent {
    pnum: u32, primitive, 1,
    latency_buf: u32, primitive, 2,
    ot: u32, primitive, 3,
    y_buf: u32, primitive, 4,
    y_scaler: u32, primitive, 5,
    pp_lines: u32, primitive, 6,
    pp_bytes: u32, primitive, 7,
    post_sc: u32, primitive, 8,
    fbc_bytes: u32, primitive, 9,
    prefill_bytes: u32, primitive, 10,
});

pb_msg!(MdpCmdWaitPingpongFtraceEvent {
    ctl_num: u32, primitive, 1,
    kickoff_cnt: i32, primitive, 2,
});

pb_msg!(MdpVideoUnderrunDoneFtraceEvent {
    ctl_num: u32, primitive, 1,
    underrun_cnt: u32, primitive, 2,
});

pb_msg!(MdpPerfSetWmLevelsFtraceEvent {
    pnum: u32, primitive, 1,
    use_space: u32, primitive, 2,
    priority_bytes: u32, primitive, 3,
    wm0: u32, primitive, 4,
    wm1: u32, primitive, 5,
    wm2: u32, primitive, 6,
    mb_cnt: u32, primitive, 7,
    mb_size: u32, primitive, 8,
});

pb_msg!(MdpMixerUpdateFtraceEvent {
    mixer_num: u32, primitive, 1,
});

pb_msg!(MdpCmdReleaseBwFtraceEvent {
    ctl_num: u32, primitive, 1,
});

pb_msg!(MdpTraceCounterFtraceEvent {
    pid: i32, primitive, 1,
    counter_name: String, primitive, 2,
    value: i32, primitive, 3,
});

pb_msg!(MdpPerfSetQosLutsFtraceEvent {
    pnum: u32, primitive, 1,
    fmt: u32, primitive, 2,
    intf: u32, primitive, 3,
    rot: u32, primitive, 4,
    fl: u32, primitive, 5,
    lut: u32, primitive, 6,
    linear: u32, primitive, 7,
});

pb_msg!(MdpMisrCrcFtraceEvent {
    block_id: u32, primitive, 1,
    vsync_cnt: u32, primitive, 2,
    crc: u32, primitive, 3,
});

pb_msg!(MdpCmdReadptrDoneFtraceEvent {
    ctl_num: u32, primitive, 1,
    koff_cnt: i32, primitive, 2,
});

pb_msg!(MdpSsppSetFtraceEvent {
    num: u32, primitive, 1,
    play_cnt: u32, primitive, 2,
    mixer: u32, primitive, 3,
    stage: u32, primitive, 4,
    flags: u32, primitive, 5,
    format: u32, primitive, 6,
    img_w: u32, primitive, 7,
    img_h: u32, primitive, 8,
    src_x: u32, primitive, 9,
    src_y: u32, primitive, 10,
    src_w: u32, primitive, 11,
    src_h: u32, primitive, 12,
    dst_x: u32, primitive, 13,
    dst_y: u32, primitive, 14,
    dst_w: u32, primitive, 15,
    dst_h: u32, primitive, 16,
});

pb_msg!(MdpPerfSetPanicLutsFtraceEvent {
    pnum: u32, primitive, 1,
    fmt: u32, primitive, 2,
    mode: u32, primitive, 3,
    panic_lut: u32, primitive, 4,
    robust_lut: u32, primitive, 5,
});

pb_msg!(MdpCompareBwFtraceEvent {
    new_ab: u64, primitive, 1,
    new_ib: u64, primitive, 2,
    new_wb: u64, primitive, 3,
    old_ab: u64, primitive, 4,
    old_ib: u64, primitive, 5,
    old_wb: u64, primitive, 6,
    params_changed: u32, primitive, 7,
    update_bw: u32, primitive, 8,
});

pb_msg!(MdpCmdPingpongDoneFtraceEvent {
    ctl_num: u32, primitive, 1,
    intf_num: u32, primitive, 2,
    pp_num: u32, primitive, 3,
    koff_cnt: i32, primitive, 4,
});

pb_msg!(TracingMarkWriteFtraceEvent {
    pid: i32, primitive, 1,
    trace_name: String, primitive, 2,
    trace_begin: u32, primitive, 3,
});

pb_msg!(MdpSsppChangeFtraceEvent {
    num: u32, primitive, 1,
    play_cnt: u32, primitive, 2,
    mixer: u32, primitive, 3,
    stage: u32, primitive, 4,
    flags: u32, primitive, 5,
    format: u32, primitive, 6,
    img_w: u32, primitive, 7,
    img_h: u32, primitive, 8,
    src_x: u32, primitive, 9,
    src_y: u32, primitive, 10,
    src_w: u32, primitive, 11,
    src_h: u32, primitive, 12,
    dst_x: u32, primitive, 13,
    dst_y: u32, primitive, 14,
    dst_w: u32, primitive, 15,
    dst_h: u32, primitive, 16,
});

pb_msg!(MdpPerfSetOtFtraceEvent {
    pnum: u32, primitive, 1,
    xin_id: u32, primitive, 2,
    rd_lim: u32, primitive, 3,
    is_vbif_rt: u32, primitive, 4,
});

pb_msg!(MdpCommitFtraceEvent {
    num: u32, primitive, 1,
    play_cnt: u32, primitive, 2,
    clk_rate: u32, primitive, 3,
    bandwidth: u64, primitive, 4,
});

pb_msg!(MdpCmdKickoffFtraceEvent {
    ctl_num: u32, primitive, 1,
    kickoff_cnt: i32, primitive, 2,
});
