// Copyright (C) 2025 Rivos Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Autogenerated by the ProtoZero Rust compiler plugin.
// Invoked by contrib/rust-sdk/tools/gen_rust_protos
// DO NOT EDIT.

use crate::pb_msg;

pb_msg!(ThermalExynosAcpmHighOverheadFtraceEvent {
    tz_id: i32, primitive, 1,
    current_temp: u32, primitive, 2,
    ctrl_temp: u32, primitive, 3,
    cdev_state: u32, primitive, 4,
    pid_et_p: i32, primitive, 5,
    k_p: i32, primitive, 6,
    k_i: i32, primitive, 7,
});

pb_msg!(ThermalExynosAcpmBulkFtraceEvent {
    tz_id: u32, primitive, 1,
    current_temp: u32, primitive, 2,
    ctrl_temp: u32, primitive, 3,
    cdev_state: u32, primitive, 4,
    pid_et_p: i32, primitive, 5,
    pid_power_range: i32, primitive, 6,
    pid_p: i32, primitive, 7,
    pid_i: i32, primitive, 8,
    k_p: i32, primitive, 9,
    k_i: i32, primitive, 10,
    timestamp: u64, primitive, 11,
});
