// Copyright (C) 2025 Rivos Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Autogenerated by the ProtoZero Rust compiler plugin.
// Invoked by contrib/rust-sdk/tools/gen_rust_protos
// DO NOT EDIT.

use crate::pb_msg;

pb_msg!(TimerExpireExitFtraceEvent {
    timer: u64, primitive, 1,
});

pb_msg!(TimerExpireEntryFtraceEvent {
    timer: u64, primitive, 1,
    now: u64, primitive, 2,
    function: u64, primitive, 3,
    baseclk: u64, primitive, 4,
});

pb_msg!(TimerCancelFtraceEvent {
    timer: u64, primitive, 1,
});

pb_msg!(TimerStartFtraceEvent {
    timer: u64, primitive, 1,
    function: u64, primitive, 2,
    expires: u64, primitive, 3,
    now: u64, primitive, 4,
    deferrable: u32, primitive, 5,
    flags: u32, primitive, 6,
    bucket_expiry: u64, primitive, 7,
});

pb_msg!(HrtimerExpireExitFtraceEvent {
    hrtimer: u64, primitive, 1,
});

pb_msg!(HrtimerExpireEntryFtraceEvent {
    hrtimer: u64, primitive, 1,
    now: i64, primitive, 2,
    function: u64, primitive, 3,
});

pb_msg!(HrtimerCancelFtraceEvent {
    hrtimer: u64, primitive, 1,
});

pb_msg!(HrtimerStartFtraceEvent {
    hrtimer: u64, primitive, 1,
    function: u64, primitive, 2,
    expires: i64, primitive, 3,
    softexpires: i64, primitive, 4,
    mode: u32, primitive, 5,
});
