// Copyright (C) 2025 Rivos Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Autogenerated by the ProtoZero Rust compiler plugin.
// Invoked by contrib/rust-sdk/tools/gen_rust_protos
// DO NOT EDIT.

use crate::pb_msg;

pb_msg!(TrustyEnqueueNopFtraceEvent {
    arg1: u32, primitive, 1,
    arg2: u32, primitive, 2,
    arg3: u32, primitive, 3,
});

pb_msg!(TrustyIpcRxFtraceEvent {
    buf_id: u64, primitive, 1,
    chan: u32, primitive, 2,
    srv_name: String, primitive, 3,
});

pb_msg!(TrustyIpcReadEndFtraceEvent {
    buf_id: u64, primitive, 1,
    chan: u32, primitive, 2,
    len_or_err: i32, primitive, 3,
    shm_cnt: u64, primitive, 4,
    srv_name: String, primitive, 5,
});

pb_msg!(TrustyIpcReadFtraceEvent {
    chan: u32, primitive, 1,
    srv_name: String, primitive, 2,
});

pb_msg!(TrustyIpcPollFtraceEvent {
    chan: u32, primitive, 1,
    poll_mask: u32, primitive, 2,
    srv_name: String, primitive, 3,
});

pb_msg!(TrustyIpcWriteFtraceEvent {
    buf_id: u64, primitive, 1,
    chan: u32, primitive, 2,
    kind_shm: i32, primitive, 3,
    len_or_err: i32, primitive, 4,
    shm_cnt: u64, primitive, 5,
    srv_name: String, primitive, 6,
});

pb_msg!(TrustyIpcConnectEndFtraceEvent {
    chan: u32, primitive, 1,
    err: i32, primitive, 2,
    state: i32, primitive, 3,
});

pb_msg!(TrustyIpcConnectFtraceEvent {
    chan: u32, primitive, 1,
    port: String, primitive, 2,
    state: i32, primitive, 3,
});

pb_msg!(TrustyIpcHandleEventFtraceEvent {
    chan: u32, primitive, 1,
    event_id: u32, primitive, 2,
    srv_name: String, primitive, 3,
});

pb_msg!(TrustyIrqFtraceEvent {
    irq: i32, primitive, 1,
});

pb_msg!(TrustyReclaimMemoryDoneFtraceEvent {
    id: u64, primitive, 1,
    ret: i32, primitive, 2,
});

pb_msg!(TrustyReclaimMemoryFtraceEvent {
    id: u64, primitive, 1,
});

pb_msg!(TrustyShareMemoryDoneFtraceEvent {
    handle: u64, primitive, 1,
    len: u64, primitive, 2,
    lend: u32, primitive, 3,
    nents: u32, primitive, 4,
    ret: i32, primitive, 5,
});

pb_msg!(TrustyShareMemoryFtraceEvent {
    len: u64, primitive, 1,
    lend: u32, primitive, 2,
    nents: u32, primitive, 3,
});

pb_msg!(TrustyStdCall32DoneFtraceEvent {
    ret: i64, primitive, 1,
});

pb_msg!(TrustyStdCall32FtraceEvent {
    r0: u64, primitive, 1,
    r1: u64, primitive, 2,
    r2: u64, primitive, 3,
    r3: u64, primitive, 4,
});

pb_msg!(TrustySmcDoneFtraceEvent {
    ret: u64, primitive, 1,
});

pb_msg!(TrustySmcFtraceEvent {
    r0: u64, primitive, 1,
    r1: u64, primitive, 2,
    r2: u64, primitive, 3,
    r3: u64, primitive, 4,
});
