// Copyright (C) 2025 Rivos Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Autogenerated by the ProtoZero Rust compiler plugin.
// Invoked by contrib/rust-sdk/tools/gen_rust_protos
// DO NOT EDIT.

use crate::pb_msg;

pb_msg!(Vb2V4l2DqbufFtraceEvent {
    field: u32, primitive, 1,
    flags: u32, primitive, 2,
    minor: i32, primitive, 3,
    sequence: u32, primitive, 4,
    timecode_flags: u32, primitive, 5,
    timecode_frames: u32, primitive, 6,
    timecode_hours: u32, primitive, 7,
    timecode_minutes: u32, primitive, 8,
    timecode_seconds: u32, primitive, 9,
    timecode_type: u32, primitive, 10,
    timecode_userbits0: u32, primitive, 11,
    timecode_userbits1: u32, primitive, 12,
    timecode_userbits2: u32, primitive, 13,
    timecode_userbits3: u32, primitive, 14,
    timestamp: i64, primitive, 15,
});

pb_msg!(Vb2V4l2QbufFtraceEvent {
    field: u32, primitive, 1,
    flags: u32, primitive, 2,
    minor: i32, primitive, 3,
    sequence: u32, primitive, 4,
    timecode_flags: u32, primitive, 5,
    timecode_frames: u32, primitive, 6,
    timecode_hours: u32, primitive, 7,
    timecode_minutes: u32, primitive, 8,
    timecode_seconds: u32, primitive, 9,
    timecode_type: u32, primitive, 10,
    timecode_userbits0: u32, primitive, 11,
    timecode_userbits1: u32, primitive, 12,
    timecode_userbits2: u32, primitive, 13,
    timecode_userbits3: u32, primitive, 14,
    timestamp: i64, primitive, 15,
});

pb_msg!(Vb2V4l2BufDoneFtraceEvent {
    field: u32, primitive, 1,
    flags: u32, primitive, 2,
    minor: i32, primitive, 3,
    sequence: u32, primitive, 4,
    timecode_flags: u32, primitive, 5,
    timecode_frames: u32, primitive, 6,
    timecode_hours: u32, primitive, 7,
    timecode_minutes: u32, primitive, 8,
    timecode_seconds: u32, primitive, 9,
    timecode_type: u32, primitive, 10,
    timecode_userbits0: u32, primitive, 11,
    timecode_userbits1: u32, primitive, 12,
    timecode_userbits2: u32, primitive, 13,
    timecode_userbits3: u32, primitive, 14,
    timestamp: i64, primitive, 15,
});

pb_msg!(Vb2V4l2BufQueueFtraceEvent {
    field: u32, primitive, 1,
    flags: u32, primitive, 2,
    minor: i32, primitive, 3,
    sequence: u32, primitive, 4,
    timecode_flags: u32, primitive, 5,
    timecode_frames: u32, primitive, 6,
    timecode_hours: u32, primitive, 7,
    timecode_minutes: u32, primitive, 8,
    timecode_seconds: u32, primitive, 9,
    timecode_type: u32, primitive, 10,
    timecode_userbits0: u32, primitive, 11,
    timecode_userbits1: u32, primitive, 12,
    timecode_userbits2: u32, primitive, 13,
    timecode_userbits3: u32, primitive, 14,
    timestamp: i64, primitive, 15,
});

pb_msg!(V4l2DqbufFtraceEvent {
    bytesused: u32, primitive, 1,
    field: u32, primitive, 2,
    flags: u32, primitive, 3,
    index: u32, primitive, 4,
    minor: i32, primitive, 5,
    sequence: u32, primitive, 6,
    timecode_flags: u32, primitive, 7,
    timecode_frames: u32, primitive, 8,
    timecode_hours: u32, primitive, 9,
    timecode_minutes: u32, primitive, 10,
    timecode_seconds: u32, primitive, 11,
    timecode_type: u32, primitive, 12,
    timecode_userbits0: u32, primitive, 13,
    timecode_userbits1: u32, primitive, 14,
    timecode_userbits2: u32, primitive, 15,
    timecode_userbits3: u32, primitive, 16,
    timestamp: i64, primitive, 17,
    type: u32, primitive, 18,
});

pb_msg!(V4l2QbufFtraceEvent {
    bytesused: u32, primitive, 1,
    field: u32, primitive, 2,
    flags: u32, primitive, 3,
    index: u32, primitive, 4,
    minor: i32, primitive, 5,
    sequence: u32, primitive, 6,
    timecode_flags: u32, primitive, 7,
    timecode_frames: u32, primitive, 8,
    timecode_hours: u32, primitive, 9,
    timecode_minutes: u32, primitive, 10,
    timecode_seconds: u32, primitive, 11,
    timecode_type: u32, primitive, 12,
    timecode_userbits0: u32, primitive, 13,
    timecode_userbits1: u32, primitive, 14,
    timecode_userbits2: u32, primitive, 15,
    timecode_userbits3: u32, primitive, 16,
    timestamp: i64, primitive, 17,
    type: u32, primitive, 18,
});
