// Copyright (C) 2025 Rivos Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Autogenerated by the ProtoZero Rust compiler plugin.
// Invoked by contrib/rust-sdk/tools/gen_rust_protos
// DO NOT EDIT.

use crate::pb_msg;

pb_msg!(MmShrinkSlabEndFtraceEvent {
    new_scan: i64, primitive, 1,
    retval: i32, primitive, 2,
    shr: u64, primitive, 3,
    shrink: u64, primitive, 4,
    total_scan: i64, primitive, 5,
    unused_scan: i64, primitive, 6,
    nid: i32, primitive, 7,
});

pb_msg!(MmShrinkSlabStartFtraceEvent {
    cache_items: u64, primitive, 1,
    delta: u64, primitive, 2,
    gfp_flags: u32, primitive, 3,
    lru_pgs: u64, primitive, 4,
    nr_objects_to_shrink: i64, primitive, 5,
    pgs_scanned: u64, primitive, 6,
    shr: u64, primitive, 7,
    shrink: u64, primitive, 8,
    total_scan: u64, primitive, 9,
    nid: i32, primitive, 10,
    priority: i32, primitive, 11,
});

pb_msg!(MmVmscanKswapdSleepFtraceEvent {
    nid: i32, primitive, 1,
});

pb_msg!(MmVmscanKswapdWakeFtraceEvent {
    nid: i32, primitive, 1,
    order: i32, primitive, 2,
    zid: i32, primitive, 3,
});

pb_msg!(MmVmscanDirectReclaimEndFtraceEvent {
    nr_reclaimed: u64, primitive, 1,
});

pb_msg!(MmVmscanDirectReclaimBeginFtraceEvent {
    order: i32, primitive, 1,
    may_writepage: i32, primitive, 2,
    gfp_flags: u32, primitive, 3,
});
