// Copyright (C) 2025 Rivos Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Autogenerated by the ProtoZero Rust compiler plugin.
// Invoked by contrib/rust-sdk/tools/gen_rust_protos
// DO NOT EDIT.

use crate::pb_msg;

pb_msg!(GpuInfo {
    gpus: GpuInfoGpu, msg, 1,
});

pb_msg!(GpuInfoGpu {
    name: String, primitive, 1,
    vendor: String, primitive, 2,
    model: String, primitive, 3,
    architecture: String, primitive, 4,
    uuid: String, primitive, 5,
    pci_bdf: String, primitive, 7,
    extra_info: GpuInfoGpuKeyValue, msg, 6,
});

pb_msg!(GpuInfoGpuKeyValue {
    key: String, primitive, 1,
    value: String, primitive, 2,
});
