packet {
  trusted_packet_sequence_id: 1
  timestamp: 0
  track_descriptor {
    uuid: 1
    thread {
      pid: 1
      tid: 1
      thread_name: "t1"
    }
  }
}
packet {
  trusted_packet_sequence_id: 1
  timestamp: 0
  track_descriptor {
    uuid: 2
    thread {
      pid: 2
      tid: 2
      thread_name: "t2"
    }
  }
}
packet {
  timestamp: 10000
  trusted_packet_sequence_id: 1
  track_event {
    name: "FlowSlice1Start"
    categories: "test"
    track_uuid: 1
    flow_ids: 1
    legacy_event {
      duration_us: 10
      phase: 88 # 'X'
    }
  }
}
packet {
  timestamp: 30000
  trusted_packet_sequence_id: 1
  track_event {
    name: "FlowSlice1End"
    categories: "test"
    track_uuid: 2
    terminating_flow_ids: 1
    legacy_event {
      duration_us: 10
      phase: 88 # 'X'
    }
  }
}
packet {
  timestamp: 50000
  trusted_packet_sequence_id: 1
  track_event {
    name: "FlowSlice1Start2Start"
    categories: "test"
    track_uuid: 1
    flow_ids: 1
    flow_ids: 2
    legacy_event {
      duration_us: 10
      phase: 88 # 'X'
    }
  }
}
packet {
  timestamp: 55000
  trusted_packet_sequence_id: 1
  track_event {
    name: "FlowSlice1End"
    categories: "test"
    track_uuid: 2
    flow_ids: 1
    legacy_event {
      duration_us: 10
      phase: 88 # 'X'
    }
  }
}

packet {
  timestamp: 58000
  trusted_packet_sequence_id: 1
  track_event {
    name: "FlowSlice3Begin"
    categories: "test"
    track_uuid: 2
    flow_ids: 3
    legacy_event {
      phase: 73 # 'I'
    }
  }
}
packet {
  timestamp: 59000
  trusted_packet_sequence_id: 1
  track_event {
    name: "FlowSlice2End"
    categories: "test"
    track_uuid: 2
    flow_ids: 2
    legacy_event {
      duration_us: 10
      phase: 88 # 'X'
    }
  }
}
packet {
  trusted_packet_sequence_id: 1
  timestamp: 0
  track_descriptor {
    uuid: 11
    name: "async"
  }
}
packet {
  timestamp: 60000
  trusted_packet_sequence_id: 1
  track_event {
    name: "FlowSlice3End4Begin"
    categories: "test"
    track_uuid: 11
    terminating_flow_ids: 3
    flow_ids: 4
    type: 1, # 'TYPE_SLICE_BEGIN'
  }
}
packet {
  timestamp: 61000
  trusted_packet_sequence_id: 1
  track_event {
    name: "FlowSlice4Step"
    categories: "test"
    track_uuid: 11
    flow_ids: 4
    type: 3, # 'TYPE_SLICE_INSTANT'
  }
}
packet {
  timestamp: 62000
  trusted_packet_sequence_id: 1
  track_event {
    name: "FlowSlice3End4Begin"
    categories: "test"
    track_uuid: 11
    type: 2 # 'TYPE_SLICE_END'
  }
}
packet {
  timestamp: 63000
  trusted_packet_sequence_id: 1
  track_event {
    name: "FlowSlice4Step2_FlowIdOnAsyncEndEvent"
    categories: "test"
    track_uuid: 11
    type: 1 # 'TYPE_SLICE_BEGIN'
  }
}
packet {
  timestamp: 64000
  trusted_packet_sequence_id: 1
  track_event {
    name: "FlowSlice4Step2_FlowIdOnAsyncEndEvent"
    categories: "test"
    track_uuid: 11
    flow_ids: 4
    type: 2 # 'TYPE_SLICE_END'
  }
}
packet {
  timestamp: 65000
  trusted_packet_sequence_id: 1
  track_event {
    name: "FlowSlice4Step2_FlowIdOnEndEvent"
    categories: "test"
    track_uuid: 2
    type: 1 # 'TYPE_SLICE_BEGIN'
  }
}
packet {
  timestamp: 66000
  trusted_packet_sequence_id: 1
  track_event {
    name: "FlowSlice4Step2_FlowIdOnEndEvent"
    categories: "test"
    track_uuid: 2
    flow_ids: 4
    type: 2 # 'TYPE_SLICE_END'
  }
}
packet {
  trusted_packet_sequence_id: 1
  timestamp: 0
  track_descriptor {
    uuid: 13
    name: "processTrack"
    process {
      pid: 3
      process_name: "processTrack"
    }
  }
}
packet {
  timestamp: 67000
  trusted_packet_sequence_id: 1
  track_event {
    name: "FlowSlice4End"
    categories: "test"
    track_uuid: 13
    terminating_flow_ids: 4
    legacy_event {
      phase: 105  # 'i'
      instant_event_scope: 2  # SCOPE_PROCESS
    }
  }
}
