packet {
  timestamp: 0
  trusted_packet_sequence_id: 1
  incremental_state_cleared: true
  track_event_range_of_interest {
    start_us: 12
  }
}

# Track for slice begin/end events.
packet {
  timestamp: 0
  trusted_packet_sequence_id: 1
  track_descriptor {
    uuid: 12345
    thread {
      pid: 123
      tid: 345
    }
    parent_uuid: 0
    chrome_thread {
      thread_type: THREAD_POOL_FG_WORKER
    }
  }
}

# Slice begins. The first two slices starts before the range of interest, the

# rest are in the range.
packet {
  trusted_packet_sequence_id: 1
  timestamp: 10000
  track_event {
    track_uuid: 12345
    categories: "cat1"
    type: 1
    name: "slice1"
  }
}

packet {
  trusted_packet_sequence_id: 1
  timestamp: 11000
  track_event {
    track_uuid: 12345
    categories: "cat1"
    type: 1
    name: "slice2"
  }
}

packet {
  trusted_packet_sequence_id: 1
  timestamp: 12000
  track_event {
    track_uuid: 12345
    categories: "cat1"
    type: 1
    name: "slice3"
  }
}

packet {
  trusted_packet_sequence_id: 1
  timestamp: 13000
  track_event {
    track_uuid: 12345
    categories: "cat1"
    type: 1
    name: "slice4"
  }
}

# Slice ends
packet {
  trusted_packet_sequence_id: 1
  timestamp: 6000000
  track_event {
    track_uuid: 12345
    categories: "cat1"
    name: "slice4"
    type: 2
  }
}

packet {
  trusted_packet_sequence_id: 1
  timestamp: 6001000
  track_event {
    track_uuid: 12345
    categories: "cat1"
    name: "slice2"
    type: 2
  }
}

packet {
  trusted_packet_sequence_id: 1
  timestamp: 6002000
  track_event {
    track_uuid: 12345
    categories: "cat1"
    name: "slice2"
    type: 2
  }
}

packet {
  trusted_packet_sequence_id: 1
  timestamp: 6003000
  track_event {
    track_uuid: 12345
    categories: "cat1"
    name: "slice1"
    type: 2
  }
}
