// Copyright (C) 2025 Rivos Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Autogenerated by the ProtoZero Rust compiler plugin.
// Invoked by contrib/rust-sdk/tools/gen_rust_protos
// DO NOT EDIT.

use crate::pb_enum;
use crate::pb_msg;

pb_enum!(LogMessagePriority {
    PRIO_UNSPECIFIED: 0,
    PRIO_UNUSED: 1,
    PRIO_VERBOSE: 2,
    PRIO_DEBUG: 3,
    PRIO_INFO: 4,
    PRIO_WARN: 5,
    PRIO_ERROR: 6,
    PRIO_FATAL: 7,
});

pb_msg!(LogMessageBody {
    iid: u64, primitive, 1,
    body: String, primitive, 2,
});

pb_msg!(LogMessage {
    source_location_iid: u64, primitive, 1,
    body_iid: u64, primitive, 2,
    prio: LogMessagePriority, enum, 3,
});
