/*
 * Copyright (C) 2026 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "src/tools/proto_merger/extension_proto_merger.h"

#include <cstdio>
#include <cstring>
#include <memory>
#include <string>
#include <unordered_set>
#include <utility>
#include <vector>

#include <google/protobuf/compiler/importer.h>
#include <google/protobuf/descriptor.h>

#include "perfetto/base/logging.h"
#include "perfetto/base/status.h"
#include "perfetto/ext/base/file_utils.h"
#include "perfetto/ext/base/getopt.h"
#include "perfetto/ext/base/scoped_file.h"
#include "perfetto/ext/base/string_utils.h"
#include "perfetto/ext/base/version.h"
#include "src/protozero/multifile_error_collector.h"
#include "src/tools/proto_merger/proto_file.h"
#include "src/tools/proto_merger/proto_file_serializer.h"

namespace perfetto {
namespace proto_merger {
namespace {

struct ImportResult {
  std::unique_ptr<google::protobuf::compiler::DiskSourceTree> source_tree;
  std::unique_ptr<protozero::MultiFileErrorCollectorImpl> error_collector;
  std::unique_ptr<google::protobuf::compiler::Importer> importer;
  const google::protobuf::FileDescriptor* file_descriptor;
};

ImportResult ImportProto(const std::string& proto_file,
                         const std::string& proto_dir_path) {
  auto dst = std::make_unique<google::protobuf::compiler::DiskSourceTree>();
  dst->MapPath("", proto_dir_path);
  dst->MapPath("", ".");
  dst->MapPath("", "buildtools/protobuf/src");

  auto mfe = std::make_unique<protozero::MultiFileErrorCollectorImpl>();

  ImportResult result;
  result.importer = std::make_unique<google::protobuf::compiler::Importer>(
      dst.get(), mfe.get());
  result.source_tree = std::move(dst);
  result.error_collector = std::move(mfe);
  result.file_descriptor = result.importer->Import(proto_file);
  return result;
}

// Recursively collects all extension files and their helper dependencies,
// skipping standard base Perfetto protos, google protobuf descriptors,
// and the input base proto itself.
void CollectExtensionFiles(
    const google::protobuf::FileDescriptor* file,
    const google::protobuf::FileDescriptor* input_desc,
    std::unordered_set<const google::protobuf::FileDescriptor*>& visited,
    std::vector<const google::protobuf::FileDescriptor*>& out) {
  if (!file || file == input_desc || !visited.insert(file).second) {
    return;
  }

  std::string name(file->name());
  if (base::StartsWith(name, "protos/perfetto/") ||
      base::StartsWith(name, "google/protobuf/") ||
      (input_desc && name == input_desc->name())) {
    return;
  }

  for (int i = 0; i < file->dependency_count(); ++i) {
    CollectExtensionFiles(file->dependency(i), input_desc, visited, out);
  }

  out.push_back(file);
}

const char kUsage[] =
    R"(Usage: extension_proto_merger [-i input proto] [-I import dir] [-E extension file] [-o output]

Inlines all proto extension fields from the given extension files into the target
messages in the input proto (e.g. TracePacket, TrackEvent, InternedData) and
appends all supporting enums and messages.

-i, --input:            Path to the input .proto file (relative to --input-include directory).
-I, --input-include:    Root directory from which includes for --input proto should be searched.
-E, --extension-file:   Path to an extension .proto file (can be repeated).
-o, --output:           Output path for writing the merged proto file.
-h, --help:             Show this help message.
-v, --version:          Show version.

Example usage:
  extension_proto_merger \
    -i merged.proto \
    -I /path/to/android \
    -E proto/tracing/frameworks_base_track_event.proto \
    -o /path/to/output.proto
)";

}  // namespace

std::string ExtractPreamble(const std::string& input_contents) {
  static constexpr char kPreambleMarker[] =
      "// --- PREAMBLE ENDS HERE - EVERYTHING BELOW AUTOGENERATED ---\n";
  size_t marker_idx = input_contents.find(kPreambleMarker);
  if (marker_idx != std::string::npos) {
    return input_contents.substr(0, marker_idx + strlen(kPreambleMarker));
  }

  // Scan lines to find the first top-level message or enum definition or
  // "// Begin of" comment block.
  size_t line_start = 0;
  while (line_start < input_contents.size()) {
    size_t line_end = input_contents.find('\n', line_start);
    if (line_end == std::string::npos) {
      line_end = input_contents.size();
    }
    std::string line = input_contents.substr(line_start, line_end - line_start);
    size_t first_non_space = line.find_first_not_of(" \t\r\n");
    if (first_non_space != std::string::npos) {
      std::string trimmed = line.substr(first_non_space);
      if (base::StartsWith(trimmed, "message ") ||
          base::StartsWith(trimmed, "enum ") ||
          base::StartsWith(trimmed, "// Begin of ")) {
        return input_contents.substr(0, line_start);
      }
    }
    line_start = (line_end < input_contents.size()) ? line_end + 1
                                                    : input_contents.size();
  }

  return "";
}

base::Status MergeExtensions(const std::string& input,
                             const std::string& input_include,
                             const std::vector<std::string>& extension_files,
                             std::string* output_contents) {
  if (input.empty()) {
    return base::ErrStatus("Input proto must be specified");
  }
  if (input_include.empty()) {
    return base::ErrStatus("Input include directory must be specified");
  }

  std::string input_file_contents;
  if (!base::ReadFile(input_include + "/" + input, &input_file_contents)) {
    return base::ErrStatus("Failed to read input file: %s/%s",
                           input_include.c_str(), input.c_str());
  }

  std::string input_preamble = ExtractPreamble(input_file_contents);

  ImportResult input_proto = ImportProto(input, input_include);
  if (!input_proto.file_descriptor) {
    return base::ErrStatus("Failed to import input proto: %s", input.c_str());
  }

  // Setup DiskSourceTree mapping for Android repos and includes.
  auto ext_dst = std::make_unique<google::protobuf::compiler::DiskSourceTree>();
  ext_dst->MapPath("", input_include);
  ext_dst->MapPath("", input_include + "/external/perfetto");
  ext_dst->MapPath("", ".");
  ext_dst->MapPath("", "buildtools/protobuf/src");

  protozero::MultiFileErrorCollectorImpl ext_mfe;
  google::protobuf::compiler::Importer ext_importer(ext_dst.get(), &ext_mfe);

  std::vector<const google::protobuf::FileDescriptor*> extension_descs;
  std::unordered_set<const google::protobuf::FileDescriptor*> visited_descs;

  for (const auto& raw_path : extension_files) {
    const auto* ext_desc = ext_importer.Import(raw_path);
    if (!ext_desc) {
      return base::ErrStatus("Failed to import extension proto: %s",
                             raw_path.c_str());
    }
    CollectExtensionFiles(ext_desc, input_proto.file_descriptor, visited_descs,
                          extension_descs);
  }

  // Convert the input descriptor into a ProtoFile model while inlining all
  // extension fields and adding all helper types from extension_descs.
  ProtoFile merged_file = ProtoFileFromDescriptor(
      std::move(input_preamble), *input_proto.file_descriptor, extension_descs);

  *output_contents = ProtoFileToDotProto(merged_file);
  return base::OkStatus();
}

int ExtensionProtoMergerMain(int argc, char** argv) {
  static const option long_options[] = {
      {"help", no_argument, nullptr, 'h'},
      {"version", no_argument, nullptr, 'v'},
      {"input", required_argument, nullptr, 'i'},
      {"input-include", required_argument, nullptr, 'I'},
      {"extension-file", required_argument, nullptr, 'E'},
      {"output", required_argument, nullptr, 'o'},
      {nullptr, 0, nullptr, 0}};

  std::string input;
  std::string input_include;
  std::vector<std::string> extension_files;
  std::string output;

  for (;;) {
    int option = getopt_long(argc, argv, "hvi:I:E:o:", long_options, nullptr);

    if (option == -1)
      break;  // EOF.

    if (option == 'v') {
      printf("%s\n", base::GetVersionString());
      return 0;
    }

    if (option == 'i') {
      input = optarg;
      continue;
    }

    if (option == 'I') {
      input_include = optarg;
      continue;
    }

    if (option == 'E') {
      extension_files.push_back(optarg);
      continue;
    }

    if (option == 'o') {
      output = optarg;
      continue;
    }

    if (option == 'h') {
      fprintf(stdout, "%s", kUsage);
      return 0;
    }

    fprintf(stderr, "%s", kUsage);
    return 1;
  }

  if (input.empty()) {
    PERFETTO_ELOG("Input proto (--input) must be specified");
    return 1;
  }

  if (input_include.empty()) {
    PERFETTO_ELOG(
        "Input include directory (--input-include) must be specified");
    return 1;
  }

  if (output.empty()) {
    PERFETTO_ELOG("Output file (--output) must be specified");
    return 1;
  }

  std::string out;
  base::Status status =
      MergeExtensions(input, input_include, extension_files, &out);
  if (!status.ok()) {
    PERFETTO_ELOG("%s", status.c_message());
    return 1;
  }

  base::ScopedFile output_file(
      base::OpenFile(output, O_CREAT | O_WRONLY | O_TRUNC, 0664));
  if (!output_file) {
    PERFETTO_ELOG("Failed opening output file: %s", output.c_str());
    return 1;
  }
  base::WriteAll(*output_file, out.c_str(), out.size());

  return 0;
}

}  // namespace proto_merger
}  // namespace perfetto
