packet {
  ftrace_events {
    cpu: 0
    event {
      timestamp: 10000
      pid: 200
      ufshcd_command {
        dev_name: "cat"
        doorbell: 0x200
        opcode: 40
        tag: 1
        group_id: 0
        str_t: 0
      }
    }
  }
}
packet {
  ftrace_events {
    cpu: 1
    event {
      timestamp: 10008
      pid: 300
      ufshcd_command {
        dev_name: "cat"
        doorbell: 0x240
        opcode: 40
        tag: 2
        group_id: 0
        str_t: 0
      }
    }
  }
}
packet {
  ftrace_events {
    cpu: 2
    event {
      timestamp: 10010
      pid: 400
      ufshcd_command {
        dev_name: "dd"
        doorbell: 0x111
        opcode: 40
        tag: 3
        group_id: 0
        str_t: 0
      }
    }
  }
}
packet {
  ftrace_events {
    cpu: 1
    event {
      timestamp: 10011
      pid: 500
      ufshcd_command {
        dev_name: "dd"
        doorbell: 0x400
        opcode: 40
        tag: 4
        group_id: 0
        str_t: 0
      }
    }
  }
}
