// Copyright (C) 2025 Rivos Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Autogenerated by the ProtoZero Rust compiler plugin.
// Invoked by contrib/rust-sdk/tools/gen_rust_protos
// DO NOT EDIT.

use crate::pb_msg;
use crate::pb_msg_ext;
use crate::protos::trace::gpu::gpu_render_stage_event::*;
use perfetto_sdk::protos::trace::interned_data::interned_data::*;

pb_msg_ext!(InternedData {
    compute_kernels: InternedComputeKernel, msg, 1000,
    compute_arg_names: InternedComputeArgName, msg, 1001,
});
