// Copyright (C) 2025 Rivos Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Autogenerated by the gen_rust_protos script.
// DO NOT EDIT.

/// `gpu_counter_event` protos.
#[path = "gpu_counter_event.pz.rs"]
pub mod gpu_counter_event;

/// `gpu_log` protos.
#[path = "gpu_log.pz.rs"]
pub mod gpu_log;

/// `gpu_render_stage_event` protos.
#[path = "gpu_render_stage_event.pz.rs"]
pub mod gpu_render_stage_event;

/// `vulkan_api_event` protos.
#[path = "vulkan_api_event.pz.rs"]
pub mod vulkan_api_event;

/// `vulkan_memory_event` protos.
#[path = "vulkan_memory_event.pz.rs"]
pub mod vulkan_memory_event;
