// Copyright (C) 2025 Rivos Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Autogenerated by the ProtoZero Rust compiler plugin.
// Invoked by contrib/rust-sdk/tools/gen_rust_protos
// DO NOT EDIT.

use crate::pb_msg;

pb_msg!(VulkanApiEvent {
    vk_debug_utils_object_name: VkDebugUtilsObjectName, msg, 1,
    vk_queue_submit: VkQueueSubmit, msg, 2,
});

pb_msg!(VkQueueSubmit {
    duration_ns: u64, primitive, 1,
    pid: u32, primitive, 2,
    tid: u32, primitive, 3,
    vk_queue: u64, primitive, 4,
    vk_command_buffers: u64, primitive, 5,
    submission_id: u32, primitive, 6,
});

pb_msg!(VkDebugUtilsObjectName {
    pid: u32, primitive, 1,
    vk_device: u64, primitive, 2,
    object_type: i32, primitive, 3,
    object: u64, primitive, 4,
    object_name: String, primitive, 5,
});
