#!/usr/bin/env python3
# Copyright (C) 2025 Rivos Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import argparse
import filecmp
import os
import pathlib
import shutil
import subprocess
import sys
import tempfile
from collections import defaultdict

SOURCE_FILES = [
    {
        "files": [
            "protos/perfetto/common/builtin_clock.proto",
            "protos/perfetto/common/semantic_type.proto",
            "protos/perfetto/common/track_event_descriptor.proto",
            "protos/perfetto/config/priority_boost/priority_boost_config.proto",
            "protos/perfetto/config/test_config.proto",
            "protos/perfetto/config/trace_config.proto",
            "protos/perfetto/config/track_event/track_event_config.proto",
            "protos/perfetto/trace/clock_snapshot.proto",
            "protos/perfetto/trace/profiling/profile_common.proto",
            "protos/perfetto/trace/test_event.proto",
            "protos/perfetto/trace/trace.proto",
            "protos/perfetto/trace/track_event/chrome_active_processes.proto",
            "protos/perfetto/trace/track_event/chrome_application_state_info.proto",
            "protos/perfetto/trace/track_event/chrome_compositor_scheduler_state.proto",
            "protos/perfetto/trace/track_event/chrome_content_settings_event_info.proto",
            "protos/perfetto/trace/track_event/chrome_frame_reporter.proto",
            "protos/perfetto/trace/track_event/chrome_histogram_sample.proto",
            "protos/perfetto/trace/track_event/chrome_keyed_service.proto",
            "protos/perfetto/trace/track_event/chrome_latency_info.proto",
            "protos/perfetto/trace/track_event/chrome_legacy_ipc.proto",
            "protos/perfetto/trace/track_event/chrome_message_pump.proto",
            "protos/perfetto/trace/track_event/chrome_mojo_event_info.proto",
            "protos/perfetto/trace/track_event/chrome_process_descriptor.proto",
            "protos/perfetto/trace/track_event/chrome_renderer_scheduler_state.proto",
            "protos/perfetto/trace/track_event/chrome_thread_descriptor.proto",
            "protos/perfetto/trace/track_event/chrome_user_event.proto",
            "protos/perfetto/trace/track_event/chrome_window_handle_event_info.proto",
            "protos/perfetto/trace/track_event/counter_descriptor.proto",
            "protos/perfetto/trace/track_event/debug_annotation.proto",
            "protos/perfetto/trace/track_event/log_message.proto",
            "protos/perfetto/trace/track_event/process_descriptor.proto",
            "protos/perfetto/trace/track_event/screenshot.proto",
            "protos/perfetto/trace/track_event/source_location.proto",
            "protos/perfetto/trace/track_event/task_execution.proto",
            "protos/perfetto/trace/track_event/thread_descriptor.proto",
            "protos/perfetto/trace/track_event/track_descriptor.proto",
            "protos/perfetto/trace/track_event/track_event.proto",
        ],
        "custom_files": [
            "protos/perfetto/common/data_source_descriptor.proto",
            "protos/perfetto/config/data_source_config.proto",
            "protos/perfetto/trace/interned_data/interned_data.proto",
            "protos/perfetto/trace/trace_packet.proto",
        ],
        "path_strip_prefix": "protos/perfetto",
        "path_add_prefix": "contrib/rust-sdk/perfetto/src/protos",
    },
    {
        "files": [
            "protos/perfetto/common/gpu_counter_descriptor.proto",
            "protos/perfetto/config/gpu/gpu_counter_config.proto",
            "protos/perfetto/config/gpu/gpu_renderstages_config.proto",
            "protos/perfetto/config/gpu/vulkan_memory_config.proto",
            "protos/perfetto/trace/gpu/gpu_counter_event.proto",
            "protos/perfetto/trace/gpu/gpu_log.proto",
            "protos/perfetto/trace/gpu/gpu_render_stage_event.proto",
            "protos/perfetto/trace/gpu/vulkan_api_event.proto",
            "protos/perfetto/trace/gpu/vulkan_memory_event.proto",
            "protos/perfetto/trace/system_info/gpu_info.proto",
        ],
        "custom_files": [
            "protos/perfetto/common/data_source_descriptor.proto",
            "protos/perfetto/config/data_source_config.proto",
            "protos/perfetto/trace/interned_data/interned_data.proto",
            "protos/perfetto/trace/trace_packet.proto",
        ],
        "path_strip_prefix": "protos/perfetto",
        "path_add_prefix": "contrib/rust-sdk/perfetto-protos-gpu/src/protos",
    },
    {
        "files": [
            "protos/perfetto/config/ftrace/ftrace_config.proto",
            "protos/perfetto/config/ftrace/frozen_ftrace_config.proto",
            "protos/perfetto/trace/ftrace/android_fs.proto",
            "protos/perfetto/trace/ftrace/bcl_exynos.proto",
            "protos/perfetto/trace/ftrace/binder.proto",
            "protos/perfetto/trace/ftrace/block.proto",
            "protos/perfetto/trace/ftrace/cgroup.proto",
            "protos/perfetto/trace/ftrace/clk.proto",
            "protos/perfetto/trace/ftrace/cma.proto",
            "protos/perfetto/trace/ftrace/compaction.proto",
            "protos/perfetto/trace/ftrace/cpm_trace.proto",
            "protos/perfetto/trace/ftrace/cpuhp.proto",
            "protos/perfetto/trace/ftrace/cros_ec.proto",
            "protos/perfetto/trace/ftrace/dcvsh.proto",
            "protos/perfetto/trace/ftrace/devfreq.proto",
            "protos/perfetto/trace/ftrace/dma_fence.proto",
            "protos/perfetto/trace/ftrace/dmabuf_heap.proto",
            "protos/perfetto/trace/ftrace/dpu.proto",
            "protos/perfetto/trace/ftrace/drm.proto",
            "protos/perfetto/trace/ftrace/dwc3.proto",
            "protos/perfetto/trace/ftrace/ext4.proto",
            "protos/perfetto/trace/ftrace/f2fs.proto",
            "protos/perfetto/trace/ftrace/fastrpc.proto",
            "protos/perfetto/trace/ftrace/fence.proto",
            "protos/perfetto/trace/ftrace/filemap.proto",
            "protos/perfetto/trace/ftrace/fs.proto",
            "protos/perfetto/trace/ftrace/ftrace.proto",
            "protos/perfetto/trace/ftrace/ftrace_event.proto",
            "protos/perfetto/trace/ftrace/ftrace_event_bundle.proto",
            "protos/perfetto/trace/ftrace/ftrace_stats.proto",
            "protos/perfetto/trace/ftrace/fwtp_ftrace.proto",
            "protos/perfetto/trace/ftrace/g2d.proto",
            "protos/perfetto/trace/ftrace/generic.proto",
            "protos/perfetto/trace/ftrace/google_icc_trace.proto",
            "protos/perfetto/trace/ftrace/google_irm_trace.proto",
            "protos/perfetto/trace/ftrace/gpu_mem.proto",
            "protos/perfetto/trace/ftrace/gpu_scheduler.proto",
            "protos/perfetto/trace/ftrace/hyp.proto",
            "protos/perfetto/trace/ftrace/hypervisor.proto",
            "protos/perfetto/trace/ftrace/i2c.proto",
            "protos/perfetto/trace/ftrace/ion.proto",
            "protos/perfetto/trace/ftrace/ipi.proto",
            "protos/perfetto/trace/ftrace/irq.proto",
            "protos/perfetto/trace/ftrace/irq_vectors.proto",
            "protos/perfetto/trace/ftrace/kfree.proto",
            "protos/perfetto/trace/ftrace/kgsl.proto",
            "protos/perfetto/trace/ftrace/kmalloc.proto",
            "protos/perfetto/trace/ftrace/kmem.proto",
            "protos/perfetto/trace/ftrace/kvm.proto",
            "protos/perfetto/trace/ftrace/lowmemorykiller.proto",
            "protos/perfetto/trace/ftrace/lwis.proto",
            "protos/perfetto/trace/ftrace/mali.proto",
            "protos/perfetto/trace/ftrace/mdss.proto",
            "protos/perfetto/trace/ftrace/mm_event.proto",
            "protos/perfetto/trace/ftrace/net.proto",
            "protos/perfetto/trace/ftrace/oom.proto",
            "protos/perfetto/trace/ftrace/panel.proto",
            "protos/perfetto/trace/ftrace/perf_trace_counters.proto",
            "protos/perfetto/trace/ftrace/pixel_mm.proto",
            "protos/perfetto/trace/ftrace/power.proto",
            "protos/perfetto/trace/ftrace/print.proto",
            "protos/perfetto/trace/ftrace/printk.proto",
            "protos/perfetto/trace/ftrace/raw_syscalls.proto",
            "protos/perfetto/trace/ftrace/regulator.proto",
            "protos/perfetto/trace/ftrace/rpm.proto",
            "protos/perfetto/trace/ftrace/samsung.proto",
            "protos/perfetto/trace/ftrace/sched.proto",
            "protos/perfetto/trace/ftrace/scm.proto",
            "protos/perfetto/trace/ftrace/scsi.proto",
            "protos/perfetto/trace/ftrace/sde.proto",
            "protos/perfetto/trace/ftrace/signal.proto",
            "protos/perfetto/trace/ftrace/skb.proto",
            "protos/perfetto/trace/ftrace/sock.proto",
            "protos/perfetto/trace/ftrace/sync.proto",
            "protos/perfetto/trace/ftrace/synthetic.proto",
            "protos/perfetto/trace/ftrace/systrace.proto",
            "protos/perfetto/trace/ftrace/task.proto",
            "protos/perfetto/trace/ftrace/tcp.proto",
            "protos/perfetto/trace/ftrace/thermal.proto",
            "protos/perfetto/trace/ftrace/thermal_exynos.proto",
            "protos/perfetto/trace/ftrace/timer.proto",
            "protos/perfetto/trace/ftrace/trusty.proto",
            "protos/perfetto/trace/ftrace/ufs.proto",
            "protos/perfetto/trace/ftrace/v4l2.proto",
            "protos/perfetto/trace/ftrace/virtio_gpu.proto",
            "protos/perfetto/trace/ftrace/virtio_video.proto",
            "protos/perfetto/trace/ftrace/vmscan.proto",
            "protos/perfetto/trace/ftrace/workqueue.proto",
        ],
        "custom_files": [
            "protos/perfetto/config/data_source_config.proto",
            "protos/perfetto/trace/trace_packet.proto",
        ],
        "path_strip_prefix": "protos/perfetto",
        "path_add_prefix": "contrib/rust-sdk/perfetto-protos-ftrace/src/protos",
    },
    {
        "files": [
            "protos/perfetto/common/descriptor.proto",
            "protos/perfetto/perfetto_sql/structured_query.proto",
            "protos/perfetto/trace_processor/metatrace_categories.proto",
            "protos/perfetto/trace_processor/trace_processor.proto",
            "protos/perfetto/trace_summary/file.proto",
            "protos/perfetto/trace_summary/v2_metric.proto",
        ],
        "custom_files": [],
        "path_strip_prefix":
            "protos/perfetto",
        "path_add_prefix":
            "contrib/rust-sdk/perfetto-protos-trace-processor/src/protos",
    },
]

ROOT_DIR = os.path.dirname(
    os.path.dirname(
        os.path.dirname(os.path.dirname(os.path.realpath(__file__)))))
IS_WIN = sys.platform.startswith("win")

SCRIPT_PATH = "contrib/rust-sdk/tools/gen_rust_protos"


def protozero_rust_plugin_path(out_directory):
  path = os.path.join(out_directory,
                      "protozero_rust_plugin") + (".exe" if IS_WIN else "")
  assert os.path.isfile(path)
  return path


def protoc_path(out_directory):
  path = os.path.join(out_directory, "protoc") + (".exe" if IS_WIN else "")
  assert os.path.isfile(path)
  return path


def call(cmd, *args):
  path = os.path.join("tools", cmd)
  command = ["python3", path] + list(args)
  print("Running", " ".join(command))
  try:
    subprocess.check_call(command, cwd=ROOT_DIR)
  except subprocess.CalledProcessError as e:
    assert False, "Command: {} failed".format(" ".join(command))


# Transforms filename extension like the ProtoZero Rust plugin
def transform_extension(filename):
  old_suffix = ".proto"
  new_suffix = ".pz.rs"
  if filename.endswith(old_suffix):
    return filename[:-len(old_suffix)] + new_suffix
  return filename


def generate(
    source,
    outdir,
    protoc_path,
    protozero_rust_plugin_path,
    path_strip_prefix,
    path_add_prefix,
):
  options = {
      "path_strip_prefix": path_strip_prefix,
      "path_add_prefix": path_add_prefix,
      "invoker": SCRIPT_PATH,
  }
  serialized_options = ",".join(
      ["{}={}".format(name, value) for name, value in options.items()])
  subprocess.check_call(
      [
          protoc_path,
          "--proto_path=.",
          "--plugin=protoc-gen-plugin={}".format(protozero_rust_plugin_path),
          "--plugin_out={}:{}".format(serialized_options, outdir),
          source,
      ],
      cwd=ROOT_DIR,
  )


def generate_mod(tmpfilename, mods):
  with open(tmpfilename, "w") as f:
    print(
        """// Copyright (C) 2025 Rivos Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Autogenerated by the gen_rust_protos script.
// DO NOT EDIT.""",
        file=f,
    )
    for mod in sorted(mods):
      modname = transform_extension(os.path.basename(mod))
      if modname.endswith(".pz.rs"):
        print(f"\n/// `{modname[:-6]}` protos.", file=f)
        print(f'#[path = "{modname}"]', file=f)
        print(f"pub mod {modname[:-6]};", file=f)
      else:
        print(f"\n/// `{modname}` protos.", file=f)
        print(f"pub mod {modname};", file=f)


def mods_by_directory(sources, path_strip_prefix):
  groups = defaultdict(set)
  for path in sources:
    if path.startswith(path_strip_prefix):
      path = path[len(path_strip_prefix):]
    modpath = pathlib.Path(path)
    for parent in modpath.parents:
      if parent != pathlib.Path("/"):
        directory = str(parent)
        groups[directory].add(path)
        path = directory
  return dict(groups)


def rust_path_for(path, path_strip_prefix, path_add_prefix):
  if path.startswith(path_strip_prefix):
    rust_path = path[len(path_strip_prefix):]
  else:
    rust_path = path
  return path_add_prefix + rust_path


def main():
  parser = argparse.ArgumentParser()
  parser.add_argument("--check-only", action="store_true")
  parser.add_argument("OUT")
  args = parser.parse_args()
  out = args.OUT

  call("ninja", "-C", out, "protoc", "protozero_rust_plugin")

  try:
    with tempfile.TemporaryDirectory() as tmpdirname:
      for sources in SOURCE_FILES:
        for source in sources["files"]:
          generate(
              source,
              tmpdirname,
              protoc_path(out),
              protozero_rust_plugin_path(out),
              path_strip_prefix=sources["path_strip_prefix"],
              path_add_prefix=sources["path_add_prefix"],
          )

          tmpfilename = os.path.join(tmpdirname, transform_extension(source))
          targetfilename = rust_path_for(
              source,
              sources["path_strip_prefix"],
              sources["path_add_prefix"],
          )
          targetfilename = transform_extension(targetfilename)

          if args.check_only:
            if not filecmp.cmp(tmpfilename, targetfilename):
              raise AssertionError("Target {} does not match", targetfilename)
          else:
            os.makedirs(os.path.dirname(targetfilename), exist_ok=True)
            shutil.copyfile(tmpfilename, targetfilename)

        modsources = sources["files"] + sources["custom_files"]
        for directory, mods in mods_by_directory(
            modsources, sources["path_strip_prefix"]).items():
          tmpfilename = os.path.join(tmpdirname, "mod.rs")
          generate_mod(tmpfilename, mods)
          targetmoddir = rust_path_for(
              directory,
              sources["path_strip_prefix"],
              sources["path_add_prefix"],
          )
          targetfilename = os.path.join(targetmoddir, "mod.rs")

          if args.check_only:
            if not filecmp.cmp(tmpfilename, targetfilename):
              raise AssertionError("Target {} does not match", targetfilename)
          else:
            os.makedirs(os.path.dirname(targetfilename), exist_ok=True)
            shutil.copyfile(tmpfilename, targetfilename)

  except AssertionError as e:
    if not str(e):
      raise
    print("Error: {}".format(e))
    return 1


if __name__ == "__main__":
  exit(main())
