--
-- Copyright 2024 The Android Open Source Project
--
-- Licensed under the Apache License, Version 2.0 (the 'License');
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     https://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an 'AS IS' BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

-- DELETED: absorbed by TREE KEEP IF ANCESTOR OF … OVER. The
-- `_tree_reachable_ancestors_or_self!` macro (a `graph_reachable_dfs` walk up a
-- tree) inlines into its consumers as `TREE KEEP IF ANCESTOR OF <set> OVER <tree>`.
