// Autogenerated by:
// ../../tools/ftrace_proto_gen/ftrace_proto_gen.cc
// Do not edit.

#include "src/ftrace_reader/event_info.h"

namespace perfetto {

std::vector<Event> GetStaticEventInfo() {
  std::vector<Event> events;

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "binder_lock";
    event->group = "binder";
    event->proto_field_id = 53;
    event->fields.push_back(MakeField("tag", 1, kProtoString));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "binder_locked";
    event->group = "binder";
    event->proto_field_id = 54;
    event->fields.push_back(MakeField("tag", 1, kProtoString));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "binder_set_priority";
    event->group = "binder";
    event->proto_field_id = 52;
    event->fields.push_back(MakeField("proc", 1, kProtoInt32));
    event->fields.push_back(MakeField("thread", 2, kProtoInt32));
    event->fields.push_back(MakeField("old_prio", 3, kProtoUint32));
    event->fields.push_back(MakeField("new_prio", 4, kProtoUint32));
    event->fields.push_back(MakeField("desired_prio", 5, kProtoUint32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "binder_transaction";
    event->group = "binder";
    event->proto_field_id = 50;
    event->fields.push_back(MakeField("debug_id", 1, kProtoInt32));
    event->fields.push_back(MakeField("target_node", 2, kProtoInt32));
    event->fields.push_back(MakeField("to_proc", 3, kProtoInt32));
    event->fields.push_back(MakeField("to_thread", 4, kProtoInt32));
    event->fields.push_back(MakeField("reply", 5, kProtoInt32));
    event->fields.push_back(MakeField("code", 6, kProtoUint32));
    event->fields.push_back(MakeField("flags", 7, kProtoUint32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "binder_transaction_received";
    event->group = "binder";
    event->proto_field_id = 51;
    event->fields.push_back(MakeField("debug_id", 1, kProtoInt32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "binder_unlock";
    event->group = "binder";
    event->proto_field_id = 55;
    event->fields.push_back(MakeField("tag", 1, kProtoString));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "block_rq_issue";
    event->group = "block";
    event->proto_field_id = 45;
    event->fields.push_back(MakeField("dev", 1, kProtoUint32));
    event->fields.push_back(MakeField("sector", 2, kProtoUint64));
    event->fields.push_back(MakeField("nr_sector", 3, kProtoUint32));
    event->fields.push_back(MakeField("bytes", 4, kProtoUint32));
    event->fields.push_back(MakeField("rwbs", 5, kProtoString));
    event->fields.push_back(MakeField("comm", 6, kProtoString));
    event->fields.push_back(MakeField("cmd", 7, kProtoString));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "cgroup_attach_task";
    event->group = "cgroup";
    event->proto_field_id = 67;
    event->fields.push_back(MakeField("dst_root", 1, kProtoInt32));
    event->fields.push_back(MakeField("dst_id", 2, kProtoInt32));
    event->fields.push_back(MakeField("pid", 3, kProtoInt32));
    event->fields.push_back(MakeField("comm", 4, kProtoString));
    event->fields.push_back(MakeField("cname", 5, kProtoString));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "cgroup_destroy_root";
    event->group = "cgroup";
    event->proto_field_id = 72;
    event->fields.push_back(MakeField("root", 1, kProtoInt32));
    event->fields.push_back(MakeField("ss_mask", 2, kProtoUint32));
    event->fields.push_back(MakeField("name", 3, kProtoString));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "cgroup_mkdir";
    event->group = "cgroup";
    event->proto_field_id = 68;
    event->fields.push_back(MakeField("root", 1, kProtoInt32));
    event->fields.push_back(MakeField("id", 2, kProtoInt32));
    event->fields.push_back(MakeField("cname", 3, kProtoString));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "cgroup_release";
    event->group = "cgroup";
    event->proto_field_id = 73;
    event->fields.push_back(MakeField("root", 1, kProtoInt32));
    event->fields.push_back(MakeField("id", 2, kProtoInt32));
    event->fields.push_back(MakeField("cname", 3, kProtoString));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "cgroup_remount";
    event->group = "cgroup";
    event->proto_field_id = 69;
    event->fields.push_back(MakeField("root", 1, kProtoInt32));
    event->fields.push_back(MakeField("ss_mask", 2, kProtoUint32));
    event->fields.push_back(MakeField("name", 3, kProtoString));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "cgroup_rename";
    event->group = "cgroup";
    event->proto_field_id = 74;
    event->fields.push_back(MakeField("root", 1, kProtoInt32));
    event->fields.push_back(MakeField("id", 2, kProtoInt32));
    event->fields.push_back(MakeField("cname", 3, kProtoString));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "cgroup_rmdir";
    event->group = "cgroup";
    event->proto_field_id = 70;
    event->fields.push_back(MakeField("root", 1, kProtoInt32));
    event->fields.push_back(MakeField("id", 2, kProtoInt32));
    event->fields.push_back(MakeField("cname", 3, kProtoString));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "cgroup_setup_root";
    event->group = "cgroup";
    event->proto_field_id = 75;
    event->fields.push_back(MakeField("root", 1, kProtoInt32));
    event->fields.push_back(MakeField("ss_mask", 2, kProtoUint32));
    event->fields.push_back(MakeField("name", 3, kProtoString));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "cgroup_transfer_tasks";
    event->group = "cgroup";
    event->proto_field_id = 71;
    event->fields.push_back(MakeField("dst_root", 1, kProtoInt32));
    event->fields.push_back(MakeField("dst_id", 2, kProtoInt32));
    event->fields.push_back(MakeField("pid", 3, kProtoInt32));
    event->fields.push_back(MakeField("comm", 4, kProtoString));
    event->fields.push_back(MakeField("cname", 5, kProtoString));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "mm_compaction_begin";
    event->group = "compaction";
    event->proto_field_id = 99;
    event->fields.push_back(MakeField("zone_start", 1, kProtoUint64));
    event->fields.push_back(MakeField("migrate_pfn", 2, kProtoUint64));
    event->fields.push_back(MakeField("free_pfn", 3, kProtoUint64));
    event->fields.push_back(MakeField("zone_end", 4, kProtoUint64));
    event->fields.push_back(MakeField("sync", 5, kProtoUint32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "mm_compaction_defer_compaction";
    event->group = "compaction";
    event->proto_field_id = 100;
    event->fields.push_back(MakeField("nid", 1, kProtoInt32));
    event->fields.push_back(MakeField("idx", 2, kProtoUint32));
    event->fields.push_back(MakeField("order", 3, kProtoInt32));
    event->fields.push_back(MakeField("considered", 4, kProtoUint32));
    event->fields.push_back(MakeField("defer_shift", 5, kProtoUint32));
    event->fields.push_back(MakeField("order_failed", 6, kProtoInt32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "mm_compaction_defer_reset";
    event->group = "compaction";
    event->proto_field_id = 102;
    event->fields.push_back(MakeField("nid", 1, kProtoInt32));
    event->fields.push_back(MakeField("idx", 2, kProtoUint32));
    event->fields.push_back(MakeField("order", 3, kProtoInt32));
    event->fields.push_back(MakeField("considered", 4, kProtoUint32));
    event->fields.push_back(MakeField("defer_shift", 5, kProtoUint32));
    event->fields.push_back(MakeField("order_failed", 6, kProtoInt32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "mm_compaction_deferred";
    event->group = "compaction";
    event->proto_field_id = 101;
    event->fields.push_back(MakeField("nid", 1, kProtoInt32));
    event->fields.push_back(MakeField("idx", 2, kProtoUint32));
    event->fields.push_back(MakeField("order", 3, kProtoInt32));
    event->fields.push_back(MakeField("considered", 4, kProtoUint32));
    event->fields.push_back(MakeField("defer_shift", 5, kProtoUint32));
    event->fields.push_back(MakeField("order_failed", 6, kProtoInt32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "mm_compaction_end";
    event->group = "compaction";
    event->proto_field_id = 103;
    event->fields.push_back(MakeField("zone_start", 1, kProtoUint64));
    event->fields.push_back(MakeField("migrate_pfn", 2, kProtoUint64));
    event->fields.push_back(MakeField("free_pfn", 3, kProtoUint64));
    event->fields.push_back(MakeField("zone_end", 4, kProtoUint64));
    event->fields.push_back(MakeField("sync", 5, kProtoUint32));
    event->fields.push_back(MakeField("status", 6, kProtoInt32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "mm_compaction_finished";
    event->group = "compaction";
    event->proto_field_id = 104;
    event->fields.push_back(MakeField("nid", 1, kProtoInt32));
    event->fields.push_back(MakeField("idx", 2, kProtoUint32));
    event->fields.push_back(MakeField("order", 3, kProtoInt32));
    event->fields.push_back(MakeField("ret", 4, kProtoInt32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "mm_compaction_isolate_freepages";
    event->group = "compaction";
    event->proto_field_id = 105;
    event->fields.push_back(MakeField("start_pfn", 1, kProtoUint64));
    event->fields.push_back(MakeField("end_pfn", 2, kProtoUint64));
    event->fields.push_back(MakeField("nr_scanned", 3, kProtoUint64));
    event->fields.push_back(MakeField("nr_taken", 4, kProtoUint64));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "mm_compaction_isolate_migratepages";
    event->group = "compaction";
    event->proto_field_id = 106;
    event->fields.push_back(MakeField("start_pfn", 1, kProtoUint64));
    event->fields.push_back(MakeField("end_pfn", 2, kProtoUint64));
    event->fields.push_back(MakeField("nr_scanned", 3, kProtoUint64));
    event->fields.push_back(MakeField("nr_taken", 4, kProtoUint64));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "mm_compaction_kcompactd_sleep";
    event->group = "compaction";
    event->proto_field_id = 107;
    event->fields.push_back(MakeField("nid", 1, kProtoInt32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "mm_compaction_kcompactd_wake";
    event->group = "compaction";
    event->proto_field_id = 108;
    event->fields.push_back(MakeField("nid", 1, kProtoInt32));
    event->fields.push_back(MakeField("order", 2, kProtoInt32));
    event->fields.push_back(MakeField("classzone_idx", 3, kProtoUint32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "mm_compaction_migratepages";
    event->group = "compaction";
    event->proto_field_id = 109;
    event->fields.push_back(MakeField("nr_migrated", 1, kProtoUint64));
    event->fields.push_back(MakeField("nr_failed", 2, kProtoUint64));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "mm_compaction_suitable";
    event->group = "compaction";
    event->proto_field_id = 110;
    event->fields.push_back(MakeField("nid", 1, kProtoInt32));
    event->fields.push_back(MakeField("idx", 2, kProtoUint32));
    event->fields.push_back(MakeField("order", 3, kProtoInt32));
    event->fields.push_back(MakeField("ret", 4, kProtoInt32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "mm_compaction_try_to_compact_pages";
    event->group = "compaction";
    event->proto_field_id = 111;
    event->fields.push_back(MakeField("order", 1, kProtoInt32));
    event->fields.push_back(MakeField("gfp_mask", 2, kProtoUint32));
    event->fields.push_back(MakeField("mode", 3, kProtoUint32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "mm_compaction_wakeup_kcompactd";
    event->group = "compaction";
    event->proto_field_id = 112;
    event->fields.push_back(MakeField("nid", 1, kProtoInt32));
    event->fields.push_back(MakeField("order", 2, kProtoInt32));
    event->fields.push_back(MakeField("classzone_idx", 3, kProtoUint32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "cpufreq_interactive_already";
    event->group = "cpufreq_interactive";
    event->proto_field_id = 5;
    event->fields.push_back(MakeField("cpu_id", 1, kProtoUint64));
    event->fields.push_back(MakeField("load", 2, kProtoUint64));
    event->fields.push_back(MakeField("curtarg", 3, kProtoUint64));
    event->fields.push_back(MakeField("curactual", 4, kProtoUint64));
    event->fields.push_back(MakeField("newtarg", 5, kProtoUint64));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "cpufreq_interactive_boost";
    event->group = "cpufreq_interactive";
    event->proto_field_id = 6;
    event->fields.push_back(MakeField("s", 1, kProtoString));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "cpufreq_interactive_notyet";
    event->group = "cpufreq_interactive";
    event->proto_field_id = 7;
    event->fields.push_back(MakeField("cpu_id", 1, kProtoUint64));
    event->fields.push_back(MakeField("load", 2, kProtoUint64));
    event->fields.push_back(MakeField("curtarg", 3, kProtoUint64));
    event->fields.push_back(MakeField("curactual", 4, kProtoUint64));
    event->fields.push_back(MakeField("newtarg", 5, kProtoUint64));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "cpufreq_interactive_setspeed";
    event->group = "cpufreq_interactive";
    event->proto_field_id = 8;
    event->fields.push_back(MakeField("cpu_id", 1, kProtoUint32));
    event->fields.push_back(MakeField("targfreq", 2, kProtoUint64));
    event->fields.push_back(MakeField("actualfreq", 3, kProtoUint64));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "cpufreq_interactive_target";
    event->group = "cpufreq_interactive";
    event->proto_field_id = 9;
    event->fields.push_back(MakeField("cpu_id", 1, kProtoUint64));
    event->fields.push_back(MakeField("load", 2, kProtoUint64));
    event->fields.push_back(MakeField("curtarg", 3, kProtoUint64));
    event->fields.push_back(MakeField("curactual", 4, kProtoUint64));
    event->fields.push_back(MakeField("newtarg", 5, kProtoUint64));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "cpufreq_interactive_unboost";
    event->group = "cpufreq_interactive";
    event->proto_field_id = 10;
    event->fields.push_back(MakeField("s", 1, kProtoString));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "ext4_da_write_begin";
    event->group = "ext4";
    event->proto_field_id = 41;
    event->fields.push_back(MakeField("dev", 1, kProtoUint32));
    event->fields.push_back(MakeField("ino", 2, kProtoUint64));
    event->fields.push_back(MakeField("pos", 3, kProtoInt64));
    event->fields.push_back(MakeField("len", 4, kProtoUint32));
    event->fields.push_back(MakeField("flags", 5, kProtoUint32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "ext4_da_write_end";
    event->group = "ext4";
    event->proto_field_id = 42;
    event->fields.push_back(MakeField("dev", 1, kProtoUint32));
    event->fields.push_back(MakeField("ino", 2, kProtoUint64));
    event->fields.push_back(MakeField("pos", 3, kProtoInt64));
    event->fields.push_back(MakeField("len", 4, kProtoUint32));
    event->fields.push_back(MakeField("copied", 5, kProtoUint32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "ext4_sync_file_enter";
    event->group = "ext4";
    event->proto_field_id = 43;
    event->fields.push_back(MakeField("dev", 1, kProtoUint32));
    event->fields.push_back(MakeField("ino", 2, kProtoUint64));
    event->fields.push_back(MakeField("parent", 3, kProtoUint64));
    event->fields.push_back(MakeField("datasync", 4, kProtoInt32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "ext4_sync_file_exit";
    event->group = "ext4";
    event->proto_field_id = 44;
    event->fields.push_back(MakeField("dev", 1, kProtoUint32));
    event->fields.push_back(MakeField("ino", 2, kProtoUint64));
    event->fields.push_back(MakeField("ret", 3, kProtoInt32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "mm_filemap_add_to_page_cache";
    event->group = "filemap";
    event->proto_field_id = 97;
    event->fields.push_back(MakeField("pfn", 1, kProtoUint64));
    event->fields.push_back(MakeField("i_ino", 2, kProtoUint64));
    event->fields.push_back(MakeField("index", 3, kProtoUint64));
    event->fields.push_back(MakeField("s_dev", 4, kProtoUint32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "mm_filemap_delete_from_page_cache";
    event->group = "filemap";
    event->proto_field_id = 98;
    event->fields.push_back(MakeField("pfn", 1, kProtoUint64));
    event->fields.push_back(MakeField("i_ino", 2, kProtoUint64));
    event->fields.push_back(MakeField("index", 3, kProtoUint64));
    event->fields.push_back(MakeField("s_dev", 4, kProtoUint32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "print";
    event->group = "ftrace";
    event->proto_field_id = 3;
    event->fields.push_back(MakeField("ip", 1, kProtoUint64));
    event->fields.push_back(MakeField("buf", 2, kProtoString));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "i2c_read";
    event->group = "i2c";
    event->proto_field_id = 27;
    event->fields.push_back(MakeField("adapter_nr", 1, kProtoInt32));
    event->fields.push_back(MakeField("msg_nr", 2, kProtoUint32));
    event->fields.push_back(MakeField("addr", 3, kProtoUint32));
    event->fields.push_back(MakeField("flags", 4, kProtoUint32));
    event->fields.push_back(MakeField("len", 5, kProtoUint32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "i2c_reply";
    event->group = "i2c";
    event->proto_field_id = 30;
    event->fields.push_back(MakeField("adapter_nr", 1, kProtoInt32));
    event->fields.push_back(MakeField("msg_nr", 2, kProtoUint32));
    event->fields.push_back(MakeField("addr", 3, kProtoUint32));
    event->fields.push_back(MakeField("flags", 4, kProtoUint32));
    event->fields.push_back(MakeField("len", 5, kProtoUint32));
    event->fields.push_back(MakeField("buf", 6, kProtoUint32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "i2c_result";
    event->group = "i2c";
    event->proto_field_id = 29;
    event->fields.push_back(MakeField("adapter_nr", 1, kProtoInt32));
    event->fields.push_back(MakeField("nr_msgs", 2, kProtoUint32));
    event->fields.push_back(MakeField("ret", 3, kProtoInt32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "i2c_write";
    event->group = "i2c";
    event->proto_field_id = 28;
    event->fields.push_back(MakeField("adapter_nr", 1, kProtoInt32));
    event->fields.push_back(MakeField("msg_nr", 2, kProtoUint32));
    event->fields.push_back(MakeField("addr", 3, kProtoUint32));
    event->fields.push_back(MakeField("flags", 4, kProtoUint32));
    event->fields.push_back(MakeField("len", 5, kProtoUint32));
    event->fields.push_back(MakeField("buf", 6, kProtoUint32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "smbus_read";
    event->group = "i2c";
    event->proto_field_id = 31;
    event->fields.push_back(MakeField("adapter_nr", 1, kProtoInt32));
    event->fields.push_back(MakeField("flags", 2, kProtoUint32));
    event->fields.push_back(MakeField("addr", 3, kProtoUint32));
    event->fields.push_back(MakeField("command", 4, kProtoUint32));
    event->fields.push_back(MakeField("protocol", 5, kProtoUint32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "smbus_reply";
    event->group = "i2c";
    event->proto_field_id = 34;
    event->fields.push_back(MakeField("adapter_nr", 1, kProtoInt32));
    event->fields.push_back(MakeField("addr", 2, kProtoUint32));
    event->fields.push_back(MakeField("flags", 3, kProtoUint32));
    event->fields.push_back(MakeField("command", 4, kProtoUint32));
    event->fields.push_back(MakeField("len", 5, kProtoUint32));
    event->fields.push_back(MakeField("protocol", 6, kProtoUint32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "smbus_result";
    event->group = "i2c";
    event->proto_field_id = 33;
    event->fields.push_back(MakeField("adapter_nr", 1, kProtoInt32));
    event->fields.push_back(MakeField("addr", 2, kProtoUint32));
    event->fields.push_back(MakeField("flags", 3, kProtoUint32));
    event->fields.push_back(MakeField("read_write", 4, kProtoUint32));
    event->fields.push_back(MakeField("command", 5, kProtoUint32));
    event->fields.push_back(MakeField("res", 6, kProtoInt32));
    event->fields.push_back(MakeField("protocol", 7, kProtoUint32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "smbus_write";
    event->group = "i2c";
    event->proto_field_id = 32;
    event->fields.push_back(MakeField("adapter_nr", 1, kProtoInt32));
    event->fields.push_back(MakeField("addr", 2, kProtoUint32));
    event->fields.push_back(MakeField("flags", 3, kProtoUint32));
    event->fields.push_back(MakeField("command", 4, kProtoUint32));
    event->fields.push_back(MakeField("len", 5, kProtoUint32));
    event->fields.push_back(MakeField("protocol", 6, kProtoUint32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "ipi_entry";
    event->group = "ipi";
    event->proto_field_id = 21;
    event->fields.push_back(MakeField("reason", 1, kProtoString));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "ipi_exit";
    event->group = "ipi";
    event->proto_field_id = 22;
    event->fields.push_back(MakeField("reason", 1, kProtoString));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "ipi_raise";
    event->group = "ipi";
    event->proto_field_id = 23;
    event->fields.push_back(MakeField("target_cpus", 1, kProtoUint32));
    event->fields.push_back(MakeField("reason", 2, kProtoString));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "irq_handler_entry";
    event->group = "irq";
    event->proto_field_id = 36;
    event->fields.push_back(MakeField("irq", 1, kProtoInt32));
    event->fields.push_back(MakeField("name", 2, kProtoString));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "irq_handler_exit";
    event->group = "irq";
    event->proto_field_id = 37;
    event->fields.push_back(MakeField("irq", 1, kProtoInt32));
    event->fields.push_back(MakeField("ret", 2, kProtoInt32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "softirq_entry";
    event->group = "irq";
    event->proto_field_id = 24;
    event->fields.push_back(MakeField("vec", 1, kProtoUint32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "softirq_exit";
    event->group = "irq";
    event->proto_field_id = 25;
    event->fields.push_back(MakeField("vec", 1, kProtoUint32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "softirq_raise";
    event->group = "irq";
    event->proto_field_id = 26;
    event->fields.push_back(MakeField("vec", 1, kProtoUint32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "lowmemory_kill";
    event->group = "lowmemorykiller";
    event->proto_field_id = 35;
    event->fields.push_back(MakeField("comm", 1, kProtoString));
    event->fields.push_back(MakeField("pid", 2, kProtoInt32));
    event->fields.push_back(MakeField("pagecache_size", 3, kProtoInt64));
    event->fields.push_back(MakeField("pagecache_limit", 4, kProtoInt64));
    event->fields.push_back(MakeField("free", 5, kProtoInt64));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "mdp_cmd_kickoff";
    event->group = "mdss";
    event->proto_field_id = 76;
    event->fields.push_back(MakeField("ctl_num", 1, kProtoUint32));
    event->fields.push_back(MakeField("kickoff_cnt", 2, kProtoInt32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "mdp_cmd_pingpong_done";
    event->group = "mdss";
    event->proto_field_id = 81;
    event->fields.push_back(MakeField("ctl_num", 1, kProtoUint32));
    event->fields.push_back(MakeField("intf_num", 2, kProtoUint32));
    event->fields.push_back(MakeField("pp_num", 3, kProtoUint32));
    event->fields.push_back(MakeField("koff_cnt", 4, kProtoInt32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "mdp_cmd_readptr_done";
    event->group = "mdss";
    event->proto_field_id = 85;
    event->fields.push_back(MakeField("ctl_num", 1, kProtoUint32));
    event->fields.push_back(MakeField("koff_cnt", 2, kProtoInt32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "mdp_cmd_release_bw";
    event->group = "mdss";
    event->proto_field_id = 89;
    event->fields.push_back(MakeField("ctl_num", 1, kProtoUint32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "mdp_cmd_wait_pingpong";
    event->group = "mdss";
    event->proto_field_id = 93;
    event->fields.push_back(MakeField("ctl_num", 1, kProtoUint32));
    event->fields.push_back(MakeField("kickoff_cnt", 2, kProtoInt32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "mdp_commit";
    event->group = "mdss";
    event->proto_field_id = 77;
    event->fields.push_back(MakeField("num", 1, kProtoUint32));
    event->fields.push_back(MakeField("play_cnt", 2, kProtoUint32));
    event->fields.push_back(MakeField("clk_rate", 3, kProtoUint32));
    event->fields.push_back(MakeField("bandwidth", 4, kProtoUint64));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "mdp_compare_bw";
    event->group = "mdss";
    event->proto_field_id = 82;
    event->fields.push_back(MakeField("new_ab", 1, kProtoUint64));
    event->fields.push_back(MakeField("new_ib", 2, kProtoUint64));
    event->fields.push_back(MakeField("new_wb", 3, kProtoUint64));
    event->fields.push_back(MakeField("old_ab", 4, kProtoUint64));
    event->fields.push_back(MakeField("old_ib", 5, kProtoUint64));
    event->fields.push_back(MakeField("old_wb", 6, kProtoUint64));
    event->fields.push_back(MakeField("params_changed", 7, kProtoUint32));
    event->fields.push_back(MakeField("update_bw", 8, kProtoUint32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "mdp_misr_crc";
    event->group = "mdss";
    event->proto_field_id = 86;
    event->fields.push_back(MakeField("block_id", 1, kProtoUint32));
    event->fields.push_back(MakeField("vsync_cnt", 2, kProtoUint32));
    event->fields.push_back(MakeField("crc", 3, kProtoUint32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "mdp_mixer_update";
    event->group = "mdss";
    event->proto_field_id = 90;
    event->fields.push_back(MakeField("mixer_num", 1, kProtoUint32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "mdp_perf_prefill_calc";
    event->group = "mdss";
    event->proto_field_id = 94;
    event->fields.push_back(MakeField("pnum", 1, kProtoUint32));
    event->fields.push_back(MakeField("latency_buf", 2, kProtoUint32));
    event->fields.push_back(MakeField("ot", 3, kProtoUint32));
    event->fields.push_back(MakeField("y_buf", 4, kProtoUint32));
    event->fields.push_back(MakeField("y_scaler", 5, kProtoUint32));
    event->fields.push_back(MakeField("pp_lines", 6, kProtoUint32));
    event->fields.push_back(MakeField("pp_bytes", 7, kProtoUint32));
    event->fields.push_back(MakeField("post_sc", 8, kProtoUint32));
    event->fields.push_back(MakeField("fbc_bytes", 9, kProtoUint32));
    event->fields.push_back(MakeField("prefill_bytes", 10, kProtoUint32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "mdp_perf_set_ot";
    event->group = "mdss";
    event->proto_field_id = 78;
    event->fields.push_back(MakeField("pnum", 1, kProtoUint32));
    event->fields.push_back(MakeField("xin_id", 2, kProtoUint32));
    event->fields.push_back(MakeField("rd_lim", 3, kProtoUint32));
    event->fields.push_back(MakeField("is_vbif_rt", 4, kProtoUint32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "mdp_perf_set_panic_luts";
    event->group = "mdss";
    event->proto_field_id = 83;
    event->fields.push_back(MakeField("pnum", 1, kProtoUint32));
    event->fields.push_back(MakeField("fmt", 2, kProtoUint32));
    event->fields.push_back(MakeField("mode", 3, kProtoUint32));
    event->fields.push_back(MakeField("panic_lut", 4, kProtoUint32));
    event->fields.push_back(MakeField("robust_lut", 5, kProtoUint32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "mdp_perf_set_qos_luts";
    event->group = "mdss";
    event->proto_field_id = 87;
    event->fields.push_back(MakeField("pnum", 1, kProtoUint32));
    event->fields.push_back(MakeField("fmt", 2, kProtoUint32));
    event->fields.push_back(MakeField("intf", 3, kProtoUint32));
    event->fields.push_back(MakeField("rot", 4, kProtoUint32));
    event->fields.push_back(MakeField("fl", 5, kProtoUint32));
    event->fields.push_back(MakeField("lut", 6, kProtoUint32));
    event->fields.push_back(MakeField("linear", 7, kProtoUint32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "mdp_perf_set_wm_levels";
    event->group = "mdss";
    event->proto_field_id = 91;
    event->fields.push_back(MakeField("pnum", 1, kProtoUint32));
    event->fields.push_back(MakeField("use_space", 2, kProtoUint32));
    event->fields.push_back(MakeField("priority_bytes", 3, kProtoUint32));
    event->fields.push_back(MakeField("wm0", 4, kProtoUint32));
    event->fields.push_back(MakeField("wm1", 5, kProtoUint32));
    event->fields.push_back(MakeField("wm2", 6, kProtoUint32));
    event->fields.push_back(MakeField("mb_cnt", 7, kProtoUint32));
    event->fields.push_back(MakeField("mb_size", 8, kProtoUint32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "mdp_perf_update_bus";
    event->group = "mdss";
    event->proto_field_id = 95;
    event->fields.push_back(MakeField("client", 1, kProtoInt32));
    event->fields.push_back(MakeField("ab_quota", 2, kProtoUint64));
    event->fields.push_back(MakeField("ib_quota", 3, kProtoUint64));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "mdp_sspp_change";
    event->group = "mdss";
    event->proto_field_id = 79;
    event->fields.push_back(MakeField("num", 1, kProtoUint32));
    event->fields.push_back(MakeField("play_cnt", 2, kProtoUint32));
    event->fields.push_back(MakeField("mixer", 3, kProtoUint32));
    event->fields.push_back(MakeField("stage", 4, kProtoUint32));
    event->fields.push_back(MakeField("flags", 5, kProtoUint32));
    event->fields.push_back(MakeField("format", 6, kProtoUint32));
    event->fields.push_back(MakeField("img_w", 7, kProtoUint32));
    event->fields.push_back(MakeField("img_h", 8, kProtoUint32));
    event->fields.push_back(MakeField("src_x", 9, kProtoUint32));
    event->fields.push_back(MakeField("src_y", 10, kProtoUint32));
    event->fields.push_back(MakeField("src_w", 11, kProtoUint32));
    event->fields.push_back(MakeField("src_h", 12, kProtoUint32));
    event->fields.push_back(MakeField("dst_x", 13, kProtoUint32));
    event->fields.push_back(MakeField("dst_y", 14, kProtoUint32));
    event->fields.push_back(MakeField("dst_w", 15, kProtoUint32));
    event->fields.push_back(MakeField("dst_h", 16, kProtoUint32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "mdp_sspp_set";
    event->group = "mdss";
    event->proto_field_id = 84;
    event->fields.push_back(MakeField("num", 1, kProtoUint32));
    event->fields.push_back(MakeField("play_cnt", 2, kProtoUint32));
    event->fields.push_back(MakeField("mixer", 3, kProtoUint32));
    event->fields.push_back(MakeField("stage", 4, kProtoUint32));
    event->fields.push_back(MakeField("flags", 5, kProtoUint32));
    event->fields.push_back(MakeField("format", 6, kProtoUint32));
    event->fields.push_back(MakeField("img_w", 7, kProtoUint32));
    event->fields.push_back(MakeField("img_h", 8, kProtoUint32));
    event->fields.push_back(MakeField("src_x", 9, kProtoUint32));
    event->fields.push_back(MakeField("src_y", 10, kProtoUint32));
    event->fields.push_back(MakeField("src_w", 11, kProtoUint32));
    event->fields.push_back(MakeField("src_h", 12, kProtoUint32));
    event->fields.push_back(MakeField("dst_x", 13, kProtoUint32));
    event->fields.push_back(MakeField("dst_y", 14, kProtoUint32));
    event->fields.push_back(MakeField("dst_w", 15, kProtoUint32));
    event->fields.push_back(MakeField("dst_h", 16, kProtoUint32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "mdp_trace_counter";
    event->group = "mdss";
    event->proto_field_id = 88;
    event->fields.push_back(MakeField("pid", 1, kProtoInt32));
    event->fields.push_back(MakeField("counter_name", 2, kProtoString));
    event->fields.push_back(MakeField("value", 3, kProtoInt32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "mdp_video_underrun_done";
    event->group = "mdss";
    event->proto_field_id = 92;
    event->fields.push_back(MakeField("ctl_num", 1, kProtoUint32));
    event->fields.push_back(MakeField("underrun_cnt", 2, kProtoUint32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "rotator_bw_ao_as_context";
    event->group = "mdss";
    event->proto_field_id = 96;
    event->fields.push_back(MakeField("state", 1, kProtoUint32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "tracing_mark_write";
    event->group = "mdss";
    event->proto_field_id = 80;
    event->fields.push_back(MakeField("pid", 1, kProtoInt32));
    event->fields.push_back(MakeField("trace_name", 2, kProtoString));
    event->fields.push_back(MakeField("trace_begin", 3, kProtoUint32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "clock_disable";
    event->group = "power";
    event->proto_field_id = 15;
    event->fields.push_back(MakeField("name", 1, kProtoString));
    event->fields.push_back(MakeField("state", 2, kProtoUint64));
    event->fields.push_back(MakeField("cpu_id", 3, kProtoUint64));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "clock_enable";
    event->group = "power";
    event->proto_field_id = 14;
    event->fields.push_back(MakeField("name", 1, kProtoString));
    event->fields.push_back(MakeField("state", 2, kProtoUint64));
    event->fields.push_back(MakeField("cpu_id", 3, kProtoUint64));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "clock_set_rate";
    event->group = "power";
    event->proto_field_id = 16;
    event->fields.push_back(MakeField("name", 1, kProtoString));
    event->fields.push_back(MakeField("state", 2, kProtoUint64));
    event->fields.push_back(MakeField("cpu_id", 3, kProtoUint64));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "cpu_frequency";
    event->group = "power";
    event->proto_field_id = 11;
    event->fields.push_back(MakeField("state", 1, kProtoUint32));
    event->fields.push_back(MakeField("cpu_id", 2, kProtoUint32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "cpu_frequency_limits";
    event->group = "power";
    event->proto_field_id = 12;
    event->fields.push_back(MakeField("min_freq", 1, kProtoUint32));
    event->fields.push_back(MakeField("max_freq", 2, kProtoUint32));
    event->fields.push_back(MakeField("cpu_id", 3, kProtoUint32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "cpu_idle";
    event->group = "power";
    event->proto_field_id = 13;
    event->fields.push_back(MakeField("state", 1, kProtoUint32));
    event->fields.push_back(MakeField("cpu_id", 2, kProtoUint32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "suspend_resume";
    event->group = "power";
    event->proto_field_id = 113;
    event->fields.push_back(MakeField("action", 1, kProtoString));
    event->fields.push_back(MakeField("val", 2, kProtoInt32));
    event->fields.push_back(MakeField("start", 3, kProtoUint32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "regulator_disable";
    event->group = "regulator";
    event->proto_field_id = 60;
    event->fields.push_back(MakeField("name", 1, kProtoString));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "regulator_disable_complete";
    event->group = "regulator";
    event->proto_field_id = 61;
    event->fields.push_back(MakeField("name", 1, kProtoString));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "regulator_enable";
    event->group = "regulator";
    event->proto_field_id = 62;
    event->fields.push_back(MakeField("name", 1, kProtoString));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "regulator_enable_complete";
    event->group = "regulator";
    event->proto_field_id = 63;
    event->fields.push_back(MakeField("name", 1, kProtoString));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "regulator_enable_delay";
    event->group = "regulator";
    event->proto_field_id = 64;
    event->fields.push_back(MakeField("name", 1, kProtoString));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "regulator_set_voltage";
    event->group = "regulator";
    event->proto_field_id = 65;
    event->fields.push_back(MakeField("name", 1, kProtoString));
    event->fields.push_back(MakeField("min", 2, kProtoInt32));
    event->fields.push_back(MakeField("max", 3, kProtoInt32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "regulator_set_voltage_complete";
    event->group = "regulator";
    event->proto_field_id = 66;
    event->fields.push_back(MakeField("name", 1, kProtoString));
    event->fields.push_back(MakeField("val", 2, kProtoUint32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "sched_blocked_reason";
    event->group = "sched";
    event->proto_field_id = 18;
    event->fields.push_back(MakeField("pid", 1, kProtoInt32));
    event->fields.push_back(MakeField("caller", 2, kProtoUint64));
    event->fields.push_back(MakeField("io_wait", 3, kProtoUint32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "sched_cpu_hotplug";
    event->group = "sched";
    event->proto_field_id = 19;
    event->fields.push_back(MakeField("affected_cpu", 1, kProtoInt32));
    event->fields.push_back(MakeField("error", 2, kProtoInt32));
    event->fields.push_back(MakeField("status", 3, kProtoInt32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "sched_switch";
    event->group = "sched";
    event->proto_field_id = 4;
    event->fields.push_back(MakeField("prev_comm", 1, kProtoString));
    event->fields.push_back(MakeField("prev_pid", 2, kProtoInt32));
    event->fields.push_back(MakeField("prev_prio", 3, kProtoInt32));
    event->fields.push_back(MakeField("prev_state", 4, kProtoInt64));
    event->fields.push_back(MakeField("next_comm", 5, kProtoString));
    event->fields.push_back(MakeField("next_pid", 6, kProtoInt32));
    event->fields.push_back(MakeField("next_prio", 7, kProtoInt32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "sched_wakeup";
    event->group = "sched";
    event->proto_field_id = 17;
    event->fields.push_back(MakeField("comm", 1, kProtoString));
    event->fields.push_back(MakeField("pid", 2, kProtoInt32));
    event->fields.push_back(MakeField("prio", 3, kProtoInt32));
    event->fields.push_back(MakeField("success", 4, kProtoInt32));
    event->fields.push_back(MakeField("target_cpu", 5, kProtoInt32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "sched_wakeup_new";
    event->group = "sched";
    event->proto_field_id = 114;
    event->fields.push_back(MakeField("comm", 1, kProtoString));
    event->fields.push_back(MakeField("pid", 2, kProtoInt32));
    event->fields.push_back(MakeField("prio", 3, kProtoInt32));
    event->fields.push_back(MakeField("success", 4, kProtoInt32));
    event->fields.push_back(MakeField("target_cpu", 5, kProtoInt32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "sched_waking";
    event->group = "sched";
    event->proto_field_id = 20;
    event->fields.push_back(MakeField("comm", 1, kProtoString));
    event->fields.push_back(MakeField("pid", 2, kProtoInt32));
    event->fields.push_back(MakeField("prio", 3, kProtoInt32));
    event->fields.push_back(MakeField("success", 4, kProtoInt32));
    event->fields.push_back(MakeField("target_cpu", 5, kProtoInt32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "sync_pt";
    event->group = "sync";
    event->proto_field_id = 38;
    event->fields.push_back(MakeField("timeline", 1, kProtoString));
    event->fields.push_back(MakeField("value", 2, kProtoString));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "sync_timeline";
    event->group = "sync";
    event->proto_field_id = 39;
    event->fields.push_back(MakeField("name", 1, kProtoString));
    event->fields.push_back(MakeField("value", 2, kProtoString));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "sync_wait";
    event->group = "sync";
    event->proto_field_id = 40;
    event->fields.push_back(MakeField("name", 1, kProtoString));
    event->fields.push_back(MakeField("status", 2, kProtoInt32));
    event->fields.push_back(MakeField("begin", 3, kProtoUint32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "mm_vmscan_direct_reclaim_begin";
    event->group = "vmscan";
    event->proto_field_id = 46;
    event->fields.push_back(MakeField("order", 1, kProtoInt32));
    event->fields.push_back(MakeField("may_writepage", 2, kProtoInt32));
    event->fields.push_back(MakeField("gfp_flags", 3, kProtoUint32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "mm_vmscan_direct_reclaim_end";
    event->group = "vmscan";
    event->proto_field_id = 47;
    event->fields.push_back(MakeField("nr_reclaimed", 1, kProtoUint64));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "mm_vmscan_kswapd_sleep";
    event->group = "vmscan";
    event->proto_field_id = 49;
    event->fields.push_back(MakeField("nid", 1, kProtoInt32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "mm_vmscan_kswapd_wake";
    event->group = "vmscan";
    event->proto_field_id = 48;
    event->fields.push_back(MakeField("nid", 1, kProtoInt32));
    event->fields.push_back(MakeField("order", 2, kProtoInt32));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "workqueue_activate_work";
    event->group = "workqueue";
    event->proto_field_id = 56;
    event->fields.push_back(MakeField("work", 1, kProtoUint64));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "workqueue_execute_end";
    event->group = "workqueue";
    event->proto_field_id = 57;
    event->fields.push_back(MakeField("work", 1, kProtoUint64));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "workqueue_execute_start";
    event->group = "workqueue";
    event->proto_field_id = 58;
    event->fields.push_back(MakeField("work", 1, kProtoUint64));
    event->fields.push_back(MakeField("function", 2, kProtoUint64));
  }

  {
    events.emplace_back(Event{});
    Event* event = &events.back();
    event->name = "workqueue_queue_work";
    event->group = "workqueue";
    event->proto_field_id = 59;
    event->fields.push_back(MakeField("work", 1, kProtoUint64));
    event->fields.push_back(MakeField("function", 2, kProtoUint64));
    event->fields.push_back(MakeField("workqueue", 3, kProtoUint64));
    event->fields.push_back(MakeField("req_cpu", 4, kProtoUint32));
    event->fields.push_back(MakeField("cpu", 5, kProtoUint32));
  }

  return events;
}

}  // namespace perfetto
