packet {
  ftrace_events {
    cpu: 4
    event {
      timestamp: 171311335293
      pid: 7663
      print {
        buf: "N|7663|OtherTraces|finalize-uuid-75e4c6d0-d8f6-4f82-fa4b-9e09c5512288\n"
      }
    }
  }
  trusted_uid: 9999
  trusted_packet_sequence_id: 2
  trusted_pid: 1277
  previous_packet_dropped: true
}
packet {
  ftrace_events {
    cpu: 4
    event {
      timestamp: 187198579688
      pid: 7752
      print {
        buf: "N|7752|OtherTraces|finalize-uuid-ad836701-3113-3fb1-be4f-f7731e23fbbf\n"
      }
    }
  }
  trusted_uid: 9999
  trusted_packet_sequence_id: 2
  trusted_pid: 1277
}
packet {
  ftrace_events {
    cpu: 6
    event {
      timestamp: 200857707872
      pid: 7824
      print {
        buf: "N|7824|OtherTraces|finalize-uuid-0de1a010-efa1-a081-2345-969b1186a6ab\n"
      }
    }
  }
  trusted_uid: 9999
  trusted_packet_sequence_id: 2
  trusted_pid: 1277
}
