--
-- Copyright 2026 The Android Open Source Project
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     https://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

-- ------------------------------------------------------------------
-- Mipmap Macro Definitions
-- ------------------------------------------------------------------

-- _mipmap_buckets_table: Generates a table of fixed-duration time buckets(intervals).
-- Each partition (defined by _partition_column) will have its own set of buckets
-- starting from its trace_min_ts. Buckets are assigned a globally unique id.
CREATE PERFETTO MACRO _mipmap_buckets_table(
  -- The source table containing ts, dur, and the partition column.
  _source_table TableOrSubQuery,
  -- The column name to partition the data by.
  _partition_column ColumnName,
  -- The duration of each bucket in nanoseconds.
  _bucket_duration_ns Expr
)
-- Returns a pipeline of (id LONG, <_partition_column>, bucket_index LONG,
-- ts TIMESTAMP, dur DURATION).
RETURNS Pipeline
AS (
  -- Collapse each partition to its full extent [min ts, max ts + dur), then cut
  -- that spanning interval into fixed-width buckets aligned to its own start.
  -- Each piece's offset from the partition start gives its bucket_index.
  FROM $_source_table
  |> AGGREGATE
       MIN(ts) AS span_start,
       MAX(ts + dur) AS span_end
     GROUP BY $_partition_column
  |> INTERVAL SET BOUNDS BEGIN AT span_start END AT span_end
  |> INTERVAL QUANTIZE $_bucket_duration_ns
       ALIGNED TO span_start PER $_partition_column
  |> SELECT
       row_number() OVER (ORDER BY $_partition_column, ts) AS id,
       $_partition_column,
       cast_int!((ts - span_start) / $_bucket_duration_ns) AS bucket_index,
       cast_int!(ts) AS ts,
       cast_int!($_bucket_duration_ns) AS dur
);

-- _mipmap_merged: Merges slices based on dominant overlap within time buckets.
-- This macro intersects source slices with the generated buckets, determines the
-- dominant slice group (by group_hash) in each bucket, and then merges contiguous
-- buckets that share the same dominant group.
CREATE PERFETTO MACRO _mipmap_merged(
  -- The source table containing slices with unique IDs, partition column, ts, dur, and group_hash.
  _source_slices_with_ids TableOrSubQuery,
  -- The buckets table generated by _mipmap_buckets_table.
  _buckets TableOrSubQuery,
  -- The column name used for partitioning.
  _partition_column ColumnName,
  -- The bucket duration in nanoseconds, matching the one used in _mipmap_buckets_table.
  _bucket_duration_ns Expr
)
-- Returns a pipeline of (<_partition_column>, id LONG, ts TIMESTAMP,
-- dur DURATION, group_hash LONG).
RETURNS Pipeline
AS (
  -- Quantize the source slices into the same fixed-width buckets, then resolve
  -- the overlap inside each bucket to its dominant group: the group_hash with the
  -- greatest covered duration (ties broken by earliest original start, then by
  -- group_hash). FLATTEN's ARG_MAX picks that representative per disjoint segment;
  -- a second flatten per bucket index collapses each bucket to one winner.
  FROM $_source_slices_with_ids
  |> INTERVAL QUANTIZE $_bucket_duration_ns PER $_partition_column
  |> EXTEND cast_int!(ts / $_bucket_duration_ns) AS bucket_index
  -- Total covered duration per (bucket, group_hash), keeping a representative id
  -- and the earliest original start for tie-breaking.
  |> AGGREGATE
       SUM(dur) AS group_dur,
       MIN(id) AS source_id,
       MIN(ts) AS min_original_ts
     GROUP BY $_partition_column, bucket_index, group_hash
  -- Dominant group per bucket: max duration, earliest start, smallest group_hash.
  |> WHERE row_number() OVER (
       PARTITION BY $_partition_column, bucket_index
       ORDER BY group_dur DESC, min_original_ts ASC, group_hash ASC
     ) = 1
  -- Re-establish each bucket's interval bounds so consecutive winners can merge.
  |> INTERVAL SET BOUNDS
       BEGIN AT bucket_index * $_bucket_duration_ns
       FOR $_bucket_duration_ns
     PER $_partition_column
  |> INTERVAL MERGE CONSECUTIVE BY group_hash PER $_partition_column
       AGGREGATE MIN(source_id) AS id
  |> SELECT $_partition_column, id, ts, dur, group_hash
  |> ORDER BY ts
);
