// Copyright (C) 2025 Rivos Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Autogenerated by the ProtoZero Rust compiler plugin.
// Invoked by contrib/rust-sdk/tools/gen_rust_protos
// DO NOT EDIT.

use crate::pb_enum;
use crate::pb_msg;
use crate::protos::common::builtin_clock::*;

pb_enum!(ClockBuiltinClocks {
    UNKNOWN: 0,
    REALTIME: 1,
    REALTIME_COARSE: 2,
    MONOTONIC: 3,
    MONOTONIC_COARSE: 4,
    MONOTONIC_RAW: 5,
    BOOTTIME: 6,
    BUILTIN_CLOCK_MAX_ID: 63,
});

pb_msg!(ClockSnapshot {
    clocks: Clock, msg, 1,
    primary_trace_clock: BuiltinClock, enum, 2,
});

pb_msg!(Clock {
    clock_id: u32, primitive, 1,
    timestamp: u64, primitive, 2,
    is_incremental: bool, primitive, 3,
    unit_multiplier_ns: u64, primitive, 4,
});
