#!/usr/bin/env python3
# Copyright (C) 2025 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import argparse
import re
import sys


def main(argv):
  parser = argparse.ArgumentParser()
  parser.add_argument('--input', required=True)
  parser.add_argument('--output', required=True)
  args = parser.parse_args(argv)

  categories = []
  if args.input != 'NONE':
    # Match lines like: categories: "name"
    # Handles variations in spacing
    pattern = re.compile(r'^\s*categories:\s*"([^"]+)"')
    with open(args.input, 'r') as f:
      for line in f:
        match = pattern.match(line)
        if match:
          cat = match.group(1)
          cat = cat.strip()
          if cat not in categories:
            categories.append(cat)

  with open(args.output, 'w') as f:
    f.write('// Autogenerated by gen_categories.py. Do not edit.\n\n')
    f.write('package dev.perfetto.sdk;\n\n')
    f.write('import java.util.List;\n')
    f.write('import java.util.Arrays;\n')
    f.write('import java.util.Collections;\n\n')
    f.write('public final class PerfettoCategories {\n')

    category_names = []
    for cat in categories:
      # Sanitize for Java identifier (simple version)
      category_id = re.sub(r'[^a-zA-Z0-9_]', '_', cat).upper()
      category_variable = f'{category_id}_CATEGORY'
      category_names.append(category_variable)
      f.write(
          f'    public static final PerfettoTrace.Category {category_variable} = '
          f'new PerfettoTrace.Category("{cat}");\n')

    if categories:
      f.write('\n')
      f.write(
          '    public static final List<PerfettoTrace.Category> ALL_CATEGORIES = '
          'Collections.unmodifiableList(Arrays.asList(\n')
      f.write(',\n'.join(f'        {name}' for name in category_names))
      f.write('\n    ));\n')
    else:
      f.write('\n')
      f.write(
          '    public static final List<PerfettoTrace.Category> ALL_CATEGORIES = '
          'Collections.emptyList();\n')

    f.write('}\n')

  return 0


if __name__ == '__main__':
  sys.exit(main(sys.argv[1:]))
