# See go/perfetto-ui-autopush for docs on how this works end-to-end.
# See trigger configs inline YAML in Google Cloud Console > Cloud Build
# for the project "perfetto-ui" (zone: europe-west2).
steps:
- name: europe-docker.pkg.dev/perfetto-ui/builder/perfetto-ui-builder
  args:
  - /ui_builder_entrypoint.sh
  - $BRANCH_NAME
# Timeout = 60 min (last measured time in Jan 2026: 30 min)
timeout: 3600s
options:
  machineType: E2_HIGHCPU_32
