# See go/perfetto-ui-autopush for docs on how this works end-to-end.
# If this file is modified, the inline YAML must be copy-pasted
# FROM: infra/ui.perfetto.dev/cloudbuild.yaml
# TO: TWO trigger configs inline YAML in Google Cloud Console > Cloud Build.
steps:
- name: gcr.io/$PROJECT_ID/perfetto-ui-builder
  args:
  - /ui_builder_entrypoint.sh
  - $BRANCH_NAME
# Timeout = 30 min (last measured time in Feb 2021: 12 min)
timeout: 1800s
options:
  machineType: E2_HIGHCPU_32
