packet {
  clock_snapshot {
    primary_trace_clock: BUILTIN_CLOCK_BOOTTIME
    clocks {
      clock_id: 6
      timestamp: 674770590741767
    }
    clocks {
      clock_id: 2
      timestamp: 1718386902201012395
    }
    clocks {
      clock_id: 4
      timestamp: 517479917684233
    }
    clocks {
      clock_id: 1
      timestamp: 1718386902204523056
    }
    clocks {
      clock_id: 3
      timestamp: 517479921194975
    }
    clocks {
      clock_id: 5
      timestamp: 517479921195099
    }
  }
  trusted_uid: 9999
  trusted_packet_sequence_id: 1
}
packet {
  clock_snapshot {
    primary_trace_clock: BUILTIN_CLOCK_BOOTTIME
    clocks {
      clock_id: 6
      timestamp: 674770590825792
    }
    clocks {
      clock_id: 2
      timestamp: 1718386902201012395
    }
    clocks {
      clock_id: 4
      timestamp: 517479917684233
    }
    clocks {
      clock_id: 1
      timestamp: 1718386902204607000
    }
    clocks {
      clock_id: 3
      timestamp: 517479921278919
    }
    clocks {
      clock_id: 5
      timestamp: 517479921279042
    }
  }
  trusted_uid: 9999
  trusted_packet_sequence_id: 1
}
packet {
  trusted_uid: 9999
  trusted_packet_sequence_id: 1
  synchronization_marker: "\202Gzv\262\215B\272\201\33432mW\240y"
}
packet {
  trusted_uid: 9999
  trusted_packet_sequence_id: 1
  trace_config {
    buffers {
      size_kb: 1000000
      fill_policy: RING_BUFFER
    }
    data_sources {
      config {
        name: "android.input.inputevent"
        android_input_event_config {
          mode: TRACE_MODE_TRACE_ALL
        }
      }
    }
    duration_ms: 10000
    enable_extra_guardrails: false
    statsd_metadata {
    }
    statsd_logging: STATSD_LOGGING_DISABLED
    trace_uuid_msb: 8003899888869335060
    trace_uuid_lsb: -5519492449794714505
  }
}
packet {
  trusted_uid: 9999
  trusted_packet_sequence_id: 1
  trace_uuid {
    lsb: -5519492449794714505
    msb: 8003899888869335060
  }
}
packet {
  system_info {
    tracing_service_version: "Perfetto v45.0 (N/A)"
    timezone_off_mins: -240
    utsname {
      sysname: "Linux"
      version: "#1 SMP PREEMPT Thu May 23 13:08:51 UTC 2024"
      machine: "aarch64"
      release: "5.10.209-android13-4-02835-gce4db2481eb5-ab11882700"
    }
    page_size: 4096
    num_cpus: 8
    android_build_fingerprint: "google/tangorpro/tangorpro:VanillaIceCream/MAIN/eng.prabir.20240606.172326:eng/dev-keys"
    android_sdk_version: 35
  }
  trusted_uid: 9999
  trusted_packet_sequence_id: 1
}
packet {
  timestamp: 674770590804552
  trusted_uid: 9999
  trusted_packet_sequence_id: 1
  service_event {
    tracing_started: true
  }
}
packet {
  timestamp: 674770593089261
  trusted_uid: 9999
  trusted_packet_sequence_id: 1
  service_event {
    all_data_sources_started: true
  }
}
packet {
  timestamp: 674775802354888
  trusted_uid: 9999
  trusted_packet_sequence_id: 1
  service_event {
    all_data_sources_flushed: true
  }
}
packet {
  timestamp: 674775804499013
  trusted_uid: 9999
  trusted_packet_sequence_id: 1
  service_event {
    tracing_disabled: true
  }
}
packet {
  first_packet_on_sequence: true
  timestamp: 517481517002349
  timestamp_clock_id: 3
  winscope_extensions {
    [perfetto.protos.WinscopeExtensionsImpl.android_input_event] {
      dispatcher_motion_event {
        event_id: 330184796
        event_time_nanos: 517481507875000
        down_time_nanos: 517481507875000
        source: 4098
        action: 0
        device_id: 4
        display_id: 0
        classification: 0
        flags: 128
        policy_flags: 1644167168
        cursor_position_x: nan
        cursor_position_y: nan
        meta_state: 0
        pointer {
          pointer_id: 0
          tool_type: 1
          axis_value {
            axis: 0
            value: 431.000000
          }
          axis_value {
            axis: 1
            value: 624.000000
          }
          axis_value {
            axis: 2
            value: 1.324219
          }
          axis_value {
            axis: 3
            value: 0.039273
          }
          axis_value {
            axis: 4
            value: 110.000000
          }
          axis_value {
            axis: 5
            value: 91.000000
          }
          axis_value {
            axis: 6
            value: 110.000000
          }
          axis_value {
            axis: 7
            value: 91.000000
          }
          axis_value {
            axis: 8
            value: 1.120190
          }
        }
      }
    }
  }
  trusted_uid: 1000
  trusted_packet_sequence_id: 2
  trusted_pid: 31778
  previous_packet_dropped: true
}
packet {
  timestamp: 517481517002349
  timestamp_clock_id: 3
  winscope_extensions {
    [perfetto.protos.WinscopeExtensionsImpl.android_input_event] {
      dispatcher_motion_event {
        event_id: 1327679296
        event_time_nanos: 517481507875000
        down_time_nanos: 517481507875000
        source: 4098
        action: 4
        device_id: 4
        display_id: 0
        classification: 0
        flags: 128
        policy_flags: 1644167168
        cursor_position_x: nan
        cursor_position_y: nan
        meta_state: 0
        pointer {
          pointer_id: 0
          tool_type: 1
          axis_value {
            axis: 0
            value: 431.000000
          }
          axis_value {
            axis: 1
            value: 624.000000
          }
          axis_value {
            axis: 2
            value: 1.324219
          }
          axis_value {
            axis: 3
            value: 0.039273
          }
          axis_value {
            axis: 4
            value: 110.000000
          }
          axis_value {
            axis: 5
            value: 91.000000
          }
          axis_value {
            axis: 6
            value: 110.000000
          }
          axis_value {
            axis: 7
            value: 91.000000
          }
          axis_value {
            axis: 8
            value: 1.120190
          }
        }
      }
    }
  }
  trusted_uid: 1000
  trusted_packet_sequence_id: 2
  trusted_pid: 31778
}
packet {
  timestamp: 517481517002349
  timestamp_clock_id: 3
  winscope_extensions {
    [perfetto.protos.WinscopeExtensionsImpl.android_input_event] {
      dispatcher_window_dispatch_event {
        event_id: 1327679296
        vsync_id: 89110
        window_id: 98
        resolved_flags: 128
        dispatched_pointer {
          pointer_id: 0
          x_in_display: 1936.000000
          y_in_display: 431.000000
          axis_value_in_window {
            axis: 0
            value: 1936.000000
          }
          axis_value_in_window {
            axis: 1
            value: -830.000000
          }
          axis_value_in_window {
            axis: 8
            value: -0.450654
          }
        }
      }
    }
  }
  trusted_uid: 1000
  trusted_packet_sequence_id: 2
  trusted_pid: 31778
}
packet {
  timestamp: 517481517002349
  timestamp_clock_id: 3
  winscope_extensions {
    [perfetto.protos.WinscopeExtensionsImpl.android_input_event] {
      dispatcher_window_dispatch_event {
        event_id: 330184796
        vsync_id: 89110
        window_id: 212
        resolved_flags: 128
        dispatched_pointer {
          pointer_id: 0
          x_in_display: 1936.000000
          y_in_display: 431.000000
          axis_value_in_window {
            axis: 0
            value: 1936.000000
          }
          axis_value_in_window {
            axis: 1
            value: 431.000000
          }
          axis_value_in_window {
            axis: 8
            value: -0.450638
          }
        }
      }
    }
  }
  trusted_uid: 1000
  trusted_packet_sequence_id: 2
  trusted_pid: 31778
}
packet {
  timestamp: 517481517002349
  timestamp_clock_id: 3
  winscope_extensions {
    [perfetto.protos.WinscopeExtensionsImpl.android_input_event] {
      dispatcher_window_dispatch_event {
        event_id: 330184796
        vsync_id: 89110
        window_id: 64
        resolved_flags: 131
        dispatched_pointer {
          pointer_id: 0
          x_in_display: 1936.000000
          y_in_display: 431.000000
          axis_value_in_window {
            axis: 0
            value: 1876.363281
          }
          axis_value_in_window {
            axis: 1
            value: 464.545898
          }
          axis_value_in_window {
            axis: 8
            value: -0.450681
          }
        }
      }
    }
  }
  trusted_uid: 1000
  trusted_packet_sequence_id: 2
  trusted_pid: 31778
}
packet {
  timestamp: 517481517002349
  timestamp_clock_id: 3
  winscope_extensions {
    [perfetto.protos.WinscopeExtensionsImpl.android_input_event] {
      dispatcher_window_dispatch_event {
        event_id: 330184796
        vsync_id: 89110
        window_id: 82
        resolved_flags: 128
        dispatched_pointer {
          pointer_id: 0
          x_in_display: 1936.000000
          y_in_display: 431.000000
          axis_value_in_window {
            axis: 0
            value: 1936.000000
          }
          axis_value_in_window {
            axis: 1
            value: 431.000000
          }
          axis_value_in_window {
            axis: 8
            value: -0.450638
          }
        }
      }
    }
  }
  trusted_uid: 1000
  trusted_packet_sequence_id: 2
  trusted_pid: 31778
}
packet {
  timestamp: 517481517002349
  timestamp_clock_id: 3
  winscope_extensions {
    [perfetto.protos.WinscopeExtensionsImpl.android_input_event] {
      dispatcher_window_dispatch_event {
        event_id: 330184796
        vsync_id: 89110
        window_id: 75
        resolved_flags: 128
        dispatched_pointer {
          pointer_id: 0
          x_in_display: 1936.000000
          y_in_display: 431.000000
          axis_value_in_window {
            axis: 0
            value: 1936.000000
          }
          axis_value_in_window {
            axis: 1
            value: 431.000000
          }
          axis_value_in_window {
            axis: 8
            value: -0.450638
          }
        }
      }
    }
  }
  trusted_uid: 1000
  trusted_packet_sequence_id: 2
  trusted_pid: 31778
}
packet {
  timestamp: 517481517002349
  timestamp_clock_id: 3
  winscope_extensions {
    [perfetto.protos.WinscopeExtensionsImpl.android_input_event] {
      dispatcher_window_dispatch_event {
        event_id: 330184796
        vsync_id: 0
        window_id: 0
        resolved_flags: 128
        dispatched_pointer {
          pointer_id: 0
          x_in_display: 1936.000000
          y_in_display: 431.000000
          axis_value_in_window {
            axis: 0
            value: 1936.000000
          }
          axis_value_in_window {
            axis: 1
            value: 431.000000
          }
          axis_value_in_window {
            axis: 8
            value: -0.450638
          }
        }
      }
    }
  }
  trusted_uid: 1000
  trusted_packet_sequence_id: 2
  trusted_pid: 31778
}
packet {
  timestamp: 517481538183257
  timestamp_clock_id: 3
  winscope_extensions {
    [perfetto.protos.WinscopeExtensionsImpl.android_input_event] {
      dispatcher_motion_event {
        event_id: 557261353
        event_time_nanos: 517481533371000
        down_time_nanos: 517481507875000
        source: 4098
        action: 2
        device_id: 4
        display_id: 0
        classification: 1
        flags: 128
        policy_flags: 1644167168
        cursor_position_x: nan
        cursor_position_y: nan
        meta_state: 0
        pointer {
          pointer_id: 0
          tool_type: 1
          axis_value {
            axis: 0
            value: 431.000000
          }
          axis_value {
            axis: 1
            value: 624.000000
          }
          axis_value {
            axis: 2
            value: 1.320312
          }
          axis_value {
            axis: 3
            value: 0.039273
          }
          axis_value {
            axis: 4
            value: 110.000000
          }
          axis_value {
            axis: 5
            value: 91.000000
          }
          axis_value {
            axis: 6
            value: 110.000000
          }
          axis_value {
            axis: 7
            value: 91.000000
          }
          axis_value {
            axis: 8
            value: 1.120190
          }
        }
      }
    }
  }
  trusted_uid: 1000
  trusted_packet_sequence_id: 2
  trusted_pid: 31778
}
packet {
  timestamp: 517481538183257
  timestamp_clock_id: 3
  winscope_extensions {
    [perfetto.protos.WinscopeExtensionsImpl.android_input_event] {
      dispatcher_window_dispatch_event {
        event_id: 557261353
        vsync_id: 89110
        window_id: 212
        resolved_flags: 128
        dispatched_pointer {
          pointer_id: 0
          x_in_display: 1936.000000
          y_in_display: 431.000000
          axis_value_in_window {
            axis: 0
            value: 1936.000000
          }
          axis_value_in_window {
            axis: 1
            value: 431.000000
          }
          axis_value_in_window {
            axis: 8
            value: -0.450638
          }
        }
      }
    }
  }
  trusted_uid: 1000
  trusted_packet_sequence_id: 2
  trusted_pid: 31778
}
packet {
  timestamp: 517481538183257
  timestamp_clock_id: 3
  winscope_extensions {
    [perfetto.protos.WinscopeExtensionsImpl.android_input_event] {
      dispatcher_window_dispatch_event {
        event_id: 557261353
        vsync_id: 89110
        window_id: 64
        resolved_flags: 131
        dispatched_pointer {
          pointer_id: 0
          x_in_display: 1936.000000
          y_in_display: 431.000000
          axis_value_in_window {
            axis: 0
            value: 1876.363281
          }
          axis_value_in_window {
            axis: 1
            value: 464.545898
          }
          axis_value_in_window {
            axis: 8
            value: -0.450681
          }
        }
      }
    }
  }
  trusted_uid: 1000
  trusted_packet_sequence_id: 2
  trusted_pid: 31778
}
packet {
  timestamp: 517481538183257
  timestamp_clock_id: 3
  winscope_extensions {
    [perfetto.protos.WinscopeExtensionsImpl.android_input_event] {
      dispatcher_window_dispatch_event {
        event_id: 557261353
        vsync_id: 89110
        window_id: 82
        resolved_flags: 128
        dispatched_pointer {
          pointer_id: 0
          x_in_display: 1936.000000
          y_in_display: 431.000000
          axis_value_in_window {
            axis: 0
            value: 1936.000000
          }
          axis_value_in_window {
            axis: 1
            value: 431.000000
          }
          axis_value_in_window {
            axis: 8
            value: -0.450638
          }
        }
      }
    }
  }
  trusted_uid: 1000
  trusted_packet_sequence_id: 2
  trusted_pid: 31778
}
packet {
  timestamp: 517481538183257
  timestamp_clock_id: 3
  winscope_extensions {
    [perfetto.protos.WinscopeExtensionsImpl.android_input_event] {
      dispatcher_window_dispatch_event {
        event_id: 557261353
        vsync_id: 89110
        window_id: 75
        resolved_flags: 128
        dispatched_pointer {
          pointer_id: 0
          x_in_display: 1936.000000
          y_in_display: 431.000000
          axis_value_in_window {
            axis: 0
            value: 1936.000000
          }
          axis_value_in_window {
            axis: 1
            value: 431.000000
          }
          axis_value_in_window {
            axis: 8
            value: -0.450638
          }
        }
      }
    }
  }
  trusted_uid: 1000
  trusted_packet_sequence_id: 2
  trusted_pid: 31778
}
packet {
  timestamp: 517481538183257
  timestamp_clock_id: 3
  winscope_extensions {
    [perfetto.protos.WinscopeExtensionsImpl.android_input_event] {
      dispatcher_window_dispatch_event {
        event_id: 557261353
        vsync_id: 0
        window_id: 0
        resolved_flags: 128
        dispatched_pointer {
          pointer_id: 0
          x_in_display: 1936.000000
          y_in_display: 431.000000
          axis_value_in_window {
            axis: 0
            value: 1936.000000
          }
          axis_value_in_window {
            axis: 1
            value: 431.000000
          }
          axis_value_in_window {
            axis: 8
            value: -0.450638
          }
        }
      }
    }
  }
  trusted_uid: 1000
  trusted_packet_sequence_id: 2
  trusted_pid: 31778
}
packet {
  timestamp: 517481543976511
  timestamp_clock_id: 3
  winscope_extensions {
    [perfetto.protos.WinscopeExtensionsImpl.android_input_event] {
      dispatcher_motion_event {
        event_id: 106022695
        event_time_nanos: 517481540876000
        down_time_nanos: 517481507875000
        source: 4098
        action: 2
        device_id: 4
        display_id: 0
        classification: 1
        flags: 128
        policy_flags: 1644167168
        cursor_position_x: nan
        cursor_position_y: nan
        meta_state: 0
        pointer {
          pointer_id: 0
          tool_type: 1
          axis_value {
            axis: 0
            value: 431.000000
          }
          axis_value {
            axis: 1
            value: 624.000000
          }
          axis_value {
            axis: 2
            value: 1.105469
          }
          axis_value {
            axis: 3
            value: 0.035952
          }
          axis_value {
            axis: 4
            value: 101.000000
          }
          axis_value {
            axis: 5
            value: 83.000000
          }
          axis_value {
            axis: 6
            value: 101.000000
          }
          axis_value {
            axis: 7
            value: 83.000000
          }
          axis_value {
            axis: 8
            value: 1.175413
          }
        }
      }
    }
  }
  trusted_uid: 1000
  trusted_packet_sequence_id: 2
  trusted_pid: 31778
}
packet {
  timestamp: 517481543976511
  timestamp_clock_id: 3
  winscope_extensions {
    [perfetto.protos.WinscopeExtensionsImpl.android_input_event] {
      dispatcher_window_dispatch_event {
        event_id: 106022695
        vsync_id: 89110
        window_id: 212
        resolved_flags: 128
        dispatched_pointer {
          pointer_id: 0
          x_in_display: 1936.000000
          y_in_display: 431.000000
          axis_value_in_window {
            axis: 0
            value: 1936.000000
          }
          axis_value_in_window {
            axis: 1
            value: 431.000000
          }
          axis_value_in_window {
            axis: 8
            value: -0.395468
          }
        }
      }
    }
  }
  trusted_uid: 1000
  trusted_packet_sequence_id: 2
  trusted_pid: 31778
}
packet {
  timestamp: 517481543976511
  timestamp_clock_id: 3
  winscope_extensions {
    [perfetto.protos.WinscopeExtensionsImpl.android_input_event] {
      dispatcher_window_dispatch_event {
        event_id: 106022695
        vsync_id: 89110
        window_id: 64
        resolved_flags: 131
        dispatched_pointer {
          pointer_id: 0
          x_in_display: 1936.000000
          y_in_display: 431.000000
          axis_value_in_window {
            axis: 0
            value: 1876.363281
          }
          axis_value_in_window {
            axis: 1
            value: 464.545898
          }
          axis_value_in_window {
            axis: 8
            value: -0.395334
          }
        }
      }
    }
  }
  trusted_uid: 1000
  trusted_packet_sequence_id: 2
  trusted_pid: 31778
}
packet {
  timestamp: 517481543976511
  timestamp_clock_id: 3
  winscope_extensions {
    [perfetto.protos.WinscopeExtensionsImpl.android_input_event] {
      dispatcher_window_dispatch_event {
        event_id: 106022695
        vsync_id: 89110
        window_id: 82
        resolved_flags: 128
        dispatched_pointer {
          pointer_id: 0
          x_in_display: 1936.000000
          y_in_display: 431.000000
          axis_value_in_window {
            axis: 0
            value: 1936.000000
          }
          axis_value_in_window {
            axis: 1
            value: 431.000000
          }
          axis_value_in_window {
            axis: 8
            value: -0.395468
          }
        }
      }
    }
  }
  trusted_uid: 1000
  trusted_packet_sequence_id: 2
  trusted_pid: 31778
}
packet {
  timestamp: 517481543976511
  timestamp_clock_id: 3
  winscope_extensions {
    [perfetto.protos.WinscopeExtensionsImpl.android_input_event] {
      dispatcher_window_dispatch_event {
        event_id: 106022695
        vsync_id: 89110
        window_id: 75
        resolved_flags: 128
        dispatched_pointer {
          pointer_id: 0
          x_in_display: 1936.000000
          y_in_display: 431.000000
          axis_value_in_window {
            axis: 0
            value: 1936.000000
          }
          axis_value_in_window {
            axis: 1
            value: 431.000000
          }
          axis_value_in_window {
            axis: 8
            value: -0.395468
          }
        }
      }
    }
  }
  trusted_uid: 1000
  trusted_packet_sequence_id: 2
  trusted_pid: 31778
}
packet {
  timestamp: 517481543976511
  timestamp_clock_id: 3
  winscope_extensions {
    [perfetto.protos.WinscopeExtensionsImpl.android_input_event] {
      dispatcher_window_dispatch_event {
        event_id: 106022695
        vsync_id: 0
        window_id: 0
        resolved_flags: 128
        dispatched_pointer {
          pointer_id: 0
          x_in_display: 1936.000000
          y_in_display: 431.000000
          axis_value_in_window {
            axis: 0
            value: 1936.000000
          }
          axis_value_in_window {
            axis: 1
            value: 431.000000
          }
          axis_value_in_window {
            axis: 8
            value: -0.395468
          }
        }
      }
    }
  }
  trusted_uid: 1000
  trusted_packet_sequence_id: 2
  trusted_pid: 31778
}
packet {
  timestamp: 517481553353301
  timestamp_clock_id: 3
  winscope_extensions {
    [perfetto.protos.WinscopeExtensionsImpl.android_input_event] {
      dispatcher_motion_event {
        event_id: 313395000
        event_time_nanos: 517481550152000
        down_time_nanos: 517481507875000
        source: 4098
        action: 2
        device_id: 4
        display_id: 0
        classification: 1
        flags: 128
        policy_flags: 1644167168
        cursor_position_x: nan
        cursor_position_y: nan
        meta_state: 0
        pointer {
          pointer_id: 0
          tool_type: 1
          axis_value {
            axis: 0
            value: 431.000000
          }
          axis_value {
            axis: 1
            value: 624.000000
          }
          axis_value {
            axis: 2
            value: 0.113281
          }
          axis_value {
            axis: 3
            value: 0.011333
          }
          axis_value {
            axis: 4
            value: 29.000000
          }
          axis_value {
            axis: 5
            value: 29.000000
          }
          axis_value {
            axis: 6
            value: 29.000000
          }
          axis_value {
            axis: 7
            value: 29.000000
          }
          axis_value {
            axis: 8
            value: 1.175413
          }
        }
      }
    }
  }
  trusted_uid: 1000
  trusted_packet_sequence_id: 2
  trusted_pid: 31778
}
packet {
  timestamp: 517481553353301
  timestamp_clock_id: 3
  winscope_extensions {
    [perfetto.protos.WinscopeExtensionsImpl.android_input_event] {
      dispatcher_window_dispatch_event {
        event_id: 313395000
        vsync_id: 89110
        window_id: 212
        resolved_flags: 128
        dispatched_pointer {
          pointer_id: 0
          x_in_display: 1936.000000
          y_in_display: 431.000000
          axis_value_in_window {
            axis: 0
            value: 1936.000000
          }
          axis_value_in_window {
            axis: 1
            value: 431.000000
          }
          axis_value_in_window {
            axis: 8
            value: -0.395468
          }
        }
      }
    }
  }
  trusted_uid: 1000
  trusted_packet_sequence_id: 2
  trusted_pid: 31778
}
packet {
  timestamp: 517481553353301
  timestamp_clock_id: 3
  winscope_extensions {
    [perfetto.protos.WinscopeExtensionsImpl.android_input_event] {
      dispatcher_window_dispatch_event {
        event_id: 313395000
        vsync_id: 89110
        window_id: 64
        resolved_flags: 131
        dispatched_pointer {
          pointer_id: 0
          x_in_display: 1936.000000
          y_in_display: 431.000000
          axis_value_in_window {
            axis: 0
            value: 1876.363281
          }
          axis_value_in_window {
            axis: 1
            value: 464.545898
          }
          axis_value_in_window {
            axis: 8
            value: -0.395334
          }
        }
      }
    }
  }
  trusted_uid: 1000
  trusted_packet_sequence_id: 2
  trusted_pid: 31778
}
packet {
  timestamp: 517481553353301
  timestamp_clock_id: 3
  winscope_extensions {
    [perfetto.protos.WinscopeExtensionsImpl.android_input_event] {
      dispatcher_window_dispatch_event {
        event_id: 313395000
        vsync_id: 89110
        window_id: 82
        resolved_flags: 128
        dispatched_pointer {
          pointer_id: 0
          x_in_display: 1936.000000
          y_in_display: 431.000000
          axis_value_in_window {
            axis: 0
            value: 1936.000000
          }
          axis_value_in_window {
            axis: 1
            value: 431.000000
          }
          axis_value_in_window {
            axis: 8
            value: -0.395468
          }
        }
      }
    }
  }
  trusted_uid: 1000
  trusted_packet_sequence_id: 2
  trusted_pid: 31778
}
packet {
  timestamp: 517481553353301
  timestamp_clock_id: 3
  winscope_extensions {
    [perfetto.protos.WinscopeExtensionsImpl.android_input_event] {
      dispatcher_window_dispatch_event {
        event_id: 313395000
        vsync_id: 89110
        window_id: 75
        resolved_flags: 128
        dispatched_pointer {
          pointer_id: 0
          x_in_display: 1936.000000
          y_in_display: 431.000000
          axis_value_in_window {
            axis: 0
            value: 1936.000000
          }
          axis_value_in_window {
            axis: 1
            value: 431.000000
          }
          axis_value_in_window {
            axis: 8
            value: -0.395468
          }
        }
      }
    }
  }
  trusted_uid: 1000
  trusted_packet_sequence_id: 2
  trusted_pid: 31778
}
packet {
  timestamp: 517481553353301
  timestamp_clock_id: 3
  winscope_extensions {
    [perfetto.protos.WinscopeExtensionsImpl.android_input_event] {
      dispatcher_window_dispatch_event {
        event_id: 313395000
        vsync_id: 0
        window_id: 0
        resolved_flags: 128
        dispatched_pointer {
          pointer_id: 0
          x_in_display: 1936.000000
          y_in_display: 431.000000
          axis_value_in_window {
            axis: 0
            value: 1936.000000
          }
          axis_value_in_window {
            axis: 1
            value: 431.000000
          }
          axis_value_in_window {
            axis: 8
            value: -0.395468
          }
        }
      }
    }
  }
  trusted_uid: 1000
  trusted_packet_sequence_id: 2
  trusted_pid: 31778
}
packet {
  timestamp: 517481558399200
  timestamp_clock_id: 3
  winscope_extensions {
    [perfetto.protos.WinscopeExtensionsImpl.android_input_event] {
      dispatcher_motion_event {
        event_id: 436499943
        event_time_nanos: 517481557012000
        down_time_nanos: 517481507875000
        source: 4098
        action: 1
        device_id: 4
        display_id: 0
        classification: 1
        flags: 128
        policy_flags: 1644167168
        cursor_position_x: nan
        cursor_position_y: nan
        meta_state: 0
        pointer {
          pointer_id: 0
          tool_type: 1
          axis_value {
            axis: 0
            value: 431.000000
          }
          axis_value {
            axis: 1
            value: 624.000000
          }
          axis_value {
            axis: 2
            value: 0.113281
          }
          axis_value {
            axis: 3
            value: 0.011333
          }
          axis_value {
            axis: 4
            value: 29.000000
          }
          axis_value {
            axis: 5
            value: 29.000000
          }
          axis_value {
            axis: 6
            value: 29.000000
          }
          axis_value {
            axis: 7
            value: 29.000000
          }
          axis_value {
            axis: 8
            value: 1.175413
          }
        }
      }
    }
  }
  trusted_uid: 1000
  trusted_packet_sequence_id: 2
  trusted_pid: 31778
}
packet {
  timestamp: 517481558399200
  timestamp_clock_id: 3
  winscope_extensions {
    [perfetto.protos.WinscopeExtensionsImpl.android_input_event] {
      dispatcher_window_dispatch_event {
        event_id: 436499943
        vsync_id: 89110
        window_id: 212
        resolved_flags: 128
        dispatched_pointer {
          pointer_id: 0
          x_in_display: 1936.000000
          y_in_display: 431.000000
          axis_value_in_window {
            axis: 0
            value: 1936.000000
          }
          axis_value_in_window {
            axis: 1
            value: 431.000000
          }
          axis_value_in_window {
            axis: 8
            value: -0.395468
          }
        }
      }
    }
  }
  trusted_uid: 1000
  trusted_packet_sequence_id: 2
  trusted_pid: 31778
}
packet {
  timestamp: 517481558399200
  timestamp_clock_id: 3
  winscope_extensions {
    [perfetto.protos.WinscopeExtensionsImpl.android_input_event] {
      dispatcher_window_dispatch_event {
        event_id: 436499943
        vsync_id: 89110
        window_id: 64
        resolved_flags: 131
        dispatched_pointer {
          pointer_id: 0
          x_in_display: 1936.000000
          y_in_display: 431.000000
          axis_value_in_window {
            axis: 0
            value: 1876.363281
          }
          axis_value_in_window {
            axis: 1
            value: 464.545898
          }
          axis_value_in_window {
            axis: 8
            value: -0.395334
          }
        }
      }
    }
  }
  trusted_uid: 1000
  trusted_packet_sequence_id: 2
  trusted_pid: 31778
}
packet {
  timestamp: 517481558399200
  timestamp_clock_id: 3
  winscope_extensions {
    [perfetto.protos.WinscopeExtensionsImpl.android_input_event] {
      dispatcher_window_dispatch_event {
        event_id: 436499943
        vsync_id: 89110
        window_id: 82
        resolved_flags: 128
        dispatched_pointer {
          pointer_id: 0
          x_in_display: 1936.000000
          y_in_display: 431.000000
          axis_value_in_window {
            axis: 0
            value: 1936.000000
          }
          axis_value_in_window {
            axis: 1
            value: 431.000000
          }
          axis_value_in_window {
            axis: 8
            value: -0.395468
          }
        }
      }
    }
  }
  trusted_uid: 1000
  trusted_packet_sequence_id: 2
  trusted_pid: 31778
}
packet {
  timestamp: 517481558399200
  timestamp_clock_id: 3
  winscope_extensions {
    [perfetto.protos.WinscopeExtensionsImpl.android_input_event] {
      dispatcher_window_dispatch_event {
        event_id: 436499943
        vsync_id: 89110
        window_id: 75
        resolved_flags: 128
        dispatched_pointer {
          pointer_id: 0
          x_in_display: 1936.000000
          y_in_display: 431.000000
          axis_value_in_window {
            axis: 0
            value: 1936.000000
          }
          axis_value_in_window {
            axis: 1
            value: 431.000000
          }
          axis_value_in_window {
            axis: 8
            value: -0.395468
          }
        }
      }
    }
  }
  trusted_uid: 1000
  trusted_packet_sequence_id: 2
  trusted_pid: 31778
}
packet {
  timestamp: 517481558399200
  timestamp_clock_id: 3
  winscope_extensions {
    [perfetto.protos.WinscopeExtensionsImpl.android_input_event] {
      dispatcher_window_dispatch_event {
        event_id: 436499943
        vsync_id: 0
        window_id: 0
        resolved_flags: 128
        dispatched_pointer {
          pointer_id: 0
          x_in_display: 1936.000000
          y_in_display: 431.000000
          axis_value_in_window {
            axis: 0
            value: 1936.000000
          }
          axis_value_in_window {
            axis: 1
            value: 431.000000
          }
          axis_value_in_window {
            axis: 8
            value: -0.395468
          }
        }
      }
    }
  }
  trusted_uid: 1000
  trusted_packet_sequence_id: 2
  trusted_pid: 31778
}
packet {
  timestamp: 517482831698151
  timestamp_clock_id: 3
  winscope_extensions {
    [perfetto.protos.WinscopeExtensionsImpl.android_input_event] {
      dispatcher_key_event {
        event_id: 759309047
        event_time_nanos: 517482680619000
        down_time_nanos: 517482680619000
        source: 257
        action: 0
        device_id: 2
        display_id: -1
        repeat_count: 0
        flags: 8
        policy_flags: 1644167168
        key_code: 24
        scan_code: 115
        meta_state: 0
      }
    }
  }
  trusted_uid: 1000
  trusted_packet_sequence_id: 2
  trusted_pid: 31778
}
packet {
  timestamp: 517482831698151
  timestamp_clock_id: 3
  winscope_extensions {
    [perfetto.protos.WinscopeExtensionsImpl.android_input_event] {
      dispatcher_window_dispatch_event {
        event_id: 759309047
        vsync_id: 89110
        window_id: 212
        resolved_flags: 8
      }
    }
  }
  trusted_uid: 1000
  trusted_packet_sequence_id: 2
  trusted_pid: 31778
}
packet {
  timestamp: 517482831698151
  timestamp_clock_id: 3
  winscope_extensions {
    [perfetto.protos.WinscopeExtensionsImpl.android_input_event] {
      dispatcher_window_dispatch_event {
        event_id: 759309047
        vsync_id: 0
        window_id: 0
        resolved_flags: 8
      }
    }
  }
  trusted_uid: 1000
  trusted_packet_sequence_id: 2
  trusted_pid: 31778
}
packet {
  timestamp: 517482839729238
  timestamp_clock_id: 3
  winscope_extensions {
    [perfetto.protos.WinscopeExtensionsImpl.android_input_event] {
      dispatcher_key_event {
        event_id: 894093732
        event_time_nanos: 517482832173000
        down_time_nanos: 517482680619000
        source: 257
        action: 1
        device_id: 2
        display_id: -1
        repeat_count: 0
        flags: 8
        policy_flags: 1644167168
        key_code: 24
        scan_code: 115
        meta_state: 0
      }
    }
  }
  trusted_uid: 1000
  trusted_packet_sequence_id: 2
  trusted_pid: 31778
}
packet {
  timestamp: 517482839729238
  timestamp_clock_id: 3
  winscope_extensions {
    [perfetto.protos.WinscopeExtensionsImpl.android_input_event] {
      dispatcher_window_dispatch_event {
        event_id: 894093732
        vsync_id: 89110
        window_id: 212
        resolved_flags: 8
      }
    }
  }
  trusted_uid: 1000
  trusted_packet_sequence_id: 2
  trusted_pid: 31778
}
packet {
  timestamp: 517482839729238
  timestamp_clock_id: 3
  winscope_extensions {
    [perfetto.protos.WinscopeExtensionsImpl.android_input_event] {
      dispatcher_window_dispatch_event {
        event_id: 894093732
        vsync_id: 0
        window_id: 0
        resolved_flags: 8
      }
    }
  }
  trusted_uid: 1000
  trusted_packet_sequence_id: 2
  trusted_pid: 31778
}
packet {
  timestamp: 674775805961781
  trusted_uid: 9999
  trusted_packet_sequence_id: 1
  service_event {
    read_tracing_buffers_completed: true
  }
}
packet {
  trusted_uid: 9999
  trusted_packet_sequence_id: 1
  trace_stats {
    buffer_stats {
      buffer_size: 1024000000
      bytes_written: 4096
      chunks_written: 1
    }
    producers_connected: 18
    producers_seen: 838
    data_sources_registered: 51
    data_sources_seen: 197
    tracing_sessions: 2
    total_buffers: 4
    chunks_discarded: 78
    patches_discarded: 0
    invalid_packets: 0
    flushes_requested: 1
    flushes_succeeded: 1
    flushes_failed: 0
    final_flush_outcome: FINAL_FLUSH_UNSPECIFIED
  }
}