# Copyright (C) 2026 The Android Open Source Project
# SPDX-License-Identifier: Apache-2.0
import("../../gn/perfetto.gni")

executable("pipeline_benchmark_runner") {
  testonly = true
  sources = [
    "perfetto_runner.cc",
    "protocol.h",
  ]
  defines = [ "PIPELINE_BENCHMARK_IS_DEBUG=$is_debug" ]
  deps = [
    "../../gn:default_deps",
    "../../gn:sqlite",
    "../../src/base",
    "../../src/trace_processor/containers",
    "../../src/trace_processor/perfetto_sql/engine",
    "../../src/trace_processor/sqlite",
  ]
}
