packet {
  timestamp: 1
  incremental_state_cleared: true
  trusted_packet_sequence_id: 1
  track_event {
    type: TYPE_INSTANT
    name: "ActiveProcesses"
    chrome_active_processes {
      pid: 10
      pid: 100
      pid: 1000
    }
  }
}
packet {
  timestamp: 1
  trusted_packet_sequence_id: 2
  track_descriptor {
    uuid: 1
    process {
      pid: 10
    }
    parent_uuid: 0
  }
}
packet {
  timestamp: 1000000000
  trusted_packet_sequence_id: 3
  track_descriptor {
    uuid: 2
    process {
      pid: 100
    }
    parent_uuid: 0
  }
}