packet {
  timestamp: 0
  incremental_state_cleared: true
  trusted_packet_sequence_id: 1
  track_descriptor {
    uuid: 12345
    thread {
      pid: 123
      tid: 345
    }
    parent_uuid: 0
    chrome_thread {
      thread_type: THREAD_POOL_FG_WORKER
    }
  }
}

packet {
  trusted_packet_sequence_id: 1
  timestamp: 0
  incremental_state_cleared: true
  track_event {
    track_uuid: 12345
    categories: "cat1"
    type: 3
    name: "name1"
    [perfetto.protos.ChromeTrackEvent.android_view_dump] {
      activity {
        name: "A"
        view {
          class_name: "abc"
        },
        view {
          class_name: "def"
        },
        view {
          class_name: "ghi"
        }
      }
      activity {
        name: "B"
        view {
          class_name: "jkl"
        }
      }
    }
  }
}
