packet {
  timestamp: 0
  incremental_state_cleared: true
  trusted_packet_sequence_id: 1
  track_descriptor {
    uuid: 12345
    thread {
      pid: 123
      tid: 345
    }
    parent_uuid: 0
    chrome_thread {
      thread_type: THREAD_POOL_FG_WORKER
    }
  }
}

# Slice begin with mojo arg
packet {
  trusted_packet_sequence_id: 1
  timestamp: 10
  track_event {
    track_uuid: 12345
    categories: "cat1"
    type: TYPE_INSTANT
    name: "slice1"
    log_message {
        body_iid: 1
        source_location_iid: 3
    }
  }
  interned_data {
    log_message_body {
        iid: 1
        body: "log message"
    }
    source_locations {
        iid: 3
        function_name: "func"
        file_name: "foo.cc"
        line_number: 123
    }
  }
}