#!/usr/bin/env python3
# Copyright (C) 2021 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import argparse
import os
import sys

ROOT_DIR = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
sys.path.insert(0, os.path.join(ROOT_DIR, 'python'))

from perfetto.common.open_trace_server import *


class ANSI:
  END = '\033[0m'
  BOLD = '\033[1m'
  RED = '\033[91m'
  BLACK = '\033[30m'
  BLUE = '\033[94m'
  BG_YELLOW = '\033[43m'
  BG_BLUE = '\033[44m'


def prt(msg, colors=ANSI.END):
  print(colors + msg + ANSI.END)


def main():
  examples = '\n'.join([
      ANSI.BOLD + 'Examples:' + ANSI.END,
      '  tools/open_trace_in_ui trace.pftrace',
  ])
  parser = argparse.ArgumentParser(
      epilog=examples, formatter_class=argparse.RawTextHelpFormatter)

  parser.add_argument('positional_trace', metavar='trace', nargs='?')
  parser.add_argument(
      '-n', '--no-open-browser', action='store_true', default=False)
  parser.add_argument(
      '--remote-browser',
      action='store_true',
      default=False,
      help='The browser runs on another machine (e.g. this is an ssh session). '
      'Serves the trace on all interfaces and prints a URL that hands it to '
      'the UI, so no port forwarding is needed')
  origin_group = parser.add_mutually_exclusive_group()
  origin_group.add_argument('--origin', default='https://ui.perfetto.dev')
  origin_group.add_argument(
      '--dev-server',
      action='store_true',
      default=False,
      help='Open the trace in the locally hosted devserver. Shorthand for "--origin http://localhost:10000"'
  )
  parser.add_argument(
      '-i', '--trace', help='input filename (overrides positional argument)')

  args = parser.parse_args()
  open_browser = not args.no_open_browser

  trace_file = None
  if args.positional_trace is not None:
    trace_file = args.positional_trace
  if args.trace is not None:
    trace_file = args.trace

  if trace_file is None:
    prt('Please specify trace file name', ANSI.RED)
    sys.exit(1)
  elif not os.path.exists(trace_file):
    prt('%s not found ' % trace_file, ANSI.RED)
    sys.exit(1)

  origin = args.origin
  if args.dev_server:
    origin = 'http://localhost:10000'

  prt('Opening the trace (%s) in the browser' % trace_file)
  open_trace_in_browser(
      trace_file,
      open_browser,
      origin,
      referrer='open_trace_in_ui',
      remote_browser=args.remote_browser)


if __name__ == '__main__':
  sys.exit(main())
