#!/usr/bin/env python3
# Copyright (C) 2023 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os
import sys

TOOLS_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.dirname(TOOLS_DIR)
# Add the /tools dir to the front of the PATH so our hermetic node is used.
os.environ['PATH'] = TOOLS_DIR + os.pathsep + os.environ['PATH']
sys.path.append(ROOT_DIR)
__package__ = 'tools'
from .run_buildtools_binary import run_buildtools_binary
run_buildtools_binary(['pnpm'] + sys.argv[1:])
