#!/bin/bash

# Copyright (C) 2018 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -euo pipefail

OUTDIR=out/linux_fuzzer_run

tools/gn gen "$OUTDIR" \
  --args="is_clang=true is_debug=false is_fuzzer=true is_asan=true" \
  --check

tools/ninja -C $OUTDIR

FUZZERS=$(cd $OUTDIR && ls *fuzzer)

for fuzzer in $FUZZERS; do
  mkdir -p "fuzz_out/$fuzzer/corpus"
  mkdir -p "fuzz_out/$fuzzer/artifacts"
  for crash in $(ls fuzz_out/$fuzzer/artifacts/crash-* 2> /dev/null); do
    if "$OUTDIR/$fuzzer" "$crash"; then
      rm $crash;
    else
      echo "$crash still exists"
    fi
  done;

  "$OUTDIR/$fuzzer" -artifact_prefix="fuzz_out/$fuzzer/artifacts/" \
    "fuzz_out/$fuzzer/corpus" 2> "fuzz_out/$fuzzer/log.err" &
done

for job in `jobs -p`
do
    wait $job
done
