#!/usr/bin/env python3
# Copyright (C) 2019 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file should do the same thing when being invoked in any of these ways:
# ./trace_processor
# python trace_processor
# bash trace_processor
# cat ./trace_processor | bash
# cat ./trace_processor | python -

BASH_FALLBACK = """ "
exec python3 - "$@" <<'#'EOF
#"""

TOOL_NAME = 'trace_processor_shell'

# BEGIN_SECTION_GENERATED_BY(roll-prebuilts)
# Revision: v27.0
PERFETTO_PREBUILT_MANIFEST = [{
    'tool':
        'trace_processor_shell',
    'arch':
        'mac-amd64',
    'file_name':
        'trace_processor_shell',
    'file_size':
        7483288,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v27.0/mac-amd64/trace_processor_shell',
    'sha256':
        '5c50e883faea326555f4cc08bd2b01f0eb94aed8c0a96b3c5513effdfb18446d',
    'platform':
        'darwin',
    'machine': ['x86_64']
}, {
    'tool':
        'trace_processor_shell',
    'arch':
        'mac-arm64',
    'file_name':
        'trace_processor_shell',
    'file_size':
        6228936,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v27.0/mac-arm64/trace_processor_shell',
    'sha256':
        'bfbb669a0eebe4c9ab87bd58e4a6353d809f8bcb605cccd1fd8d6e44ceb9b78c',
    'platform':
        'darwin',
    'machine': ['arm64']
}, {
    'tool':
        'trace_processor_shell',
    'arch':
        'linux-amd64',
    'file_name':
        'trace_processor_shell',
    'file_size':
        8044560,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v27.0/linux-amd64/trace_processor_shell',
    'sha256':
        '54ec8a15bf6b0b2cf93103ede4982b370f8902315e3204b6421364ce8c8ced58',
    'platform':
        'linux',
    'machine': ['x86_64']
}, {
    'tool':
        'trace_processor_shell',
    'arch':
        'linux-arm',
    'file_name':
        'trace_processor_shell',
    'file_size':
        5754252,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v27.0/linux-arm/trace_processor_shell',
    'sha256':
        '49809f97924f1c6bd93e42e84fd8c95f6760d147cba8a90efcfb6faefc1669a0',
    'platform':
        'linux',
    'machine': ['armv6l', 'armv7l', 'armv8l']
}, {
    'tool':
        'trace_processor_shell',
    'arch':
        'linux-arm64',
    'file_name':
        'trace_processor_shell',
    'file_size':
        7160568,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v27.0/linux-arm64/trace_processor_shell',
    'sha256':
        '50eec568ccec27d6f4d370a275eb454a768e3977c8342e1b12d679087334a4c2',
    'platform':
        'linux',
    'machine': ['aarch64']
}, {
    'tool':
        'trace_processor_shell',
    'arch':
        'android-arm',
    'file_name':
        'trace_processor_shell',
    'file_size':
        4804920,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v27.0/android-arm/trace_processor_shell',
    'sha256':
        '61f167ae82ea5fd1ebc6133e8bf934be4c001997812c4840a17f1dae9b01ab56'
}, {
    'tool':
        'trace_processor_shell',
    'arch':
        'android-arm64',
    'file_name':
        'trace_processor_shell',
    'file_size':
        6424736,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v27.0/android-arm64/trace_processor_shell',
    'sha256':
        '7517606d3e59e6f5168c0707c09886052a613b3b7ae10ff007a509a2879fd12c'
}, {
    'tool':
        'trace_processor_shell',
    'arch':
        'android-x86',
    'file_name':
        'trace_processor_shell',
    'file_size':
        7295244,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v27.0/android-x86/trace_processor_shell',
    'sha256':
        '46bccc77e8ac076f3136f24165c882c2e6810e3659b2c612f8c5fbf7a5a3b34f'
}, {
    'tool':
        'trace_processor_shell',
    'arch':
        'android-x64',
    'file_name':
        'trace_processor_shell',
    'file_size':
        7682240,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v27.0/android-x64/trace_processor_shell',
    'sha256':
        'c3af39b4d0e035ece9cd29ab557ab2a0a330575e3b931ec2f77184e45fd03339'
}, {
    'tool':
        'trace_processor_shell',
    'arch':
        'windows-amd64',
    'file_name':
        'trace_processor_shell.exe',
    'file_size':
        7857152,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v27.0/windows-amd64/trace_processor_shell.exe',
    'sha256':
        '9fc40dc927901e4fb0d235a3b721a3cf9a615953ded0fafc22a8943d81b30fff',
    'platform':
        'win32',
    'machine': ['amd64']
}]


# DO NOT EDIT. If you wish to make edits to this code, you need to change only
# //tools/get_perfetto_prebuilt.py and run /tools/roll-prebuilts to regenerate
# all the others scripts this is embedded into.
def get_perfetto_prebuilt(tool_name, soft_fail=False, arch=None):
  """ Downloads the prebuilt, if necessary, and returns its path on disk. """

  # The first time this is invoked, it downloads the |url| and caches it into
  # ~/.perfetto/prebuilts/$tool_name. On subsequent invocations it just runs the
  # cached version.
  def download_or_get_cached(file_name, url, sha256):
    import os, hashlib, subprocess
    dir = os.path.join(
        os.path.expanduser('~'), '.local', 'share', 'perfetto', 'prebuilts')
    os.makedirs(dir, exist_ok=True)
    bin_path = os.path.join(dir, file_name)
    sha256_path = os.path.join(dir, file_name + '.sha256')
    needs_download = True

    # Avoid recomputing the SHA-256 on each invocation. The SHA-256 of the last
    # download is cached into file_name.sha256, just check if that matches.
    if os.path.exists(bin_path) and os.path.exists(sha256_path):
      with open(sha256_path, 'rb') as f:
        digest = f.read().decode()
        if digest == sha256:
          needs_download = False

    if needs_download:
      # Either the filed doesn't exist or the SHA256 doesn't match.
      tmp_path = bin_path + '.tmp'
      print('Downloading ' + url)
      subprocess.check_call(['curl', '-f', '-L', '-#', '-o', tmp_path, url])
      with open(tmp_path, 'rb') as fd:
        actual_sha256 = hashlib.sha256(fd.read()).hexdigest()
      if actual_sha256 != sha256:
        raise Exception('Checksum mismatch for %s (actual: %s, expected: %s)' %
                        (url, actual_sha256, sha256))
      os.chmod(tmp_path, 0o755)
      os.rename(tmp_path, bin_path)
      with open(sha256_path, 'w') as f:
        f.write(sha256)
    return bin_path
    # --- end of download_or_get_cached() ---

  # --- get_perfetto_prebuilt() function starts here. ---
  import os, platform, sys
  plat = sys.platform.lower()
  machine = platform.machine().lower()
  manifest_entry = None
  for entry in PERFETTO_PREBUILT_MANIFEST:
    # If the caller overrides the arch, just match that (for Android prebuilts).
    if arch:
      if entry.get('arch') == arch:
        manifest_entry = entry
        break
      continue
    # Otherwise guess the local machine arch.
    if entry.get('tool') == tool_name and entry.get(
        'platform') == plat and machine in entry.get('machine', []):
      manifest_entry = entry
      break
  if manifest_entry is None:
    if soft_fail:
      return None
    raise Exception(
        ('No prebuilts available for %s-%s\n' % (plat, machine)) +
        'See https://perfetto.dev/docs/contributing/build-instructions')

  return download_or_get_cached(
      file_name=manifest_entry['file_name'],
      url=manifest_entry['url'],
      sha256=manifest_entry['sha256'])


# END_SECTION_GENERATED_BY(roll-prebuilts)

if __name__ == '__main__':
  import sys, subprocess, os
  bin_path = get_perfetto_prebuilt(TOOL_NAME)
  if sys.platform.lower() == 'win32':
    exit(subprocess.check_call([bin_path, *sys.argv[1:]]))
  os.execv(bin_path, [bin_path] + sys.argv[1:])

#EOF
