#!/usr/bin/env python3
# Copyright (C) 2021 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file should do the same thing when being invoked in any of these ways:
# ./traceconv
# python traceconv
# bash traceconv
# cat ./traceconv | bash
# cat ./traceconv | python -

BASH_FALLBACK = """ "
exec python3 - "$@" <<'#'EOF
#"""

TOOL_NAME = 'traceconv'

# BEGIN_SECTION_GENERATED_BY(roll-prebuilts)
# Revision: v27.0
PERFETTO_PREBUILT_MANIFEST = [{
    'tool':
        'traceconv',
    'arch':
        'mac-amd64',
    'file_name':
        'traceconv',
    'file_size':
        6689896,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v27.0/mac-amd64/traceconv',
    'sha256':
        '9a28b74e9d1cc79a7e9693be0f9b3193e1b10ecb8f11cd9f01fd45c417497911',
    'platform':
        'darwin',
    'machine': ['x86_64']
}, {
    'tool':
        'traceconv',
    'arch':
        'mac-arm64',
    'file_name':
        'traceconv',
    'file_size':
        5496552,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v27.0/mac-arm64/traceconv',
    'sha256':
        'cbb2c4ed53ac8530f644049800aca6d47879e8b7a15d2f90a354c36dfef1e2b8',
    'platform':
        'darwin',
    'machine': ['arm64']
}, {
    'tool':
        'traceconv',
    'arch':
        'linux-amd64',
    'file_name':
        'traceconv',
    'file_size':
        7159072,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v27.0/linux-amd64/traceconv',
    'sha256':
        'd87645feec0e1c47d8eb8c257090808115d90db3d920e304f380c99ab87354c1',
    'platform':
        'linux',
    'machine': ['x86_64']
}, {
    'tool':
        'traceconv',
    'arch':
        'linux-arm',
    'file_name':
        'traceconv',
    'file_size':
        5305732,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v27.0/linux-arm/traceconv',
    'sha256':
        '3597f23ee7fa8ad57f45711798c152bc9f1cbeb9aed124661833934f94761b89',
    'platform':
        'linux',
    'machine': ['armv6l', 'armv7l', 'armv8l']
}, {
    'tool':
        'traceconv',
    'arch':
        'linux-arm64',
    'file_name':
        'traceconv',
    'file_size':
        6342040,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v27.0/linux-arm64/traceconv',
    'sha256':
        '9a976a57ac0f99f6c527939934413e2244189e190846d2999d2f4bf18b6041a6',
    'platform':
        'linux',
    'machine': ['aarch64']
}, {
    'tool':
        'traceconv',
    'arch':
        'android-arm',
    'file_name':
        'traceconv',
    'file_size':
        4337052,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v27.0/android-arm/traceconv',
    'sha256':
        'a007a6f270005dece307589ebbd84151810d927f5a48fef399dc3633b9cbaebb'
}, {
    'tool':
        'traceconv',
    'arch':
        'android-arm64',
    'file_name':
        'traceconv',
    'file_size':
        5706496,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v27.0/android-arm64/traceconv',
    'sha256':
        'ad91fcfe07580c2b8a5cb4dbece4f327bbe5ecabbdf0100862ce84d4b01d3161'
}, {
    'tool':
        'traceconv',
    'arch':
        'android-x86',
    'file_name':
        'traceconv',
    'file_size':
        6548852,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v27.0/android-x86/traceconv',
    'sha256':
        '25fb13cfda08db37876f1be618dc0240c5f3b3107f1f649a655dd689626bf46a'
}, {
    'tool':
        'traceconv',
    'arch':
        'android-x64',
    'file_name':
        'traceconv',
    'file_size':
        6820632,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v27.0/android-x64/traceconv',
    'sha256':
        '737b50a4413db7b5e4e26e5ff3031afe437541af9b76ef9e434d8bc58a3a75b1'
}, {
    'tool':
        'traceconv',
    'arch':
        'windows-amd64',
    'file_name':
        'traceconv.exe',
    'file_size':
        6850048,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v27.0/windows-amd64/traceconv.exe',
    'sha256':
        '958d3b067f3ea5e388bd77ff4dc51ced67cf6b6fcdb3fbfbb093b8c2974da0fc',
    'platform':
        'win32',
    'machine': ['amd64']
}]


# DO NOT EDIT. If you wish to make edits to this code, you need to change only
# //tools/get_perfetto_prebuilt.py and run /tools/roll-prebuilts to regenerate
# all the others scripts this is embedded into.
def get_perfetto_prebuilt(tool_name, soft_fail=False, arch=None):
  """ Downloads the prebuilt, if necessary, and returns its path on disk. """

  # The first time this is invoked, it downloads the |url| and caches it into
  # ~/.perfetto/prebuilts/$tool_name. On subsequent invocations it just runs the
  # cached version.
  def download_or_get_cached(file_name, url, sha256):
    import os, hashlib, subprocess
    dir = os.path.join(
        os.path.expanduser('~'), '.local', 'share', 'perfetto', 'prebuilts')
    os.makedirs(dir, exist_ok=True)
    bin_path = os.path.join(dir, file_name)
    sha256_path = os.path.join(dir, file_name + '.sha256')
    needs_download = True

    # Avoid recomputing the SHA-256 on each invocation. The SHA-256 of the last
    # download is cached into file_name.sha256, just check if that matches.
    if os.path.exists(bin_path) and os.path.exists(sha256_path):
      with open(sha256_path, 'rb') as f:
        digest = f.read().decode()
        if digest == sha256:
          needs_download = False

    if needs_download:
      # Either the filed doesn't exist or the SHA256 doesn't match.
      tmp_path = bin_path + '.tmp'
      print('Downloading ' + url)
      subprocess.check_call(['curl', '-f', '-L', '-#', '-o', tmp_path, url])
      with open(tmp_path, 'rb') as fd:
        actual_sha256 = hashlib.sha256(fd.read()).hexdigest()
      if actual_sha256 != sha256:
        raise Exception('Checksum mismatch for %s (actual: %s, expected: %s)' %
                        (url, actual_sha256, sha256))
      os.chmod(tmp_path, 0o755)
      os.rename(tmp_path, bin_path)
      with open(sha256_path, 'w') as f:
        f.write(sha256)
    return bin_path
    # --- end of download_or_get_cached() ---

  # --- get_perfetto_prebuilt() function starts here. ---
  import os, platform, sys
  plat = sys.platform.lower()
  machine = platform.machine().lower()
  manifest_entry = None
  for entry in PERFETTO_PREBUILT_MANIFEST:
    # If the caller overrides the arch, just match that (for Android prebuilts).
    if arch:
      if entry.get('arch') == arch:
        manifest_entry = entry
        break
      continue
    # Otherwise guess the local machine arch.
    if entry.get('tool') == tool_name and entry.get(
        'platform') == plat and machine in entry.get('machine', []):
      manifest_entry = entry
      break
  if manifest_entry is None:
    if soft_fail:
      return None
    raise Exception(
        ('No prebuilts available for %s-%s\n' % (plat, machine)) +
        'See https://perfetto.dev/docs/contributing/build-instructions')

  return download_or_get_cached(
      file_name=manifest_entry['file_name'],
      url=manifest_entry['url'],
      sha256=manifest_entry['sha256'])


# END_SECTION_GENERATED_BY(roll-prebuilts)

if __name__ == '__main__':
  import sys, subprocess, os
  bin_path = get_perfetto_prebuilt(TOOL_NAME)
  if sys.platform.lower() == 'win32':
    exit(subprocess.check_call([bin_path, *sys.argv[1:]]))
  os.execv(bin_path, [bin_path] + sys.argv[1:])

#EOF
