#!/usr/bin/env python3
# Copyright (C) 2021 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file should do the same thing when being invoked in any of these ways:
# ./tracebox
# python tracebox
# bash tracebox
# cat ./tracebox | bash
# cat ./tracebox | python -

BASH_FALLBACK = """ "
exec python3 - "$@" <<'#'EOF
#"""

TOOL_NAME = 'tracebox'

# BEGIN_SECTION_GENERATED_BY(roll-prebuilts)
# Revision: v27.0
PERFETTO_PREBUILT_MANIFEST = [{
    'tool':
        'tracebox',
    'arch':
        'mac-amd64',
    'file_name':
        'tracebox',
    'file_size':
        1382560,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v27.0/mac-amd64/tracebox',
    'sha256':
        '114f081aad14f47bbf4357735b2b51c881ee6ccad51d812c7aba6f5327796eac',
    'platform':
        'darwin',
    'machine': ['x86_64']
}, {
    'tool':
        'tracebox',
    'arch':
        'mac-arm64',
    'file_name':
        'tracebox',
    'file_size':
        1292392,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v27.0/mac-arm64/tracebox',
    'sha256':
        '5726dad1ecb9a7b13726a5450f2ec48c88060f36e5db53f9c7c8a7391eddcc2a',
    'platform':
        'darwin',
    'machine': ['arm64']
}, {
    'tool':
        'tracebox',
    'arch':
        'linux-amd64',
    'file_name':
        'tracebox',
    'file_size':
        1804008,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v27.0/linux-amd64/tracebox',
    'sha256':
        'f5dc9a41be33fd695c9591afdabadc19a66402ce4a1859be2a61fd262fa0acf5',
    'platform':
        'linux',
    'machine': ['x86_64']
}, {
    'tool':
        'tracebox',
    'arch':
        'linux-arm',
    'file_name':
        'tracebox',
    'file_size':
        1043296,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v27.0/linux-arm/tracebox',
    'sha256':
        '379711cca648e6ee17859af8879a5a3c081f9df674cc2fb8605e21ce79bfd419',
    'platform':
        'linux',
    'machine': ['armv6l', 'armv7l', 'armv8l']
}, {
    'tool':
        'tracebox',
    'arch':
        'linux-arm64',
    'file_name':
        'tracebox',
    'file_size':
        1679368,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v27.0/linux-arm64/tracebox',
    'sha256':
        '70e88d5d1d5093a0ea298fb14797a4559addf833195f0c7638143fffa7ac740e',
    'platform':
        'linux',
    'machine': ['aarch64']
}, {
    'tool':
        'tracebox',
    'arch':
        'android-arm',
    'file_name':
        'tracebox',
    'file_size':
        1079252,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v27.0/android-arm/tracebox',
    'sha256':
        '7ee19611d152e00c73e2fdbb336da1be05d985530e3a8140870b5f5dd0531df0'
}, {
    'tool':
        'tracebox',
    'arch':
        'android-arm64',
    'file_name':
        'tracebox',
    'file_size':
        1637032,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v27.0/android-arm64/tracebox',
    'sha256':
        '12301d91ad99f354270db5a6b93159d2da0d4223b2cefae93c24eb7b27b4b42f'
}, {
    'tool':
        'tracebox',
    'arch':
        'android-x86',
    'file_name':
        'tracebox',
    'file_size':
        1656748,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v27.0/android-x86/tracebox',
    'sha256':
        '0d3ca2709e29431ce40276d37fe0b3ba870eccf10beb08f03e0e2513ad1f8faf'
}, {
    'tool':
        'tracebox',
    'arch':
        'android-x64',
    'file_name':
        'tracebox',
    'file_size':
        1890984,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v27.0/android-x64/tracebox',
    'sha256':
        '2a336da56a6da13dba9c36a1741179e04bf3b6bb7b8840061d79f1e3373f83eb'
}]


# DO NOT EDIT. If you wish to make edits to this code, you need to change only
# //tools/get_perfetto_prebuilt.py and run /tools/roll-prebuilts to regenerate
# all the others scripts this is embedded into.
def get_perfetto_prebuilt(tool_name, soft_fail=False, arch=None):
  """ Downloads the prebuilt, if necessary, and returns its path on disk. """

  # The first time this is invoked, it downloads the |url| and caches it into
  # ~/.perfetto/prebuilts/$tool_name. On subsequent invocations it just runs the
  # cached version.
  def download_or_get_cached(file_name, url, sha256):
    import os, hashlib, subprocess
    dir = os.path.join(
        os.path.expanduser('~'), '.local', 'share', 'perfetto', 'prebuilts')
    os.makedirs(dir, exist_ok=True)
    bin_path = os.path.join(dir, file_name)
    sha256_path = os.path.join(dir, file_name + '.sha256')
    needs_download = True

    # Avoid recomputing the SHA-256 on each invocation. The SHA-256 of the last
    # download is cached into file_name.sha256, just check if that matches.
    if os.path.exists(bin_path) and os.path.exists(sha256_path):
      with open(sha256_path, 'rb') as f:
        digest = f.read().decode()
        if digest == sha256:
          needs_download = False

    if needs_download:
      # Either the filed doesn't exist or the SHA256 doesn't match.
      tmp_path = bin_path + '.tmp'
      print('Downloading ' + url)
      subprocess.check_call(['curl', '-f', '-L', '-#', '-o', tmp_path, url])
      with open(tmp_path, 'rb') as fd:
        actual_sha256 = hashlib.sha256(fd.read()).hexdigest()
      if actual_sha256 != sha256:
        raise Exception('Checksum mismatch for %s (actual: %s, expected: %s)' %
                        (url, actual_sha256, sha256))
      os.chmod(tmp_path, 0o755)
      os.rename(tmp_path, bin_path)
      with open(sha256_path, 'w') as f:
        f.write(sha256)
    return bin_path
    # --- end of download_or_get_cached() ---

  # --- get_perfetto_prebuilt() function starts here. ---
  import os, platform, sys
  plat = sys.platform.lower()
  machine = platform.machine().lower()
  manifest_entry = None
  for entry in PERFETTO_PREBUILT_MANIFEST:
    # If the caller overrides the arch, just match that (for Android prebuilts).
    if arch:
      if entry.get('arch') == arch:
        manifest_entry = entry
        break
      continue
    # Otherwise guess the local machine arch.
    if entry.get('tool') == tool_name and entry.get(
        'platform') == plat and machine in entry.get('machine', []):
      manifest_entry = entry
      break
  if manifest_entry is None:
    if soft_fail:
      return None
    raise Exception(
        ('No prebuilts available for %s-%s\n' % (plat, machine)) +
        'See https://perfetto.dev/docs/contributing/build-instructions')

  return download_or_get_cached(
      file_name=manifest_entry['file_name'],
      url=manifest_entry['url'],
      sha256=manifest_entry['sha256'])


# END_SECTION_GENERATED_BY(roll-prebuilts)

if __name__ == '__main__':
  import sys, subprocess, os
  bin_path = get_perfetto_prebuilt(TOOL_NAME)
  if sys.platform.lower() == 'win32':
    exit(subprocess.check_call([bin_path, *sys.argv[1:]]))
  os.execv(bin_path, [bin_path] + sys.argv[1:])

#EOF
