#!/bin/bash

set -e

DIR=$(mktemp -d out/perfetto.XXXXXX)

function cleanup {
  rm -rf "$WORK_DIR"
  echo "Deleted temp working directory $WORK_DIR"
}

#trap cleanup EXIT

function is_mac {
  ! test -d /proc
  return $?
}

tools/gn gen $DIR --args='is_clang=true is_debug=false'
tools/ninja -C $DIR trace_to_text
hash=$(shasum $DIR/trace_to_text | cut -f1 -d' ')

if is_mac; then
  platform=mac
else
  platform=linux
fi

name=trace_to_text-$platform-$hash

gsutil cp $DIR/trace_to_text gs://perfetto/$name
gsutil cp $DIR/trace_to_text gs://chromium-telemetry/binary_dependencies/$name

echo 'Now run the following command to update tools/traceconv:'
echo "sed \"s/'$platform': '[^']*',/'$platform': '$hash',/\" --in-place tools/traceconv"

