# This file has been generated by: tools/release/roll-prebuilts v56.1
HEAPPROFD_GLIBC_PRELOAD_MANIFEST = [{
    'arch':
        'linux-amd64',
    'file_name':
        'libheapprofd_glibc_preload.so',
    'file_size':
        1059400,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v56.1/linux-amd64/libheapprofd_glibc_preload.so',
    'sha256':
        '4d7a1871f6e2e38d84789dcc6d03377853597979b069b1492272bba09bed6997',
    'platform':
        'linux',
    'machine': ['x86_64']
}, {
    'arch':
        'linux-arm',
    'file_name':
        'libheapprofd_glibc_preload.so',
    'file_size':
        629160,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v56.1/linux-arm/libheapprofd_glibc_preload.so',
    'sha256':
        '48e1480a47ceec58e30dfb82ccc40a5814163c5798e8fe1f393b5adae679383d',
    'platform':
        'linux',
    'machine': ['armv6l', 'armv7l', 'armv8l']
}, {
    'arch':
        'linux-arm64',
    'file_name':
        'libheapprofd_glibc_preload.so',
    'file_size':
        1027528,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v56.1/linux-arm64/libheapprofd_glibc_preload.so',
    'sha256':
        '1d5ba35e7f11f897d9449f02295663d3caef7de78acfdc544b050af052a07310',
    'platform':
        'linux',
    'machine': ['aarch64']
}]
