# This file has been generated by: tools/release/roll-prebuilts v55.2
HEAPPROFD_GLIBC_PRELOAD_MANIFEST = [{
    'arch':
        'linux-amd64',
    'file_name':
        'libheapprofd_glibc_preload.so',
    'file_size':
        1055920,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v55.2/linux-amd64/libheapprofd_glibc_preload.so',
    'sha256':
        '420279e52f700f59ff9473437beabe5d79351064cccf61107ea04c1f2d617ed3',
    'platform':
        'linux',
    'machine': ['x86_64']
}, {
    'arch':
        'linux-arm',
    'file_name':
        'libheapprofd_glibc_preload.so',
    'file_size':
        626928,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v55.2/linux-arm/libheapprofd_glibc_preload.so',
    'sha256':
        '1aeaff2c28682b586409257574479d56129ee5d453b9ea85cef8b6ac253c0c92',
    'platform':
        'linux',
    'machine': ['armv6l', 'armv7l', 'armv8l']
}, {
    'arch':
        'linux-arm64',
    'file_name':
        'libheapprofd_glibc_preload.so',
    'file_size':
        1024288,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v55.2/linux-arm64/libheapprofd_glibc_preload.so',
    'sha256':
        'e5ef23e8a7ca107c2b69703a3d0a579885296b4be6db731c7bfbb3aaecf09142',
    'platform':
        'linux',
    'machine': ['aarch64']
}]
