# This file has been generated by: tools/release/roll-prebuilts v56.0
PERFETTO_C_SDK_SRC_MANIFEST = [{
    'arch':
        'src',
    'file_name':
        'perfetto-c-sdk-src.zip',
    'file_size':
        1308683,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v56.0/sdk/perfetto-c-sdk-src.zip',
    'sha256':
        '920531971e60458b3e9b6df9e82f22c8661760e0a3370739c545413bd2965802'
}]
