# This file has been generated by: tools/roll-prebuilts v48.0
TRACECONV_MANIFEST = [{
    'arch':
        'mac-amd64',
    'file_name':
        'traceconv',
    'file_size':
        9041560,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v48.0/mac-amd64/traceconv',
    'sha256':
        'f2b41e14da5c30165d2b47c2e64d45a6fa445f2c68e19b72b76c67d638e058eb',
    'platform':
        'darwin',
    'machine': ['x86_64']
}, {
    'arch':
        'mac-arm64',
    'file_name':
        'traceconv',
    'file_size':
        8375512,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v48.0/mac-arm64/traceconv',
    'sha256':
        'ab88b791a5790ba08b6d13ef24ed5bbd784cc9002fa9ab1819b6dcff43b887f4',
    'platform':
        'darwin',
    'machine': ['arm64']
}, {
    'arch':
        'linux-amd64',
    'file_name':
        'traceconv',
    'file_size':
        9134136,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v48.0/linux-amd64/traceconv',
    'sha256':
        'fa22fadddb6288bdcad5d7d925928146e58419f601fc94ab76f43b5dc3b7d0fe',
    'platform':
        'linux',
    'machine': ['x86_64']
}, {
    'arch':
        'linux-arm',
    'file_name':
        'traceconv',
    'file_size':
        6753020,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v48.0/linux-arm/traceconv',
    'sha256':
        'dc183bdb577ee504f1e1ceffcf22802c6db3accc542e821f9c5041b7e10d08b0',
    'platform':
        'linux',
    'machine': ['armv6l', 'armv7l', 'armv8l']
}, {
    'arch':
        'linux-arm64',
    'file_name':
        'traceconv',
    'file_size':
        8740064,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v48.0/linux-arm64/traceconv',
    'sha256':
        '45300e5affd90426184a0789bb0871bc06c909e71ce0dc1ba235e30cc6a88d3d',
    'platform':
        'linux',
    'machine': ['aarch64']
}, {
    'arch':
        'android-arm',
    'file_name':
        'traceconv',
    'file_size':
        6792280,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v48.0/android-arm/traceconv',
    'sha256':
        '4438d1c0a843c583908fdd00831e21501979a57d8298152d2a150c0c6634d2f0'
}, {
    'arch':
        'android-arm64',
    'file_name':
        'traceconv',
    'file_size':
        8677992,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v48.0/android-arm64/traceconv',
    'sha256':
        'bd54f136daca35e69e4eb69b7ef6ccefe0e6f575f6f2ff388f92f8c524ec5bbf'
}, {
    'arch':
        'android-x86',
    'file_name':
        'traceconv',
    'file_size':
        9503704,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v48.0/android-x86/traceconv',
    'sha256':
        'ea30742d93489b034cd7cf99755176f03e49216f0600a11421305aa37e85b7d9'
}, {
    'arch':
        'android-x64',
    'file_name':
        'traceconv',
    'file_size':
        8964488,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v48.0/android-x64/traceconv',
    'sha256':
        '79ea643f978e9a90e30a5867ecf1eeaeffda014393a75b00660acaefcdb042f6'
}, {
    'arch':
        'windows-amd64',
    'file_name':
        'traceconv.exe',
    'file_size':
        8763904,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v48.0/windows-amd64/traceconv.exe',
    'sha256':
        'e32e4635371a0207fbb6cb34cc6aea40b64ec608e1053203909d3c8ec9d80a60',
    'platform':
        'win32',
    'machine': ['amd64']
}]
