# This file has been generated by: tools/roll-prebuilts 6ba75cc5d93c39d4f86e2777709a460b30ce06fc
TRACEBOX_MANIFEST = [{
    'arch':
        'mac-amd64',
    'file_name':
        'tracebox',
    'file_size':
        1498680,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/6ba75cc5d93c39d4f86e2777709a460b30ce06fc/mac-amd64/tracebox',
    'sha256':
        '57252aaf73b6a82cfb3bbc6cd68a9ec953f61296cf2c2d651125bb437dc50144',
    'platform':
        'darwin',
    'machine': ['x86_64']
}, {
    'arch':
        'mac-arm64',
    'file_name':
        'tracebox',
    'file_size':
        1376136,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/6ba75cc5d93c39d4f86e2777709a460b30ce06fc/mac-arm64/tracebox',
    'sha256':
        '5f37217af7d47b39624c62625847ec6b98db2ebd1a512e85921eb16bcb402b35',
    'platform':
        'darwin',
    'machine': ['arm64']
}, {
    'arch':
        'linux-amd64',
    'file_name':
        'tracebox',
    'file_size':
        2218840,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/6ba75cc5d93c39d4f86e2777709a460b30ce06fc/linux-amd64/tracebox',
    'sha256':
        '89b1412e66b0a227cd8d16e6bf3d7416609c153d4b5c64d6e1a7c600870cd27b',
    'platform':
        'linux',
    'machine': ['x86_64']
}, {
    'arch':
        'linux-arm',
    'file_name':
        'tracebox',
    'file_size':
        1332292,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/6ba75cc5d93c39d4f86e2777709a460b30ce06fc/linux-arm/tracebox',
    'sha256':
        'b5a3a8e0869b35bc9ceb06f3e4ca5bb6c1e1b1c5e6ea23cfed541e40a45ad96a',
    'platform':
        'linux',
    'machine': ['armv6l', 'armv7l', 'armv8l']
}, {
    'arch':
        'linux-arm64',
    'file_name':
        'tracebox',
    'file_size':
        2147464,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/6ba75cc5d93c39d4f86e2777709a460b30ce06fc/linux-arm64/tracebox',
    'sha256':
        '00fdbdfc5877352b9323b6ea1a119132b66e696941f380da117d0d47ae1baaf9',
    'platform':
        'linux',
    'machine': ['aarch64']
}, {
    'arch':
        'android-arm',
    'file_name':
        'tracebox',
    'file_size':
        1230804,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/6ba75cc5d93c39d4f86e2777709a460b30ce06fc/android-arm/tracebox',
    'sha256':
        '02ee157f995708e78f57d6e5e110054d2e2b407dbf2db120cc967c7c553081e7'
}, {
    'arch':
        'android-arm64',
    'file_name':
        'tracebox',
    'file_size':
        1854120,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/6ba75cc5d93c39d4f86e2777709a460b30ce06fc/android-arm64/tracebox',
    'sha256':
        'e0031963f623da25c387b78e20747e07829043732f5afe16cfdea9bad3c0f27c'
}, {
    'arch':
        'android-x86',
    'file_name':
        'tracebox',
    'file_size':
        1853356,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/6ba75cc5d93c39d4f86e2777709a460b30ce06fc/android-x86/tracebox',
    'sha256':
        '6e9e4b7b0d3773ab5011e476eca883eeb0ab7538fc7d2cd4642b6abc01711ba9'
}, {
    'arch':
        'android-x64',
    'file_name':
        'tracebox',
    'file_size':
        2149032,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/6ba75cc5d93c39d4f86e2777709a460b30ce06fc/android-x64/tracebox',
    'sha256':
        '4b494907a43e898047ce98271796464deb3010b6755cee8d9c8a6c341502979b'
}]
