# This file has been generated by: tools/roll-prebuilts v39.0
TRACE_PROCESSOR_SHELL_MANIFEST = [{
    'arch':
        'mac-amd64',
    'file_name':
        'trace_processor_shell',
    'file_size':
        9814280,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v39.0/mac-amd64/trace_processor_shell',
    'sha256':
        'd3b61b97f2e18aa8e6ece06b3167a012d23f895a97ed12e1f400e3f0480b72af',
    'platform':
        'darwin',
    'machine': ['x86_64']
}, {
    'arch':
        'mac-arm64',
    'file_name':
        'trace_processor_shell',
    'file_size':
        8295768,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v39.0/mac-arm64/trace_processor_shell',
    'sha256':
        '32560ee9eb8d86397fd8daec24e5e1e091e760c8cec708a1340cc7259cfd8f07',
    'platform':
        'darwin',
    'machine': ['arm64']
}, {
    'arch':
        'linux-amd64',
    'file_name':
        'trace_processor_shell',
    'file_size':
        9660152,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v39.0/linux-amd64/trace_processor_shell',
    'sha256':
        'efbbb42291eecd0bd658694c6e60f3c7df5eee8b6e23ca6a1438059ddbd65667',
    'platform':
        'linux',
    'machine': ['x86_64']
}, {
    'arch':
        'linux-arm',
    'file_name':
        'trace_processor_shell',
    'file_size':
        7066080,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v39.0/linux-arm/trace_processor_shell',
    'sha256':
        'c62db9a9be13fefc114301e5a42714e400201bbf3a90d4f35c46494fc91ac230',
    'platform':
        'linux',
    'machine': ['armv6l', 'armv7l', 'armv8l']
}, {
    'arch':
        'linux-arm64',
    'file_name':
        'trace_processor_shell',
    'file_size':
        9069000,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v39.0/linux-arm64/trace_processor_shell',
    'sha256':
        'f2f5c4de02d9bd8505bcea931de8605d93485c5479130835e49b3d6ecf23fc4a',
    'platform':
        'linux',
    'machine': ['aarch64']
}, {
    'arch':
        'android-arm',
    'file_name':
        'trace_processor_shell',
    'file_size':
        6707128,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v39.0/android-arm/trace_processor_shell',
    'sha256':
        '5a9a5b8965f7b923444cb3ec9dea10df322a22d82765335be3191314aea48bf5'
}, {
    'arch':
        'android-arm64',
    'file_name':
        'trace_processor_shell',
    'file_size':
        8234344,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v39.0/android-arm64/trace_processor_shell',
    'sha256':
        'e6033a8928bc7b3ef6a5b4e56040219824dbba858b101241eb03513b39868829'
}, {
    'arch':
        'android-x86',
    'file_name':
        'trace_processor_shell',
    'file_size':
        9148284,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v39.0/android-x86/trace_processor_shell',
    'sha256':
        '38348a3295540e3c10d6622910d42844f37d7e849d3fbd8910b734df5c09f817'
}, {
    'arch':
        'android-x64',
    'file_name':
        'trace_processor_shell',
    'file_size':
        9397672,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v39.0/android-x64/trace_processor_shell',
    'sha256':
        '2f91b3c32dd48891c0979c546074b208ea7c0aa46b8ef543835d8361cb962070'
}, {
    'arch':
        'windows-amd64',
    'file_name':
        'trace_processor_shell.exe',
    'file_size':
        9078272,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v39.0/windows-amd64/trace_processor_shell.exe',
    'sha256':
        '65e2e29e2b6c76388af17f268cf5e597896a6e135a0bbbd224174f25715f0a32',
    'platform':
        'win32',
    'machine': ['amd64']
}]
