# This file has been generated by: tools/release/roll-prebuilts v56.1
TRACECONV_MANIFEST = [{
    'arch':
        'mac-amd64',
    'file_name':
        'traceconv',
    'file_size':
        11839400,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v56.1/mac-amd64/traceconv',
    'sha256':
        '7b696e45600d03fe95121cc5710852080331874396f17297610e829887300d7f',
    'platform':
        'darwin',
    'machine': ['x86_64']
}, {
    'arch':
        'mac-arm64',
    'file_name':
        'traceconv',
    'file_size':
        10959176,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v56.1/mac-arm64/traceconv',
    'sha256':
        '99dd2ebf488af5591fb5d4be0aa1d84ac173ceed62b077dd73bfa0cff8531be4',
    'platform':
        'darwin',
    'machine': ['arm64']
}, {
    'arch':
        'linux-amd64',
    'file_name':
        'traceconv',
    'file_size':
        12057312,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v56.1/linux-amd64/traceconv',
    'sha256':
        '0d91b41016b86733e56ed641b8bf88ee4192e01470e7e5d5feb1ecb00401cdbc',
    'platform':
        'linux',
    'machine': ['x86_64']
}, {
    'arch':
        'linux-arm',
    'file_name':
        'traceconv',
    'file_size':
        9103156,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v56.1/linux-arm/traceconv',
    'sha256':
        'b68f21399e4e49b81631f0e720dd1e626562020ca25b3220df4f88ba96c73eea',
    'platform':
        'linux',
    'machine': ['armv6l', 'armv7l', 'armv8l']
}, {
    'arch':
        'linux-arm64',
    'file_name':
        'traceconv',
    'file_size':
        11435112,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v56.1/linux-arm64/traceconv',
    'sha256':
        '6641337ce8fb865a85f9538c52ab563f57ed18e62b4efbe670fca484589b4c8a',
    'platform':
        'linux',
    'machine': ['aarch64']
}, {
    'arch':
        'android-arm',
    'file_name':
        'traceconv',
    'file_size':
        9076156,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v56.1/android-arm/traceconv',
    'sha256':
        '501ef91a96d5ff2bb49df967ad169ed6f7959f4c4c910ac782672a8bf6a25cc1'
}, {
    'arch':
        'android-arm64',
    'file_name':
        'traceconv',
    'file_size':
        11292248,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v56.1/android-arm64/traceconv',
    'sha256':
        'c0488a20b6da2533557b78d10cb69d503345c3a2660460453dee5853fe27cd08'
}, {
    'arch':
        'android-x86',
    'file_name':
        'traceconv',
    'file_size':
        12661180,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v56.1/android-x86/traceconv',
    'sha256':
        '0ebd3d1a0c4c15ea32b0d15f3def3152c14967234a9ea86d6efb060a235983ed'
}, {
    'arch':
        'android-x64',
    'file_name':
        'traceconv',
    'file_size':
        11835984,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v56.1/android-x64/traceconv',
    'sha256':
        '8242ee7c63709a170c0ca3584bc1d814a420807eb1b095b224d6d48ea5bd3c31'
}, {
    'arch':
        'windows-amd64',
    'file_name':
        'traceconv.exe',
    'file_size':
        11760640,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v56.1/windows-amd64/traceconv.exe',
    'sha256':
        '10d420057affdfad9aaae34ade221a96740af233f03b9e5e387b7ae0f5c0ecab',
    'platform':
        'win32',
    'machine': ['amd64']
}]
