# This file has been generated by: tools/release/roll-prebuilts v55.3
TRACE_PROCESSOR_SHELL_MANIFEST = [{
    'arch':
        'mac-amd64',
    'file_name':
        'trace_processor_shell',
    'file_size':
        13472504,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v55.3/mac-amd64/trace_processor_shell',
    'sha256':
        '5156cc64e4cf8720cfde0da3bcef9e4f24b32ffc62bcf4258324eeb3ab3073b9',
    'platform':
        'darwin',
    'machine': ['x86_64']
}, {
    'arch':
        'mac-arm64',
    'file_name':
        'trace_processor_shell',
    'file_size':
        12470408,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v55.3/mac-arm64/trace_processor_shell',
    'sha256':
        '6d31d6c0e17734416da2b95fd623d7a3e1c4040ccf36dc27aa2f7ff6d21a2ff0',
    'platform':
        'darwin',
    'machine': ['arm64']
}, {
    'arch':
        'linux-amd64',
    'file_name':
        'trace_processor_shell',
    'file_size':
        13700320,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v55.3/linux-amd64/trace_processor_shell',
    'sha256':
        '9370711cc6134daad77db63daf4953c75a49eab4b4a8956068f5a7ce72108adc',
    'platform':
        'linux',
    'machine': ['x86_64']
}, {
    'arch':
        'linux-arm',
    'file_name':
        'trace_processor_shell',
    'file_size':
        10222736,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v55.3/linux-arm/trace_processor_shell',
    'sha256':
        '395cb05a4d5686d56006e50f645862c2fafc568d15a95e574e41026375c7b9f0',
    'platform':
        'linux',
    'machine': ['armv6l', 'armv7l', 'armv8l']
}, {
    'arch':
        'linux-arm64',
    'file_name':
        'trace_processor_shell',
    'file_size':
        13060488,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v55.3/linux-arm64/trace_processor_shell',
    'sha256':
        '5da4d13f0a76388b49a3f7d226b35d8403c3317a82df42e9f459112c5c309d9a',
    'platform':
        'linux',
    'machine': ['aarch64']
}, {
    'arch':
        'android-arm',
    'file_name':
        'trace_processor_shell',
    'file_size':
        10182236,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v55.3/android-arm/trace_processor_shell',
    'sha256':
        '17e04804b63ec153f7ce16236711adff9b0df3b6d8d4316d9ea106fac109f315'
}, {
    'arch':
        'android-arm64',
    'file_name':
        'trace_processor_shell',
    'file_size':
        12853152,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v55.3/android-arm64/trace_processor_shell',
    'sha256':
        '823bd4a5c320b5bbdd49001faa3bdc5c12f0e853663db226f30e766e7b5a9811'
}, {
    'arch':
        'android-x86',
    'file_name':
        'trace_processor_shell',
    'file_size':
        14466396,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v55.3/android-x86/trace_processor_shell',
    'sha256':
        'c57176323b995cfa2c2543431dfaaa8026424cdfdb17879ccfab1d125d54e31d'
}, {
    'arch':
        'android-x64',
    'file_name':
        'trace_processor_shell',
    'file_size':
        13416248,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v55.3/android-x64/trace_processor_shell',
    'sha256':
        'a36efe5dd1ca654a034ab4e301240cc0f0c6d346a4ae8130870b5e4430cbd2e1'
}, {
    'arch':
        'windows-amd64',
    'file_name':
        'trace_processor_shell.exe',
    'file_size':
        13336576,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v55.3/windows-amd64/trace_processor_shell.exe',
    'sha256':
        'd10cc0620dd34ac352fc1eaad96139fce3f4063b542a419dca2a1528e6792977',
    'platform':
        'win32',
    'machine': ['amd64']
}]
