# This file has been generated by: tools/roll-prebuilts v51.1
TRACEBOX_MANIFEST = [{
    'arch':
        'mac-amd64',
    'file_name':
        'tracebox',
    'file_size':
        1729080,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v51.1/mac-amd64/tracebox',
    'sha256':
        '4fc1b0a9e85cd1e93fa703bd4f074b18e6a6f1ed0883bdf3bfea886dafe7bac4',
    'platform':
        'darwin',
    'machine': ['x86_64']
}, {
    'arch':
        'mac-arm64',
    'file_name':
        'tracebox',
    'file_size':
        1591720,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v51.1/mac-arm64/tracebox',
    'sha256':
        '3735bb7aa93c3e88e60e48930896492c3cbaa611a1fd9606ebe6431a46e3afb4',
    'platform':
        'darwin',
    'machine': ['arm64']
}, {
    'arch':
        'linux-amd64',
    'file_name':
        'tracebox',
    'file_size':
        2505648,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v51.1/linux-amd64/tracebox',
    'sha256':
        '745b4db174b2429212e651fd4c6050d3a7b1837200954c4926621a43b0950577',
    'platform':
        'linux',
    'machine': ['x86_64']
}, {
    'arch':
        'linux-arm',
    'file_name':
        'tracebox',
    'file_size':
        1532472,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v51.1/linux-arm/tracebox',
    'sha256':
        'fa1ad02be8f3c47eca276f0eb695305e28ab3898a53afaa8be8e5806f673643f',
    'platform':
        'linux',
    'machine': ['armv6l', 'armv7l', 'armv8l']
}, {
    'arch':
        'linux-arm64',
    'file_name':
        'tracebox',
    'file_size':
        2386960,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v51.1/linux-arm64/tracebox',
    'sha256':
        'f298ce733e89ac4c641a6842cd590a1d3b11deadc157dd106b46845e29c61e2a',
    'platform':
        'linux',
    'machine': ['aarch64']
}, {
    'arch':
        'android-arm',
    'file_name':
        'tracebox',
    'file_size':
        1403716,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v51.1/android-arm/tracebox',
    'sha256':
        '362941d2d2bc25d22f6c17f0e00169101c6d8ee1691bb0635f6037e8101e6776'
}, {
    'arch':
        'android-arm64',
    'file_name':
        'tracebox',
    'file_size':
        2213288,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v51.1/android-arm64/tracebox',
    'sha256':
        '59a8f81f9e8575869534443115a0abe0cacd7887f9a341f5ace0eec247b40bbd'
}, {
    'arch':
        'android-x86',
    'file_name':
        'tracebox',
    'file_size':
        2426604,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v51.1/android-x86/tracebox',
    'sha256':
        '310622f9421d4dcbdb31f2f496a4f3d35ec3a568f80041ab5626b6292f8cabea'
}, {
    'arch':
        'android-x64',
    'file_name':
        'tracebox',
    'file_size':
        2254192,
    'url':
        'https://commondatastorage.googleapis.com/perfetto-luci-artifacts/v51.1/android-x64/tracebox',
    'sha256':
        '461e875916b097ce5c3f0426fae2d869d86ecdb6803f759b4f71cfc2336de162'
}]
