#!/bin/bash
# Copyright (C) 2022 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e -u
ROOT_DIR="$(dirname $(cd -P ${BASH_SOURCE[0]%/*}; pwd))"
ESLINT_PATH="$ROOT_DIR/ui/node_modules/.bin/eslint"

if [[ ! -x "$ESLINT_PATH" ]]; then
  echo "eslint not found ($ESLINT_PATH). Run '$ROOT_DIR/tools/install-build-deps --ui'"
  exit 1
fi

# Need to add node to the search path.
TOOLS_PATH="$ROOT_DIR/tools"
PATH=$TOOLS_PATH:$PATH

exec "$ESLINT_PATH" "$@"
