packet {
  ftrace_events {
    cpu: 0
    event {
      timestamp: 100
      pid: 1
      dma_heap_stat {
        inode: 123
        len: 1024
        total_allocated: 2048
      }
    }
  }
}
packet {
  ftrace_events {
    cpu: 0
    event {
      timestamp: 200
      pid: 1
      dma_heap_stat {
        inode: 123
        len: -1024
        total_allocated: 1024
      }
    }
  }
}
