packet {
  system_info {
    utsname {
      sysname: "Linux"
      release: "5.10.0"
    }
  }
}
packet {
  ftrace_events {
    cpu: 4
    event {
      timestamp: 74288080958099
      pid: 537
      cma_alloc_start {
        align: 4
        count: 6592
        name: "farawimg"
      }
    }
    event {
      timestamp: 74288191109751
      pid: 537
      cma_alloc_info {
        align: 4
        count: 6592
        err_iso: 0
        err_mig: 0
        err_test: 0
        name: "farawimg"
        nr_mapped: 832596
        nr_migrated: 6365
        nr_reclaimed: 7
        pfn: 10365824
      }
    }
  }
}