packet {
  ftrace_events {
    cpu: 7
    event {
      timestamp: 36448185787847
      pid: 156
      mm_shrink_slab_start {
        cache_items: 1
        delta: 0
        gfp_flags: 3264
        nr_objects_to_shrink: 0
        shr: 18446743882920355600
        shrink: 90
        total_scan: 0
        nid: 0
        priority: 12
      }
    }
  }
}
packet {
  ftrace_events {
    cpu: 7
    event {
      timestamp: 36448185788539
      pid: 156
      mm_shrink_slab_end {
        new_scan: 0
        retval: 0
        shr: 18446743882920355600
        shrink: 90
        total_scan: 0
        unused_scan: 0
        nid: 0
      }
    }
  }
}