/*
 * Copyright (C) 2023 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Autogenerated by the ProtoZero C compiler plugin.
// Invoked by tools/gen_c_protos
// DO NOT EDIT.
#ifndef INCLUDE_PERFETTO_PUBLIC_PROTOS_TRACE_ANDROID_ANDROID_BINDER_PARCEL_PZC_H_
#define INCLUDE_PERFETTO_PUBLIC_PROTOS_TRACE_ANDROID_ANDROID_BINDER_PARCEL_PZC_H_

#include <stdbool.h>
#include <stdint.h>

#include "perfetto/public/pb_macros.h"

PERFETTO_PB_MSG_DECL(perfetto_protos_AndroidBinderParcelEvent_ParcelMetadata);
PERFETTO_PB_MSG_DECL(perfetto_protos_ParcelFieldAnnotation);

PERFETTO_PB_ENUM_IN_MSG(perfetto_protos_AndroidBinderParcelEvent, Direction){
    PERFETTO_PB_ENUM_IN_MSG_ENTRY(perfetto_protos_AndroidBinderParcelEvent,
                                  DIRECTION_UNKNOWN) = 0,
    PERFETTO_PB_ENUM_IN_MSG_ENTRY(perfetto_protos_AndroidBinderParcelEvent,
                                  CLIENT_SEND) = 1,
    PERFETTO_PB_ENUM_IN_MSG_ENTRY(perfetto_protos_AndroidBinderParcelEvent,
                                  SERVER_RECV) = 2,
    PERFETTO_PB_ENUM_IN_MSG_ENTRY(perfetto_protos_AndroidBinderParcelEvent,
                                  SERVER_REPLY) = 3,
    PERFETTO_PB_ENUM_IN_MSG_ENTRY(perfetto_protos_AndroidBinderParcelEvent,
                                  CLIENT_RECV) = 4,
};

PERFETTO_PB_ENUM_IN_MSG(perfetto_protos_AndroidBinderParcelEvent, ParcelKind){
    PERFETTO_PB_ENUM_IN_MSG_ENTRY(perfetto_protos_AndroidBinderParcelEvent,
                                  PARCEL_KIND_UNSPECIFIED) = 0,
    PERFETTO_PB_ENUM_IN_MSG_ENTRY(perfetto_protos_AndroidBinderParcelEvent,
                                  PRIMITIVE) = 1,
    PERFETTO_PB_ENUM_IN_MSG_ENTRY(perfetto_protos_AndroidBinderParcelEvent,
                                  STRING) = 2,
    PERFETTO_PB_ENUM_IN_MSG_ENTRY(perfetto_protos_AndroidBinderParcelEvent,
                                  STRONG_BINDER) = 3,
    PERFETTO_PB_ENUM_IN_MSG_ENTRY(perfetto_protos_AndroidBinderParcelEvent,
                                  FILE_DESCRIPTOR) = 4,
    PERFETTO_PB_ENUM_IN_MSG_ENTRY(perfetto_protos_AndroidBinderParcelEvent,
                                  PARCELABLE) = 5,
    PERFETTO_PB_ENUM_IN_MSG_ENTRY(perfetto_protos_AndroidBinderParcelEvent,
                                  TYPED_OBJECT) = 6,
    PERFETTO_PB_ENUM_IN_MSG_ENTRY(perfetto_protos_AndroidBinderParcelEvent,
                                  ARRAY) = 7,
    PERFETTO_PB_ENUM_IN_MSG_ENTRY(perfetto_protos_AndroidBinderParcelEvent,
                                  VECTOR) = 8,
    PERFETTO_PB_ENUM_IN_MSG_ENTRY(perfetto_protos_AndroidBinderParcelEvent,
                                  BYTES) = 9,
    PERFETTO_PB_ENUM_IN_MSG_ENTRY(perfetto_protos_AndroidBinderParcelEvent,
                                  INTERFACE_TOKEN) = 10,
    PERFETTO_PB_ENUM_IN_MSG_ENTRY(perfetto_protos_AndroidBinderParcelEvent,
                                  OPAQUE) = 11,
};

PERFETTO_PB_MSG(perfetto_protos_ParcelFieldAnnotation);
PERFETTO_PB_FIELD(perfetto_protos_ParcelFieldAnnotation,
                  STRING,
                  const char*,
                  field_name,
                  1);
PERFETTO_PB_FIELD(perfetto_protos_ParcelFieldAnnotation,
                  STRING,
                  const char*,
                  aidl_type,
                  2);
PERFETTO_PB_FIELD(perfetto_protos_ParcelFieldAnnotation,
                  VARINT,
                  uint32_t,
                  parcel_offset,
                  3);
PERFETTO_PB_FIELD(perfetto_protos_ParcelFieldAnnotation,
                  VARINT,
                  uint32_t,
                  byte_length,
                  4);
PERFETTO_PB_FIELD(perfetto_protos_ParcelFieldAnnotation,
                  VARINT,
                  enum perfetto_protos_AndroidBinderParcelEvent_ParcelKind,
                  kind,
                  5);
PERFETTO_PB_FIELD(perfetto_protos_ParcelFieldAnnotation,
                  ZIGZAG,
                  int64_t,
                  int_preview,
                  6);
PERFETTO_PB_FIELD(perfetto_protos_ParcelFieldAnnotation,
                  FIXED64,
                  double,
                  double_preview,
                  7);
PERFETTO_PB_FIELD(perfetto_protos_ParcelFieldAnnotation,
                  STRING,
                  const char*,
                  string_preview,
                  8);
PERFETTO_PB_FIELD(perfetto_protos_ParcelFieldAnnotation,
                  STRING,
                  const char*,
                  bytes_preview,
                  9);
PERFETTO_PB_FIELD(perfetto_protos_ParcelFieldAnnotation,
                  STRING,
                  const char*,
                  binder_descriptor_preview,
                  10);
PERFETTO_PB_FIELD(perfetto_protos_ParcelFieldAnnotation,
                  MSG,
                  perfetto_protos_ParcelFieldAnnotation,
                  nested,
                  11);
PERFETTO_PB_FIELD(perfetto_protos_ParcelFieldAnnotation,
                  VARINT,
                  bool,
                  sensitive,
                  12);
PERFETTO_PB_FIELD(perfetto_protos_ParcelFieldAnnotation,
                  VARINT,
                  bool,
                  nullable,
                  13);
PERFETTO_PB_FIELD(perfetto_protos_ParcelFieldAnnotation,
                  VARINT,
                  bool,
                  is_null,
                  14);
PERFETTO_PB_FIELD(perfetto_protos_ParcelFieldAnnotation,
                  VARINT,
                  bool,
                  utf8_in_cpp,
                  15);
PERFETTO_PB_FIELD(perfetto_protos_ParcelFieldAnnotation,
                  VARINT,
                  uint32_t,
                  element_count,
                  16);
PERFETTO_PB_FIELD(perfetto_protos_ParcelFieldAnnotation,
                  STRING,
                  const char*,
                  element_aidl_type,
                  17);
PERFETTO_PB_FIELD(perfetto_protos_ParcelFieldAnnotation,
                  STRING,
                  const char*,
                  direction_marker,
                  18);
PERFETTO_PB_FIELD(perfetto_protos_ParcelFieldAnnotation,
                  STRING,
                  const char*,
                  parcelable_stability,
                  19);
PERFETTO_PB_FIELD(perfetto_protos_ParcelFieldAnnotation,
                  VARINT,
                  uint64_t,
                  fd_size_bytes,
                  20);
PERFETTO_PB_FIELD(perfetto_protos_ParcelFieldAnnotation,
                  STRING,
                  const char*,
                  fd_kind,
                  21);

PERFETTO_PB_MSG(perfetto_protos_AndroidBinderParcelEvent);
PERFETTO_PB_FIELD(perfetto_protos_AndroidBinderParcelEvent,
                  STRING,
                  const char*,
                  interface_name,
                  1);
PERFETTO_PB_FIELD(perfetto_protos_AndroidBinderParcelEvent,
                  VARINT,
                  uint32_t,
                  code,
                  2);
PERFETTO_PB_FIELD(perfetto_protos_AndroidBinderParcelEvent,
                  VARINT,
                  uint32_t,
                  flags,
                  3);
PERFETTO_PB_FIELD(perfetto_protos_AndroidBinderParcelEvent,
                  VARINT,
                  int32_t,
                  returned_status,
                  4);
PERFETTO_PB_FIELD(perfetto_protos_AndroidBinderParcelEvent,
                  VARINT,
                  enum perfetto_protos_AndroidBinderParcelEvent_Direction,
                  direction,
                  5);
PERFETTO_PB_FIELD(perfetto_protos_AndroidBinderParcelEvent,
                  FIXED64,
                  uint64_t,
                  txn_id,
                  6);
PERFETTO_PB_FIELD(perfetto_protos_AndroidBinderParcelEvent,
                  STRING,
                  const char*,
                  recorded_transaction,
                  7);
PERFETTO_PB_FIELD(perfetto_protos_AndroidBinderParcelEvent,
                  MSG,
                  perfetto_protos_ParcelFieldAnnotation,
                  annotation,
                  8);
PERFETTO_PB_FIELD(perfetto_protos_AndroidBinderParcelEvent,
                  VARINT,
                  uint64_t,
                  wall_clock_ns,
                  9);
PERFETTO_PB_FIELD(perfetto_protos_AndroidBinderParcelEvent,
                  VARINT,
                  uint64_t,
                  duration_ns,
                  10);
PERFETTO_PB_FIELD(perfetto_protos_AndroidBinderParcelEvent,
                  VARINT,
                  int32_t,
                  pid,
                  11);
PERFETTO_PB_FIELD(perfetto_protos_AndroidBinderParcelEvent,
                  VARINT,
                  int32_t,
                  tid,
                  12);
PERFETTO_PB_FIELD(perfetto_protos_AndroidBinderParcelEvent,
                  STRING,
                  const char*,
                  method_name,
                  13);
PERFETTO_PB_FIELD(perfetto_protos_AndroidBinderParcelEvent,
                  MSG,
                  perfetto_protos_AndroidBinderParcelEvent_ParcelMetadata,
                  metadata,
                  14);
PERFETTO_PB_FIELD(perfetto_protos_AndroidBinderParcelEvent,
                  VARINT,
                  bool,
                  oneway,
                  15);
PERFETTO_PB_FIELD(perfetto_protos_AndroidBinderParcelEvent,
                  STRING,
                  const char*,
                  thread_name,
                  16);

PERFETTO_PB_MSG(perfetto_protos_AndroidBinderParcelEvent_ParcelMetadata);
PERFETTO_PB_FIELD(perfetto_protos_AndroidBinderParcelEvent_ParcelMetadata,
                  VARINT,
                  uint32_t,
                  total_data_size,
                  1);
PERFETTO_PB_FIELD(perfetto_protos_AndroidBinderParcelEvent_ParcelMetadata,
                  VARINT,
                  uint32_t,
                  object_count,
                  2);
PERFETTO_PB_FIELD(perfetto_protos_AndroidBinderParcelEvent_ParcelMetadata,
                  VARINT,
                  uint32_t,
                  binder_count,
                  3);
PERFETTO_PB_FIELD(perfetto_protos_AndroidBinderParcelEvent_ParcelMetadata,
                  VARINT,
                  uint32_t,
                  file_descriptor_count,
                  4);
PERFETTO_PB_FIELD(perfetto_protos_AndroidBinderParcelEvent_ParcelMetadata,
                  VARINT,
                  uint32_t,
                  file_descriptor_array_count,
                  5);
PERFETTO_PB_FIELD(perfetto_protos_AndroidBinderParcelEvent_ParcelMetadata,
                  VARINT,
                  uint32_t,
                  pointer_count,
                  6);
PERFETTO_PB_FIELD(perfetto_protos_AndroidBinderParcelEvent_ParcelMetadata,
                  VARINT,
                  uint64_t,
                  shared_memory_bytes,
                  7);
PERFETTO_PB_FIELD(perfetto_protos_AndroidBinderParcelEvent_ParcelMetadata,
                  VARINT,
                  bool,
                  sensitive,
                  8);
PERFETTO_PB_FIELD(perfetto_protos_AndroidBinderParcelEvent_ParcelMetadata,
                  VARINT,
                  uint32_t,
                  strict_mode_policy,
                  9);
PERFETTO_PB_FIELD(perfetto_protos_AndroidBinderParcelEvent_ParcelMetadata,
                  VARINT,
                  int32_t,
                  work_source_uid,
                  10);
PERFETTO_PB_FIELD(perfetto_protos_AndroidBinderParcelEvent_ParcelMetadata,
                  VARINT,
                  bool,
                  is_rpc,
                  11);

#endif  // INCLUDE_PERFETTO_PUBLIC_PROTOS_TRACE_ANDROID_ANDROID_BINDER_PARCEL_PZC_H_
