#
# Copyright 2026 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

metric_spec {
  id: "wattson_metadata"
  dimensions: "metric_version"
  dimensions: "power_model_version"
  value: "is_crude_estimate"
  query: {
    table: {
      table_name: "_wattson_metric_metadata"
    }
    referenced_modules: "wattson.metrics.aggregation"
  }
}

metric_template_spec {
  id_prefix: "wattson_rails_marker"

  # ==========================================================
  # Dimensions
  # ==========================================================

  # 1. Period Identifier
  dimensions_specs {
    name: "period_name"
    type: STRING
  }

  # 2. Hardware Subsystem
  dimensions_specs {
    name: "subsystem"
    type: STRING
  }

  # 3. Hierarchy Type
  dimensions_specs {
    name: "breakdown_type"
    type: STRING
  }

  # 4. Component Identifier
  dimensions_specs {
    name: "component_id"
    type: INT64
    display_name: "ID"
  }

  # 5. Parent Relation
  dimensions_specs {
    name: "parent_id"
    type: INT64
    display_name: "Cluster ID"
  }

  # ==========================================================
  # Values
  # ==========================================================

  # Metric 1: Energy
  value_column_specs {
    name: "estimated_mws"
    display_name: "Energy (mWs)"
    custom_unit: "mWs"
    polarity: LOWER_IS_BETTER
  }

  # Metric 2: Power
  value_column_specs {
    name: "estimated_mw"
    display_name: "Average Power"
    unit: MILLI_WATTS
    polarity: LOWER_IS_BETTER
  }

  # ==========================================================
  # Query (Data Source)
  # ==========================================================

  query {
    table {
      table_name: "_wattson_rails_marker"
    }
    referenced_modules: "wattson.metrics.rails_metrics"
  }

  dimension_uniqueness: UNIQUE
}

metric_template_spec {
  id_prefix: "wattson_rails_trace"

  # ==========================================================
  # Dimensions
  # ==========================================================

  # 1. Period Identifier
  dimensions_specs {
    name: "period_name"
    type: STRING
  }

  # 2. Hardware Subsystem
  dimensions_specs {
    name: "subsystem"
    type: STRING
  }

  # 3. Hierarchy Type
  dimensions_specs {
    name: "breakdown_type"
    type: STRING
  }

  # 4. Component Identifier
  dimensions_specs {
    name: "component_id"
    type: INT64
    display_name: "ID"
  }

  # 5. Parent Relation
  dimensions_specs {
    name: "parent_id"
    type: INT64
    display_name: "Cluster ID"
  }

  # ==========================================================
  # Values
  # ==========================================================

  # Metric 1: Energy
  value_column_specs {
    name: "estimated_mws"
    display_name: "Energy (mWs)"
    custom_unit: "mWs"
    polarity: LOWER_IS_BETTER
  }

  # Metric 2: Power
  value_column_specs {
    name: "estimated_mw"
    display_name: "Average Power"
    unit: MILLI_WATTS
    polarity: LOWER_IS_BETTER
  }

  # ==========================================================
  # Query (Data Source)
  # ==========================================================

  query {
    table {
      table_name: "_wattson_rails_trace"
    }
    referenced_modules: "wattson.metrics.rails_metrics"
  }

  dimension_uniqueness: UNIQUE
}

metric_template_spec {
  id_prefix: "wattson_rails_startup"

  # ==========================================================
  # Dimensions
  # ==========================================================

  # 1. Period Identifier
  dimensions_specs {
    name: "period_name"
    type: STRING
  }

  # 2. Hardware Subsystem
  dimensions_specs {
    name: "subsystem"
    type: STRING
  }

  # 3. Hierarchy Type
  dimensions_specs {
    name: "breakdown_type"
    type: STRING
  }

  # 4. Component Identifier
  dimensions_specs {
    name: "component_id"
    type: INT64
    display_name: "ID"
  }

  # 5. Parent Relation
  dimensions_specs {
    name: "parent_id"
    type: INT64
    display_name: "Cluster ID"
  }

  # ==========================================================
  # Values
  # ==========================================================

  # Metric 1: Energy
  value_column_specs {
    name: "estimated_mws"
    display_name: "Energy (mWs)"
    custom_unit: "mWs"
    polarity: LOWER_IS_BETTER
  }

  # Metric 2: Power
  value_column_specs {
    name: "estimated_mw"
    display_name: "Average Power"
    unit: MILLI_WATTS
    polarity: LOWER_IS_BETTER
  }

  # ==========================================================
  # Query (Data Source)
  # ==========================================================

  query {
    table {
      table_name: "_wattson_rails_startup"
    }
    referenced_modules: "wattson.metrics.rails_metrics"
  }

  dimension_uniqueness: UNIQUE
}

metric_template_spec {
  id_prefix: "wattson_rails_cuj"

  # ==========================================================
  # Dimensions
  # ==========================================================

  # 1. Period Identifier
  dimensions_specs {
    name: "period_name"
    type: STRING
  }

  # 2. Hardware Subsystem
  dimensions_specs {
    name: "subsystem"
    type: STRING
  }

  # 3. Hierarchy Type
  dimensions_specs {
    name: "breakdown_type"
    type: STRING
  }

  # 4. Component Identifier
  dimensions_specs {
    name: "component_id"
    type: INT64
    display_name: "ID"
  }

  # 5. Parent Relation
  dimensions_specs {
    name: "parent_id"
    type: INT64
    display_name: "Cluster ID"
  }

  # ==========================================================
  # Values
  # ==========================================================

  # Metric 1: Energy
  value_column_specs {
    name: "estimated_mws"
    display_name: "Energy (mWs)"
    custom_unit: "mWs"
    polarity: LOWER_IS_BETTER
  }

  # Metric 2: Power
  value_column_specs {
    name: "estimated_mw"
    display_name: "Average Power"
    unit: MILLI_WATTS
    polarity: LOWER_IS_BETTER
  }

  # ==========================================================
  # Query (Data Source)
  # ==========================================================

  query {
    table {
      table_name: "_wattson_rails_cuj"
    }
    referenced_modules: "wattson.metrics.rails_metrics"
  }

  dimension_uniqueness: UNIQUE
}
