#
# Copyright 2026 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

metric_spec {
  id: "wattson_metadata"
  dimensions: "metric_version"
  dimensions: "power_model_version"
  value: "is_crude_estimate"
  query: {
    table: {
      table_name: "_wattson_metric_metadata"
    }
    referenced_modules: "wattson.metrics.aggregation"
  }
}

# Marker
metric_template_spec {
  id_prefix: "wattson_threads_marker"

  # --- Dimensions ---
  # 1. Period
  dimensions_specs { name: "period_name" type: STRING }
  dimensions_specs { name: "period_id" type: INT64 }

  # 2. Process Info
  dimensions_specs { name: "process_name" type: STRING }
  dimensions_specs { name: "pid" type: INT64 }

  # 3. Thread Info
  dimensions_specs { name: "thread_name" type: STRING }
  dimensions_specs { name: "tid" type: INT64 }

  # --- Values ---
  value_column_specs {
    name: "estimated_mws"
    display_name: "Active Energy (mWs)"
    custom_unit: "mWs"
    polarity: LOWER_IS_BETTER
  }
  value_column_specs {
    name: "estimated_mw"
    display_name: "Active Power"
    unit: MILLI_WATTS
    polarity: LOWER_IS_BETTER
  }
  value_column_specs {
    name: "idle_transitions_mws"
    display_name: "Idle Overhead (mWs)"
    custom_unit: "mWs"
    polarity: LOWER_IS_BETTER
  }
  value_column_specs {
    name: "total_mws"
    display_name: "Total Energy (mWs)"
    custom_unit: "mWs"
    polarity: LOWER_IS_BETTER
  }

  # --- Source ---
  query {
    table { table_name: "_wattson_threads_marker" }
    referenced_modules: "wattson.metrics.threads_metrics"
  }
}

# Full Trace
metric_template_spec {
  id_prefix: "wattson_threads_trace"

  # --- Dimensions ---
  # 1. Period
  dimensions_specs { name: "period_name" type: STRING }
  dimensions_specs { name: "period_id" type: INT64 }

  # 2. Process Info
  dimensions_specs { name: "process_name" type: STRING }
  dimensions_specs { name: "pid" type: INT64 }

  # 3. Thread Info
  dimensions_specs { name: "thread_name" type: STRING }
  dimensions_specs { name: "tid" type: INT64 }

  # --- Values ---
  value_column_specs {
    name: "estimated_mws"
    display_name: "Active Energy (mWs)"
    custom_unit: "mWs"
    polarity: LOWER_IS_BETTER
  }
  value_column_specs {
    name: "estimated_mw"
    display_name: "Active Power"
    unit: MILLI_WATTS
    polarity: LOWER_IS_BETTER
  }
  value_column_specs {
    name: "idle_transitions_mws"
    display_name: "Idle Overhead (mWs)"
    custom_unit: "mWs"
    polarity: LOWER_IS_BETTER
  }
  value_column_specs {
    name: "total_mws"
    display_name: "Total Energy (mWs)"
    custom_unit: "mWs"
    polarity: LOWER_IS_BETTER
  }

  # --- Source ---
  query {
    table { table_name: "_wattson_threads_trace" }
    referenced_modules: "wattson.metrics.threads_metrics"
  }
}

# App Startup
metric_template_spec {
  id_prefix: "wattson_threads_startup"

  # --- Dimensions ---
  # 1. Period
  dimensions_specs { name: "period_name" type: STRING }
  dimensions_specs { name: "period_id" type: INT64 }

  # 2. Process Info
  dimensions_specs { name: "process_name" type: STRING }
  dimensions_specs { name: "pid" type: INT64 }

  # 3. Thread Info
  dimensions_specs { name: "thread_name" type: STRING }
  dimensions_specs { name: "tid" type: INT64 }

  # --- Values ---
  value_column_specs {
    name: "estimated_mws"
    display_name: "Active Energy (mWs)"
    custom_unit: "mWs"
    polarity: LOWER_IS_BETTER
  }
  value_column_specs {
    name: "estimated_mw"
    display_name: "Active Power"
    unit: MILLI_WATTS
    polarity: LOWER_IS_BETTER
  }
  value_column_specs {
    name: "idle_transitions_mws"
    display_name: "Idle Overhead (mWs)"
    custom_unit: "mWs"
    polarity: LOWER_IS_BETTER
  }
  value_column_specs {
    name: "total_mws"
    display_name: "Total Energy (mWs)"
    custom_unit: "mWs"
    polarity: LOWER_IS_BETTER
  }

  # --- Source ---
  query {
    table { table_name: "_wattson_threads_startup" }
    referenced_modules: "wattson.metrics.threads_metrics"
  }
}

# CUJ
metric_template_spec {
  id_prefix: "wattson_threads_cuj"

  # --- Dimensions ---
  # 1. Period
  dimensions_specs { name: "period_name" type: STRING }
  dimensions_specs { name: "period_id" type: INT64 }

  # 2. Process Info
  dimensions_specs { name: "process_name" type: STRING }
  dimensions_specs { name: "pid" type: INT64 }

  # 3. Thread Info
  dimensions_specs { name: "thread_name" type: STRING }
  dimensions_specs { name: "tid" type: INT64 }

  # --- Values ---
  value_column_specs {
    name: "estimated_mws"
    display_name: "Active Energy (mWs)"
    custom_unit: "mWs"
    polarity: LOWER_IS_BETTER
  }
  value_column_specs {
    name: "estimated_mw"
    display_name: "Active Power"
    unit: MILLI_WATTS
    polarity: LOWER_IS_BETTER
  }
  value_column_specs {
    name: "idle_transitions_mws"
    display_name: "Idle Overhead (mWs)"
    custom_unit: "mWs"
    polarity: LOWER_IS_BETTER
  }
  value_column_specs {
    name: "total_mws"
    display_name: "Total Energy (mWs)"
    custom_unit: "mWs"
    polarity: LOWER_IS_BETTER
  }

  # --- Source ---
  query {
    table { table_name: "_wattson_threads_cuj" }
    referenced_modules: "wattson.metrics.threads_metrics"
  }
}
