name: PRs only on main or UI branches

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  pr-branch-check:
    runs-on: self-hosted
    name: pr-branch-check
    steps:
      - name: Check if target branch is allowed for merging PRs
        run: |
          # Define your list of allowed branches
          ALLOWED_BRANCHES=("main" "ui-canary" "ui-stable")

          # Get the target branch of the PR
          TARGET_BRANCH="${{ github.base_ref }}"

          echo "Pull request is targeting branch: $TARGET_BRANCH"

          # Check if the target branch is in the allowed list
          if [[ " ${ALLOWED_BRANCHES[*]} " == *" $TARGET_BRANCH "* ]]; then
            echo "✅ PR target branch $TARGET_BRANCH is in the allowed list"
            exit 0
          else
            echo "❌ PR target branch $TARGET_BRANCH is not in the allowed list"
            echo "Only the following branches are allowed for merging: ${ALLOWED_BRANCHES[*]}"
            exit 1
          fi
